export default {
  "en" : [
  " at ",
  "now",
  "one",
  "year",
  "years",
  "yr.",
  "yr.",
  "month",
  "months",
  "mo.",
  "mo.",
  "week",
  "weeks",
  "wk.",
  "wk.",
  "day",
  "days",
  "dy.",
  "dy.",
  "hour",
  "hours",
  "hr.",
  "hr.",
  "minute",
  "minutes",
  "min.",
  "min.",
  "second",
  "seconds",
  "sec.",
  "sec.",
  "a few moments ago",
  "in a few moments",
  "ago",
  "today",
  "tomorrow",
  "yesterday",
  "next $weekday()",
  "$weekday(), last week",
  "$weekday(), $weeks(-1.0) weeks ago",
  "a week from $weekday()",
  "in $weeks(-1.0) weeks, on $weekday()",
  "$days(-1.0) days ago",
  "in $days(-1.0) days"
],
  "ar" : [
  " في ",
  "الآن",
  "واحد",

  "عام",
  "سنوات",
  "عام",
  "سنوات" ,

  "شهر",
  "الشهور",
  "شهر" ,
  "الشهور" ,

  "أسبوع",
  "أسابيع",
  "أسبوع",
  "أسابيع",

  "يوم",
  "أيام",
  "يوم",
  "أيام",

  "ساعة",
  "ساعات",
  "ساعة",
  "ساعات",

  "دقيقة",
  "الدقائق",
  "دقيقة",
  "الدقائق",

  "ثانيا",
  "ثواني",
  "ثانيا",
  "ثواني",

  "قبل لحظات قليلة" ,
  "في لحظات قليلة",
  "منذ",
  "اليوم",
  "غدا",
  "في الامس",
  "ال$weekday() القادمة",
  "ال$weekday() الأسبوع الماضي",
  "ال$weekday() ، قبل weeks$() أسابيع",
  "أسبوع من ال$weekday()",
  "في weeks$() أسابيع يوم ال$weekday()",
  "منذ $days() أيام",
  "في $days() أيام"
],
  "cs": [
  " v ",
  "nyní",
  "jeden",
  "rok",
  "rok",
  "rok",
  "rok",
  "měsíc",
  "měsíce",
  "měsíc.",
  "měsíce.",
  "týden",
  "týdny",
  "týden",
  "týdny",
  "den",
  "dny",
  "den",
  "dny",
  "hodina",
  "hodiny",
  "hodina",
  "hodiny",
  "minuta",
  "minut",
  "min.",
  "min.",
  "druhý",
  "sekundy",
  "sec.",
  "sec.",
  "před několika okamžiky",
  "za pár okamžiků",
  "před",
  "dnes",
  "zítra",
  "včera",
  "příští $weekday()",
  "$weekday(), minulý týden",
  "$weekday(), před $weeks(-1.0) týdny",
  "týden od $weekday()",
  "za $weeks(-1.0) týdny, v $weekday()",
  "Před $days(-1.0) dny",
  "za $days(-1.0) dny"
],
  "de": [
  " um ",
  "jetzt",
  "einer",
  "jahr",
  "jahre",
  "jahr",
  "jahre",
  "monat",
  "monate",
  "monat",
  "monate",
  "woche",
  "wochen",
  "woce",
  "wochen",
  "tag",
  "tage",
  "tag",
  "tage",
  "stunde",
  "stunden",
  "std.",
  "std.",
  "minute",
  "minuten",
  "min.",
  "min.",
  "sekunde",
  "sekunden",
  "sek.",
  "sek.",
  "vor wenigen Augenblicken",
  "in ein paar Momenten",
  "vor",
  "heute",
  "morgen",
  "gestern",
  "nächsten $weekday()",
  "$weekday(), letzte Woche",
  "$weekday(), vor $weeks(-1.0) wochen",
  "eine Woche ab $weekday()",
  "in $weeks(-1.0) wochen, am $weekday()",
  "vor $days(-1.0) tagen",
  "in $days(-1.0) tagen"
],
  "es": [
  "a las",
  "ahora",
  "uno",
  "año",
  "años",
  "año",
  "años",
  "mes",
  "meses",
  "mes",
  "mes",
  "semana",
  "semanas",
  "semana",
  "semana",
  "día",
  "días",
  "día",
  "días",
  "hora",
  "horas",
  "hora",
  "horas",
  "minuto",
  "minutos",
  "min.",
  "min.",
  "segundo",
  "segundos",
  "seg.",
  "seg.",
  "hace unos momentos",
  "en unos momentos",
  "hace",
  "hoy",
  "mañana",
  "ayer",
  " próximo $weekday()",
  "$weekday(), la semana pasada",
  "$weekday(), hace $weeks(-1.0) semanas",
  "una semana desde el $weekday()",
  "en $weeks(-1.0) semanas, el $weekday()",
  "hace $days(-1.0) dias",
  "en $days(-1.0) días"
],
  "fr" : [
  " à ",
  "à présent",
  "une",
  "an",
  "années",
  "an",
  "années",
  "mois",
  "mois",
  "mois",
  "mois",
  "semaine",
  "semaines",
  "semaine",
  "semaines",
  "journée",
  "journées",
  "journée",
  "journées",
  "heure",
  "les heures",
  "heure",
  "heures",
  "minute",
  "minutes",
  "min.",
  "min.",
  "seconde",
  "secondes",
  "sec.",
  "sec.",
  "il y a quelques instants",
  "dans quelques instants",
  "depuis",
  "aujourd'hui",
  "demain",
  "hier",
  "$weekday() prochain",
  "$weekday(), la semaine dernière",
  "$weekday(),il y a $weeks(-1.0) semaines",
  "une semaine à partir du $weekday()",
  "dans $weeks() semaines, le $weekday()",
  "Il ya $days(-1.0) jours",
  "dans $days(-1.0) jours"
],
  "he" : [
  " בשעה ",
  "עַכשָׁיו",
  "אחד",
  "שָׁנָה",
  "שנים",
  "שָׁנָה.",
  "שנים.",
  "חוֹדֶשׁ",
  "חודשים",
  "חוֹדֶשׁ.",
  "חודשים",
  "שָׁבוּעַ",
  "שבועות",
  "שָׁבוּעַ",
  "שבועות",
  "יְוֹם",
  "ימים",
  "יְוֹם",
  "ימים",
  "שָׁעָה",
  "שעה (ות",
  "שָׁעָה",
  "שָׁעָה",
  "דַקָה",
  "דקות",
  "דַקָה",
  "דקות",
  "שְׁנִיָה",
  "שניות",
  "שְׁנִיָה",
  "שניות",
  "לפני כמה רגעים",
  "בעוד כמה רגעים",
  "לִפנֵי",
  "היום",
  "מָחָר",
  "אתמול",
  "יום $weekday()",
  "יום $weekday(), שבוע שעבר",
  "ב $weekday(), $weeks(-1.0) לפני שבועות",
  "שבוע מיום $weekday()",
  "בעוד $weeks(-1.0) שבועות, ביום $weekday()",
  "לפני $days(-1.0) ימים",
  "בעוד $days(-1.0) ימים"
],
  "hi" : [
  " पर ",
  "अब क",
  "एक",
  "साल",
  "वर्षों",
  "साल",
  "वर्षों",
  "महीना",
  "महीने",
  "महीना",
  "महीने",
  "सप्ताह",
  "सप्ताह",
  "सप्ताह",
  "सप्ताह",
  "दिन",
  "दिन",
  "दिन",
  "दिन",
  "घंटा",
  "घंटा",
  "घंटा",
  "घंटा",
  "मिनट",
  "मिनट",
  "मिनट",
  "मिनट",
  "दूसरा",
  "दूसरा",
  "दूसरा",
  "दूसरा",
  "कुछ पल पहले",
  "कुछ ही पलों में",
  "पहले",
  "आज",
  "आने वाला कल",
  "बिता हुआ कल",
  "अगले $weekday()",
  "$weekday(), पिछले सप्ताह",
  "$weekday(), $weeks(-1.0) सप्ताह पहले",
  "से एक सप्ताह $weekday()",
  "$weeks(-1.0) सप्ताह में, $weekday() को",
  "$days(-1.0) दिन पहले",
  "$days(-1.0) दिनों में"
],
  "it" : [
  " alle ",
  "adesso",
  "uno",
  "anno",
  "anni",
  "anno",
  "anni",
  "mese",
  "mesi",
  "mese",
  "mesi",
  "settimana",
  "settimane",
  "settimana",
  "settimane",
  "giorno",
  "giorni",
  "giorno",
  "giorni",
  "ora",
  "ore",
  "ora",
  "ore",
  "minuto",
  "minuti",
  "min.",
  "min.",
  "secondo",
  "secondi",
  "sec.",
  "sec.",
  "pochi istanti fa",
  "in pochi istanti",
  "fa",
  "oggi",
  "Domani",
  "ieri",
  "$weekday() prossimo",
  "$weekday(), la scorsa settimana",
  "$weekday(), $weeks(-1.0) settimane fa",
  "una settimana da $weekday()",
  "tra $weeks(-1.0) settimane, $weekday()",
  "$days(-1.0) giorni fa",
  "tra $days(-1.0) giorni"
],
  "ja" : [
  " の ",
  "今",
  "1",
  "年",
  "年",
  "年",
  "年",
  "月",
  "月",
  "月",
  "月",
  "週間",
  "数週間",
  "週間",
  "数週間",
  "日",
  "日々",
  "日",
  "日々",
  "時間",
  "時間",
  "時間",
  "時間",
  "分",
  "分",
  "分",
  "分",
  "秒",
  "秒",
  "秒",
  "秒",
  "少し前",
  "すぐに",
  "前",
  "今日",
  "明日",
  "昨日",
  "次の $weekday()",
  "先週の $weekday()",
  "$weeks(-1.0) 週間前の $weekday()",
  "$weekday() から一週間",
  "$weeks(-1.0) 週間後、$weekday()",
  "$days(-1.0)日前",
  "$days(-1.0)日で"
],
  "nl" : [
  " om ",
  "nu",
  "een",
  "jaar",
  "jaar",
  "jaar",
  "jaar",
  "maand",
  "maand",
  "maand",
  "maand",
  "week",
  "weken",
  "week",
  "weken",
  "dag",
  "dagen",
  "dag",
  "dagen",
  "uur",
  "uren",
  "uur",
  "uren.",
  "minuut",
  "minuten",
  "minuut",
  "minuten",
  "second",
  "seconden",
  "sec.",
  "sec.",
  "enkele ogenblikken geleden",
  "binnen enkele ogenblikken",
  "geleden",
  "vandaag",
  "morgen",
  "gisteren",
  "volgende $weekday()",
  "vorige week $weekday()",
  "$weekday(), $weeks(-1.0) weken geleden",
  "een week vanaf $weekday()",
  "over $weeks(-1.0) weken, op $weekday()",
  "$days(-1.0) dagen geleden",
  "binnen $days(-1.0) dagen"
],
  "pt" : [
  " às ",
  "agora",
  "1",
  "ano",
  "anos",
  "ano",
  "anos",
  "mês",
  "meses",
  "mês",
  "meses",
  "semana",
  "semanas",
  "semana",
  "semanas",
  "dia",
  "dias",
  "dia",
  "dias",
  "hora",
  "hora",
  "hora",
  "horas",
  "minuto",
  "minutos",
  "min.",
  "min.",
  "segundo",
  "segundos",
  "sec.",
  "sec.",
  "alguns momentos atrás",
  "em alguns instantes",
  "atrás",
  "hoje",
  "amanhã",
  "ontem",
  "próxima $weekday()",
  "$weekday(), semana passada",
  "$weekday(), $weeks(-1.0) semanas atrás",
  "uma semana a partir de $weekday()",
  "em $weeks(-1.0) semanas, na $weekday()",
  "$days(-1.0) dias atrás",
  "em $days(-1.0) dias"
],
  "ru" : [
  " в ",
  "сейчас",
  "один",
  "год",
  "годы",
  "год",
  "годы",
  "месяц",
  "месяцы",
  "месяц",
  "месяцы",
  "неделя",
  "недели",
  "неделя",
  "недели",
  "день",
  "дни",
  "день",
  "дни",
  "час",
  "часы",
  "час",
  "часы",
  "минута",
  "минут",
  "мин",
  "мин",
  "второй",
  "секунды",
  "сек",
  "сек",
  "несколько минут назад",
  "через несколько минут",
  "тому назад",
  "Cегодня",
  "завтра",
  "вчера",
  "в следующую $weekday()",
  "$weekday(), lна прошлой неделе",
  "$weekday(), $weeks(-1.0) недели назад",
  "неделя с $weekday()",
  "через $weeks(-1.0) недели, в $weekday()",
  "$days(-1.0) дня назад",
  "через $days(-1.0) дня"
],
  "sw" : [
  " saa ",
  "sasa",
  "moja",
  "mwaka",
  "miaka",
  "mwaka",
  "miaka",
  "mwezi",
  "miezi",
  "mwezi",
  "miezi",
  "wiki",
  "wiki",
  "wiki",
  "wiki",
  "siku",
  "siku",
  "siku",
  "siku",
  "saa",
  "masaa",
  "saa.",
  "masaa",
  "dakika",
  "dakika",
  "dk.",
  "dk.",
  "sekunde",
  "sekunde",
  "sec.",
  "sec.",
  "dakika chache zilizopita",
  "katika muda mfupi",
  "iliyopita",
  "leo",
  "kesho",
  "jana",
  "$weekday() ijayo",
  "$weekday(), wiki iliyopita",
  "$weekday(), wiki $weeks(-1.0) zilizopita",
  "wiki kutoka $weekday()",
  "katika wiki $weeks(-1.0), $weekday()",
  "siku $days(-1.0) zilizopita",
  "kwa siku $days(-1.0)"
],
  "vi" : [
  " lúc ",
  "hiện nay",
  "một",
  "năm",
  "năm",
  "năm",
  "năm",
  "tháng",
  "tháng",
  "tháng",
  "tháng",
  "tuần",
  "tuần",
  "tuần",
  "tuần",
  "ngày",
  "ngày",
  "ngày",
  "ngày",
  "giờ",
  "giờ",
  "giờ",
  "giờ",
  "phút",
  "phút",
  "phút",
  "phút",
  "giây",
  "giây",
  "giây",
  "giây",
  "một vài phút trước",
  "Trong giây lát",
  "trước",
  "hôm nay",
  "Ngày mai",
  "hôm qua",
  "$weekday() tới",
  "$weekday(), tuần trước",
  "$weekday(), $weeks(-1.0) tuần trước",
  "một tuần từ $weekday()",
  "trong $weeks(-1.0) tuần, vào $weekday()",
  "$days(-1.0) ngày trước",
  "trong $days(-1.0) ngày nữa"
],
  "zh" : [
  " ",
  "现在",
  "一",
  "年",
  "年",
  "年",
  "年",
  "月",
  "月",
  "月",
  "月",
  "星期",
  "周",
  "星期",
  "周",
  "日",
  "天",
  "日",
  "天",
  "小时",
  "小时",
  "小时",
  "小时",
  "分钟",
  "分钟",
  "分钟",
  "分钟",
  "秒",
  "秒",
  "秒",
  "秒",
  "几分钟前",
  "过一会儿",
  "前",
  "今天",
  "明天",
  "昨天",
  "next $weekday()",
  "$weekday(), 上周",
  "$weekday(), $weeks(-1.0) 周前",
  "从 $weekday() 开始的一周",
  "从 $weeks(-1.0) 周，在 $weekday()",
  "$days(-1.0) 天前",
  "在 $days(-1.0) 天"
],

  "am" : [
      "፣ ",
      "አሁን",
      "አንድ",
      "አመት",
      "ዓመታት",
      "አመት",
      "ዓመታት",
      "ወር",
      "ወሮች",
      "ወር",
      "ወሮች",
      "ሳምንት",
      "ሳምንታት",
      "ሳምንት",
      "ሳምንታት",
      "ቀን",
      "ቀናት",
      "ቀን",
      "ቀናት",
      "ሰአት",
      "ሰዓታት",
      "ሰአት",
      "ሰዓታት",
      "ደቂቃ",
      "ደቂቃዎች",
      "ደቂቃ",
      "ደቂቃዎች",
      "ሴኮንድ",
      "ሰከንዶች",
      "ሴኮንድ",
      "ሰከንዶች",
      "ከጥቂት ጊዜያት በፊት",
      "በጥቂት ጊዜያት ውስጥ",
      "በፊት",
      "ዛሬ",
      "ነገ",
      "ትናንት",
      "በሚቀጥለው $weekday()",
      "$weekday() ፣ ባለፈው ሳምንት",
      "$weekday(), ከ $weeks(-1.0) ሳምንታት በፊት",
      "ከ$weekday() አንድ ሳምንት",
      "$weekday በ $weeks(-1.0) ሳምንታት ውስጥ",
      "ከ $days(-1.0) ቀናት በፊት",
      "በ $days(-1.0) ቀናት ውስጥ"
  ],
  "az" : [
      ", ",
      "İndi",
      "bir",
      "il",
      "il",
      "il",
      "il",
      "ay",
      "ay",
      "ay",
      "ay",
      "həftə",
      "həftələr",
      "həftə",
      "həftələr",
      "gün",
      "günlər",
      "gün",
      "günlər",
      "saat",
      "saat",
      "saat",
      "saat",
      "dəqiqə",
      "dəqiqə",
      "dəqiqə",
      "dəqiqə",
      "saniyə",
      "saniyə",
      "saniyə",
      "saniyə",
      "bir neçə dəqiqə əvvəl",
      "bir neçə dəqiqədə",
      "əvvəl",
      "bu gün",
      "sabah",
      "dünən",
      "növbəti $weekday() günü",
      "$weekday() günü, keçən həftə",
      "$weekday(), $weeks(-1.0) həftə əvvəl",
      "$weekday() günündən bir həftə",
      "$weeks(-1.0) həftədə, $weekday() günü",
      "$days(-1.0) gün əvvəl",
      "$days(-1.0) günə"
  ],
  "bg" : [
      " в ",
      "сега",
      "един",
      "година",
      "години",
      "година",
      "години",
      "месец",
      "месеци",
      "месец",
      "месеци",
      "седмица",
      "седмици",
      "седмица",
      "седмици",
      "ден",
      "дни",
      "ден",
      "дни",
      "час",
      "часa",
      "час",
      "часa",
      "минута",
      "минути",
      "минута",
      "минути",
      "секунда",
      "секунди",
      "секунда",
      "секунди",
      "преди няколко мига",
      "след няколко мига",
      "преди",
      "днес",
      "утре",
      "вчера",
      "следващата $weekday()",
      "$weekday(), миналата седмица",
      "$weekday(), преди $weeks(-1.0) седмици",
      "седмица от $weekday()",
      "след $weeks(-1.0) седмици, в $weekday",
      "преди $days(-1.0) дни",
      "за $days(-1.0) дни"
  ],
  "bn" : [
      ", ",
      "এখন",
      "এক",
      "বছর",
      "বছর",
      "বছর",
      "বছর",
      "মাস",
      "মাস",
      "মাস",
      "মাস",
      "সপ্তাহ",
      "সপ্তাহ",
      "সপ্তাহ",
      "সপ্তাহ",
      "দিন",
      "দিন",
      "দিন",
      "দিন",
      "ঘন্টা",
      "ঘন্টার",
      "ঘন্টা",
      "ঘন্টার",
      "মিনিট",
      "মিনিট",
      "মিনিট",
      "মিনিট",
      "সেকেন্ড",
      "সেকেন্ড",
      "সেকেন্ড",
      "সেকেন্ড",
      "কয়েক মুহুর্ত আগে",
      "কয়েক মুহুর্তে",
      "আগে",
      "আজ",
      "আগামীকাল",
      "গতকাল",
      "পরবর্তী $weekday()",
      "$weekday(), গত সপ্তাহে",
      "$weekday(), $weeks(-1.0) সপ্তাহ আগে",
      "$weekday() থেকে এক সপ্তাহ",
      "$weeks(-1.0) সপ্তাহে, $weekday()",
      "$days(-1.0) দিন আগে",
      "$days(-1.0) দিনের মধ্যে"
  ],

  "bs" : [
      " u ",
      "sad",
      "jedan",
      "godine",
      "godine",
      "godine",
      "godine",
      "mjesec",
      "mjeseci",
      "mjesec",
      "mjeseci",
      "sedmica",
      "sedmice",
      "sedmica",
      "sedmice",
      "dan",
      "dana",
      "dan",
      "dana",
      "sat",
      "sati",
      "sat",
      "sati",
      "minutu",
      "minuta",
      "minutu",
      "minuta",
      "sekunda",
      "sekunde",
      "sekunda",
      "sekunde",
      "pre nekoliko trenutaka",
      "za nekoliko trenutaka",
      "prije",
      "danas",
      "sutra",
      "juce",
      "sljedeći $weekday()",
      "$weekday(), prošli tjedan",
      "$weekday(), prije $weeks(-1.0) sedmice",
      "tjedan dana od $weekday()",
      "za $weeks(-1.0) sedmice, u $weekday()",
      "Pre $days(-1.0) dana",
      "za $days(-1.0) dana"
  ],
  "ca" : [
      " a les ",
      "ara",
      "un",
      "curs",
      "anys",
      "curs",
      "anys",
      "mes",
      "mesos",
      "mes",
      "mesos",
      "setmana",
      "setmanes",
      "setmana",
      "setmanes",
      "dia",
      "dies",
      "dia",
      "dies",
      "hores",
      "hores",
      "hores",
      "hores",
      "minut",
      "minuts",
      "minut",
      "minuts",
      "segon",
      "segons",
      "segon",
      "segons",
      "fa uns moments",
      "en pocs moments",
      "fa",
      "avui",
      "demà",
      "ahir",
      "el pròxim $weekday()",
      "$weekday(), la setmana passada",
      "$weekday(), fa $weeks(-1.0) setmanes",
      "a la setmana del $weekday()",
      "en $weeks(-1.0) setmanes, el $weekday()",
      "fa $days(-1.0) dies",
      "en $days(-1.0) dies"

  ],
  "da" : [
      " kl ",
      "nu",
      "en",
      "år",
      "flere år",
      "år.",
      "år.",
      "måned",
      "måneder",
      "måned",
      "måneder",
      "uge",
      "uger",
      "uge",
      "uger",
      "dag",
      "dage",
      "dag",
      "dage",
      "time",
      "timer",
      "time",
      "timer",
      "minut",
      "minutter",
      "min.",
      "min.",
      "sekund",
      "sekunder",
      "sek.",
      "sek.",
      "for et øjeblik siden",
      "om få øjeblikke",
      "siden",
      "i dag",
      "i morgen",
      "i går",
      "næste $weekday()",
      "$weekday(), sidste uge",
      "$weekday(), for $weeks(-1.0) uger siden",
      "en uge fra $weekday()",
      "om $weeks(-1.0) uger, $weekday()",
      "$days(-1.0) dage siden",
      "om $days(-1.0) dage"
  ],
  "el" : [
      " στις ",
      "τώρα",
      "ένας",
      "έτος",
      "χρόνια",
      "ε.",
      "ε.",
      "μήνας",
      "μήνες",
      "μου.",
      "μου.",
      "εβδομάδα",
      "εβδομάδες",
      "β.",
      "β.",
      "ημέρα",
      "μέρες",
      "δ.",
      "δ.",
      "ώρα",
      "ώρες",
      "ωρ.",
      "ωρ.",
      "λεπτό",
      "λεπτά",
      "λεπτό",
      "λεπτά",
      "δευτερόλεπτο",
      "δευτερόλεπτα",
      "δευτ.",
      "δευτ.",
      "πριν από λίγα λεπτά",
      "σε λίγες στιγμές",
      "πριν",
      "σήμερα",
      "αύριο",
      "εχθές",
      "την επόμενη $weekday()",
      "$weekday(), περασμένη εβδομάδα",
      "$weekday(), $weeks(-1.0) εβδομάδες πριν",
      "μια εβδομάδα από $weekday()",
      "σε $weeks(-1.0) εβδομάδες, την $weekday()",
      " πριν από $days(-1.0) ημέρες",
      "σε $days(-1.0) ημέρες"
  ],
  "et" : [
      " kell ",
      "nüüd",
      "üks",
      "aasta",
      "aastat",
      "a.",
      "a.",
      "kuu",
      "kuud",
      "kuu",
      "kuud",
      "nädal",
      "nädalat",
      "nädal",
      "nädalat",
      "päeval",
      "päeva",
      "päeval",
      "päeva",
      "tund",
      "tundi",
      "tund",
      "tundi",
      "minut",
      "minutit",
      "min.",
      "min.",
      "sekund",
      "sekundit",
      "s.",
      "s.",
      "mõni hetk tagasi",
      "mõne hetke pärast",
      "tagasi",
      "täna",
      "homme",
      "eile",
      "järgmisel $weekday()",
      "$weekday() nädala pühapäev",
      "$weekday(), $weeks(-1.0) nädalat tagasi",
      "nädal alates $weekday()",
      "$weeks(-1.0) nädala pärast, $weekday()",
      "$days(-1.0) päeva tagasi",
      "$days(-1.0) päeva pärast"
  ],
  "fa" : [
      " ساعت ",
      "اکنون",
      "یکی",
      "سال",
      "سال ها",
      "سال",
      "سال ها",
      "ماه",
      "ماه ها",
      "ماه",
      "ماه ها",
      "هفته",
      "هفته ها",
      "هفته",
      "هفته ها",
      "روز",
      "روزها",
      "روز",
      "روزها",
      "ساعت",
      "ساعت ها",
      "ساعت",
      "ساعت ها",
      "دقیقه",
      "دقایق",
      "دقیقه",
      "دقایق",
      "ثانیه",
      "ثانیه",
      "ثانیه",
      "ثانیه",
      "چند لحظه پیش",
      "در چند لحظه",
      "پیش",
      "امروز",
      "فردا",
      "دیروز",
      "$weekday() بعدی",
      "$weekday()، هفته گذشته",
      "$weekday()، $weeks(-1.0) هفته پیش",
      "یک هفته از $weekday()",
      "در $weeks(-1.0) هفته ، $weekday()",
      "$days(-1.0) روز پیش",
      "در $days(-1.0) روز"
  ],
  "fi" : [
      " klo ",
      "nyt",
      "yksi",
      "vuosi",
      "vuotta",
      "v.",
      "v.",
      "kuukausi",
      "kuukaudet",
      "k.",
      "k.",
      "viikko",
      "viikkoa",
      "viikko",
      "viikkoa",
      "päivä",
      "päivää",
      "päivä",
      "päivää",
      "tunnin",
      "tuntia",
      "t.",
      "t.",
      "minuutti",
      "pöytäkirja",
      "min.",
      "min.",
      "sekunti",
      "sekuntia",
      "sek.",
      "sek.",
      "muutama hetki sitten",
      "hetkessä",
      "sitten",
      "tänään",
      "huomenna",
      "eilen",
      "ensi $weekday()",
      "$weekday(), viime viikko",
      "$weekday(), $weeks(-1.0) viikkoa sitten",
      "viikko $weekday()",
      "$weeks(-1.0) viikon kuluttua $weekday()",
      "$days(-1.0) päivää sitten",
      "$days(-1.0) päivässä"
  ],
  "fil" : [
      " ng ",
      "ngayon",
      "isa",
      "taon",
      "taon",
      "taon",
      "taon",
      "buwan",
      "buwan",
      "buwan",
      "buwan",
      "linggo",
      "linggo",
      "linggo",
      "linggo",
      "araw",
      "araw",
      "araw",
      "araw",
      "oras",
      "oras",
      "oras",
      "oras",
      "minuto",
      "minuto",
      "min.",
      "min.",
      "segundo",
      "segundo",
      "seg.",
      "seg.",
      "ilang sandali ang nakaraan",
      "sa ilang sandali",
      "nakaraan",
      "ngayon",
      "bukas",
      "kahapon",
      "sa susunod na $weekday()",
      "$weekday(), noong nakaraang linggo",
      "$weekday(), $weeks(-1.0) linggo ang nakakaraan",
      "isang linggo mula $weekday()",
      "sa $weeks(-1.0) linggo, sa $weekday()",
      "$days(-1.0) araw na ang nakakalipas",
      "sa $days(-1.0) araw"
  ],
  "hr" : [
      " u ",
      "sada",
      "jedan",
      "godina",
      "godine",
      "godina",
      "godine",
      "mjesec",
      "mjeseci",
      "mjesec",
      "mjeseci",
      "tjedan",
      "tjedni",
      "tjedan",
      "tjedni",
      "dan",
      "dana",
      "dan",
      "dana",
      "sat",
      "sati",
      "sat",
      "sati",
      "minuta",
      "minuta",
      "min.",
      "min.",
      "sekundu",
      "sekunde",
      "sek.",
      "sek.",
      "prije nekoliko trenutaka",
      "za nekoliko trenutaka",
      "prije",
      "danas",
      "sutra",
      "jučer",
      "sljedeći $weekday()",
      "$weekday(), prošli tjedan",
      "$weekday(), prije $weeks(-1.0) tjedna",
      "tjedan dana od $weekday()",
      "za $weeks(-1.0) tjedna, u $weekday()",
      "prije $days(-1.0) dana",
      "za $days(-1.0) dana"
  ],
  "hu" : [
      ", ",
      "Most",
      "egy",
      "év",
      "évek",
      "év",
      "évek",
      "hónap",
      "hónapok",
      "hónap",
      "hónapok",
      "hét",
      "hétig",
      "hét",
      "hétig",
      "nap",
      "napok",
      "nap",
      "napok",
      "óra",
      "órák",
      "óra",
      "órák",
      "perc",
      "percek",
      "perc",
      "percek",
      "másodperc",
      "másodpercig",
      "mp.",
      "mp.",
      "néhány pillanattal ezelőtt",
      "néhány pillanat múlva",
      "ezelőtt",
      "Ma",
      "holnap",
      "tegnap",
      "jövő $weekday()",
      "Múlt hét $weekday()",
      "hete hete, $weekday()",
      "$weekday() egy hét",
      "$weeks(-1.0) hét múlva, $weekday()",
      "$days(-1.0) napja",
      "$days(-1.0) napon belül"
  ],
  "id" : [
      " pukul ",
      "sekarang",
      "satu",
      "tahun",
      "tahun",
      "thn.",
      "thn.",
      "bulan",
      "bulan",
      "bulan",
      "bulan",
      "minggu",
      "minggu",
      "minggu",
      "minggu",
      "hari",
      "hari",
      "hari",
      "hari",
      "jam",
      "jam",
      "jam",
      "jam",
      "menit",
      "menit",
      "menit",
      "menit",
      "detik",
      "detik",
      "detik",
      "detik",
      "beberapa saat yang lalu",
      "dalam beberapa saat",
      "lalu",
      "hari ini",
      "besok",
      "kemarin",
      "$weekday() depan",
      "$weekday(), minggu lalu",
      "$weekday(), $weeks(-1.0) minggu yang lalu",
      "seminggu dari hari $weekday()",
      "dalam $weeks(-1.0) minggu, pada hari $weekday()",
      "$days(-1.0) hari yang lalu",
      "dalam $days(-1.0) hari"
  ],
  "kn" : [
      ", ",
      "ಈಗ",
      "ಒಂದು",
      "ವರ್ಷ",
      "ವರ್ಷಗಳು",
      "ವರ್ಷ",
      "ವರ್ಷಗಳು",
      "ತಿಂಗಳು",
      "ತಿಂಗಳುಗಳು",
      "ತಿಂಗಳು",
      "ತಿಂಗಳುಗಳು",
      "ವಾರ",
      "ವಾರಗಳು",
      "ವಾರ",
      "ವಾರಗಳು",
      "ದಿನ",
      "ದಿನಗಳು",
      "ದಿನ",
      "ದಿನಗಳು",
      "ಗಂಟೆ",
      "ಗಂಟೆಗಳು",
      "ಗಂ.",
      "ಗಂ.",
      "ನಿಮಿಷ",
      "ನಿಮಿಷಗಳು",
      "ನಿಮಿಷ.",
      "ನಿಮಿಷ.",
      "ಸೆಕೆಂಡ್",
      "ಸೆಕೆಂಡುಗಳು",
      "ಸೆ.",
      "ಸೆ.",
      "ಕೆಲವು ಕ್ಷಣಗಳ ಹಿಂದೆ",
      "ಕೆಲವು ಕ್ಷಣಗಳಲ್ಲಿ",
      "ಹಿಂದೆ",
      "ಇಂದು",
      "ನಾಳೆ",
      "ನಿನ್ನೆ",
      "ಮುಂದಿನ $weekday()",
      "ಕಳೆದ ವಾರ $weekday()",
      "$weeks(-1.0) ವಾರಗಳ ಹಿಂದೆ $weekday()",
      "$weekday()ದಿಂದ ಒಂದು ವಾರ",
      "$weeks(-1.0) ವಾರಗಳಲ್ಲಿ, $weekday()",
      "$days(-1.0) ದಿನಗಳ ಹಿಂದೆ",
      "$days(-1.0) ದಿನಗಳಲ್ಲಿ"
  ],
  "lt" : [
      ", ",
      "dabar",
      "vienas",
      "metus",
      "metų",
      "m.",
      "m.",
      "mėnesį",
      "mėnesių",
      "mėn.",
      "mėn.",
      "savaitę",
      "savaičių",
      "sav.",
      "sav.",
      "dieną",
      "dienų",
      "dieną",
      "dienų",
      "valandą",
      "valandos",
      "val.",
      "val.",
      "minutė",
      "minučių",
      "min.",
      "min.",
      "sekundė",
      "sekundžių",
      "sek.",
      "sek.",
      "prieš kelias akimirkas",
      "per kelias akimirkas",
      "prieš",
      "šiandien",
      "rytoj",
      "vakar",
      "kitą $weekday()",
      "Praėjusios savaitės $weekday()",
      "Prieš $weeks(-1.0) savaites, $weekday()",
      "savaitę nuo $weekday()",
      "po $weeks(-1.0) savaičių, $weekday()",
      "prieš $days(-1.0) dienas",
      "per $days(-1.0) dienas"
  ],
  "lv" : [
      " pulksten ",
      "tagad",
      "viens",
      "gadā",
      "gadiem",
      "g.",
      "g.",
      "mēnesī",
      "mēnešus",
      "mēnesī",
      "mēnešus",
      "nedēļu",
      "nedēļas",
      "ned.",
      "ned.",
      "diena",
      "dienas",
      "diena",
      "dienas",
      "stunda",
      "stundas",
      "stunda",
      "stundas",
      "minūti",
      "minūtes",
      "min.",
      "min.",
      "sekunde",
      "sekundes",
      "sek.",
      "sek.",
      "pirms dažiem mirkļiem",
      "pēc dažiem mirkļiem",
      "pirms",
      "šodien",
      "rīt",
      "vakar",
      "nākamajā $weekday()",
      "$weekday(), pagājušā nedēļa",
      "Pirms $weeks(-1.0) nedēļām $weekday",
      "a week from $weekday()",
      "nedēļu no $weekday()",
      "pēc $weeks(-1.0) nedēļām, $weekday()",
      "Pirms $days(-1.0) dienām",
      "$days(-1.0) 3 dienu laikā"
  ],
  "ml" : [
    ", ",
    "ഇപ്പോൾ",
    "ഒന്ന്",
    "വർഷം",
    "വർഷങ്ങൾ",
    "വർഷം",
    "വർഷങ്ങൾ",
    "മാസം",
    "മാസം",
    "മാസം",
    "മാസം",
    "ആഴ്ച",
    "ആഴ്ചകൾ",
    "ആഴ്ച",
    "ആഴ്ചകൾ",
    "ദിവസം",
    "ദിവസങ്ങളിൽ",
    "ദിവസം",
    "ദിവസങ്ങളിൽ",
    "മണിക്കൂർ",
    "മണിക്കൂറുകൾ",
    "മ.",
    "മ.",
    "മിനിറ്റ്",
    "മിനിറ്റ്",
    "മിനിറ്റ്",
    "മിനിറ്റ്",
    "സെക്കൻഡ്",
    "സെക്കൻഡ്",
    "സെക്കൻഡ്",
    "സെക്കൻഡ്",
    "കുറച്ച് നിമിഷങ്ങൾക്ക് മുമ്പ്",
    "കുറച്ച് നിമിഷങ്ങൾക്കുള്ളിൽ",
    "മുമ്പ്",
    "ഇന്ന്",
    "നാളെ",
    "ഇന്നലെ",
    "$weekday() അടുത്തത്",
    "കഴിഞ്ഞ ആഴ്ച $weekday()",
    "$weeks(-1.0) ആഴ്ച മുമ്പ് $weekday()",
    "a week from $weekday()",
    "$weekday() മുതൽ ഒരാഴ്ച",
    "$weeks(-1.0) ആഴ്ചയ്ക്കുള്ളിൽ, $weekday()",
    "$days(-1.0) ദിവസം മുൻപ്",
    "$days(-1.0) ദിവസത്തിനുള്ളിൽ"
  ],
  "mr" : [
      ", ",
      "आता",
      "एक",
      "वर्ष",
      "वर्षे",
      "वर्ष",
      "वर्षे",
      "आठवडा",
      "महिने",
      "आठवडा",
      "महिने",
      "आठवडा",
      "आठवडे",
      "आठवडा",
      "आठवडे",
      "दिवस",
      "दिवस",
      "दिवस",
      "दिवस",
      "तास",
      "तास",
      "तास",
      "तास",
      "मिनिट",
      "मिनिटे",
      "मिनिट",
      "मिनिटे",
      "सेकंद",
      "सेकंद",
      "सेकंद",
      "सेकंद",
      "काही क्षणांपूर्वी",
      "काही क्षणात",
      "पूर्वी",
      "आज",
      "उद्या",
      "काल",
      "पुढच्या $weekday()",
      "$weekday(), गेल्या आठवड्यात",
      "$weekday(), $weeks(-1.0) आठवड्यांपूर्वी",
      "a week from $weekday()",
      "$weekday() पासून एक आठवडा",
      "$weeks(-1.0) आठवड्यात, $weekday()",
      "$days(-1.0) दिवसांपूर्वी",
      "$days(-1.0) दिवसात"
  ],
  "ms" : [
    ", ",
    "sekarang",
    "satu",
    "tahun",
    "tahun",
    "thn.",
    "thn.",
    "bulan",
    "bulan",
    "bulan",
    "bulan",
    "minggu",
    "minggu",
    "minggu",
    "minggu",
    "hari",
    "hari-hari",
    "hari",
    "hari-hari",
    "jam",
    "Jam",
    "jam",
    "Jam",
    "minit",
    "minit",
    "min.",
    "min.",
    "saat",
    "saat",
    "sek.",
    "sek.",
    "beberapa saat yang lalu",
    "dalam beberapa saat",
    "yang lalu",
    "hari ini",
    "esok",
    "semalam",
    "$weekday() depan",
    "$weekday(), minggu lalu",
    "$weekday(), $weeks(-1.0) minggu yang lalu",
    "seminggu dari hari $weekday()",
    "in $weeks(-1.0) weeks, on $weekday()",
    "dalam $weeks(-1.0) minggu, pada hari $weekday()",
    "$days(-1.0) hari yang lepas",
    "dalam $days(-1.0) hari"
  ],
  "nb" : [
    " kl ",
    "nå",
    "en",
    "år",
    "år",
    "år",
    "år",
    "måned",
    "måneder",
    "måned",
    "måneder",
    "uke",
    "uker",
    "uke",
    "uker",
    "dag",
    "dager",
    "dag",
    "dager",
    "time",
    "timer",
    "time",
    "timer",
    "minutt",
    "minutter",
    "min.",
    "min.",
    "sekund",
    "sekunder",
    "sek.",
    "sek.",
    "for noen øyeblikk siden",
    "om noen få øyeblikk",
    "siden",
    "i dag",
    "i morgen",
    "i går",
    "neste $weekday()",
    "$weekday(), forrige uke",
    "$weekday(), for $weeks(-1.0) uker siden",
    "en uke fra $weekday()",
    "om $weeks(-1.0) uker, på $weekday()",
    "$days(-1.0) dager siden",
    "om $days(-1.0) dager"

  ],
  "pa" : [
    ", ",
    "ਹੁਣ",
    "ਇਕ",
    "ਸਾਲ",
    "ਸਾਲ",
    "ਸਾਲ",
    "ਸਾਲ",
    "ਮਹੀਨਾ",
    "ਮਹੀਨੇ",
    "ਮਹੀਨਾ",
    "ਮਹੀਨੇ",
    "ਹਫ਼ਤਾ",
    "ਹਫ਼ਤੇ",
    "ਹਫ਼ਤਾ",
    "ਹਫ਼ਤੇ",
    "ਦਿਨ",
    "ਦਿਨ",
    "ਦਿਨ",
    "ਦਿਨ",
    "ਘੰਟਾ",
    "ਘੰਟੇ",
    "ਘੰਟਾ",
    "ਘੰਟੇ",
    "ਮਿੰਟ",
    "ਮਿੰਟ",
    "ਮਿੰਟ",
    "ਮਿੰਟ",
    "ਸਕਿੰਟ",
    "ਸਕਿੰਟ",
    "ਸਕਿੰਟ",
    "ਸਕਿੰਟ",
    "ਕੁਝ ਪਲ ਪਹਿਲਾਂ",
    "ਕੁਝ ਪਲਾਂ ਵਿਚ",
    "ਪਹਿਲਾਂ",
    "ਅੱਜ",
    "ਕੱਲ",
    "ਕੱਲ",
    "ਅਗਲਾ $weekday()",
    "$weekday(), ਪਿਛਲੇ ਹਫ਼ਤੇ",
    "$weekday(), $weeks(-1.0) ਹਫ਼ਤੇ ਪਹਿਲਾਂ",
    "$weekday() ਤੋਂ ਇਕ ਹਫਤਾ",
    "$weeks(-1.0) ਹਫਤਿਆਂ ਵਿਚ, $weekday()",
    "$days(-1.0) ਦਿਨ ਪਹਿਲਾਂ",
    "$days(-1.0) ਦਿਨਾਂ ਵਿਚ"

  ],
  "pl" : [
    " o ",
    "teraz",
    "jeden",
    "rok",
    "lat",
    "rok",
    "lat",
    "miesiąc",
    "miesięcy",
    "miesiąc",
    "miesięcy",
    "tydzień",
    "tygodnie",
    "tydzień",
    "tygodnie",
    "dzień",
    "dni",
    "dzień",
    "dni",
    "godzina",
    "godziny",
    "godz.",
    "godz.",
    "minuta",
    "minuty",
    "min.",
    "min.",
    "sekunda",
    "sekundy",
    "ust.",
    "ust.",
    "kilka chwil temu",
    "za kilka chwil",
    "temu",
    "dzisiaj",
    "jutro",
    "wczoraj",
    "w następną $weekday()",
    "$weekday(), ostatni tydzień",
    "$weekday(), $weeks(-1.0) tygodnie temu",
    "tydzień od $weekday()",
    "za $weeks(-1.0) tygodnie, w $weekday()",
    "$days(-1.0) dni temu",
    "w $days(-1.0) dni"
  ],
  "ro" : [
    " la ",
    "acum",
    "unu",
    "an",
    "ani",
    "an",
    "ani",
    "lună",
    "luni",
    "lună",
    "luni",
    "săptămână",
    "săptămâni",
    "săptămână",
    "săptămâni",
    "zi",
    "zile",
    "zi",
    "zile",
    "ora",
    "ore",
    "ora",
    "ore",
    "minut",
    "minute",
    "minut",
    "minute",
    "secunda",
    "secunde",
    "secunda",
    "secunde",
    "acum câteva clipe",
    "în câteva clipe",
    "în urmă",
    "azi",
    "Mâine",
    "ieri",
    "$weekday() viitoare",
    "$weekday(), săptămâna trecută",
    "$weekday(), acum $weeks(-1.0) săptămâni",
    "o săptămână de $weekday()",
    "în $weeks(-1.0) săptămâni, $weekday()",
    "acum $days(-1.0) zile",
    "în $days(-1.0) zile"
  ],
  "sk" : [
    " o ",
    "teraz",
    "jeden",
    "rok",
    "rokov",
    "rok",
    "rokov",
    "mesiac",
    "mesiacov",
    "mesiac",
    "mesiacov",
    "týždeň",
    "týždňov",
    "týždeň",
    "týždňov",
    "deň",
    "dni",
    "deň",
    "dni",
    "hodinu",
    "hodin",
    "hodinu",
    "hodin",
    "minútu",
    "minút",
    "minútu",
    "minút",
    "sekunda",
    "sekúnd",
    "sekunda",
    "sekúnd",
    "pred pár okamihmi",
    "za pár okamihov",
    "pred",
    "dnes",
    "zajtra",
    "včera",
    "budúci $weekday()",
    "$weekday(), minulý týždeň",
    "$weekday(), pred $weeks(-1.0) týždňami",
    "týždeň od $weekday()",
    "o $weeks(-1.0) týždne, v $weekday()",
    "Pred $days(-1.0) dňami",
    "za $days(-1.0) dni"
  ],
  "sl" : [
    " ob ",
    "zdaj",
    "eno",
    "leto",
    "letih",
    "leto",
    "letih",
    "mesec",
    "mesecev",
    "mesec",
    "mesecev",
    "teden",
    "tednov",
    "teden",
    "tednov",
    "dan",
    "dnevi",
    "dan",
    "dnevi",
    "uro",
    "ure",
    "uro",
    "ure",
    "minuta",
    "minut",
    "min.",
    "min.",
    "sekundo",
    "sekund",
    "sek.",
    "sek.",
    "pred nekaj trenutki",
    "v nekaj trenutkih",
    "nazaj",
    "danes",
    "jutri",
    "včeraj",
    "naslednji $weekday()",
    "$weekday(), prejšnji teden",
    "$weekday(), pred $weeks(-1.0) tedni",
    "teden dni od $weekday()",
    "čez $weeks(-1.0) tedne, v $weekday()",
    "Pred $days(-1.0) dnevi",
    "v $days(-1.0) dneh"

  ],
  "sr" : [
    " у ",
    "Сада",
    "једно",
    "године",
    "године",
    "год.",
    "год.",
    "месец дана",
    "месеци",
    "месец дана",
    "месеци",
    "Недеља",
    "недеље",
    "Недеља",
    "недеље",
    "дан",
    "дана",
    "дан",
    "дана",
    "сат",
    "сати",
    "xp.",
    "xp.",
    "минуту",
    "минута",
    "мин.",
    "мин.",
    "секунда",
    "секунде",
    "cek.",
    "cek.",
    "пре неколико тренутака",
    "за неколико тренутака",
    "пре",
    "данас",
    "сутра",
    "јуче",
    "следећи $weekday()",
    "$weekday(), прошле недеље",
    "$weekday(), пре $weeks(-1.0) недеље",
    "недељу дана од $weekday()",
    "за $weeks(-1.0) недеље, у $weekday()",
    "$days(-1.0) дана пре",
    "за $days(-1.0) дана"

  ],
  "sv" : [
    " kl ",
    "nu",
    "ett",
    "år",
    "år",
    "år",
    "år",
    "månad",
    "månader",
    "mån.",
    "mån.",
    "vecka",
    "Veckor",
    "vecka",
    "Veckor",
    "dag",
    "dager",
    "dag",
    "dager",
    "timme",
    "timmar",
    "tim.",
    "tim.",
    "minut",
    "minuter",
    "min.",
    "min.",
    "sekund",
    "sekunder",
    "sek.",
    "sek.",
    "för några ögonblick sedan",
    "på några ögonblick",
    "sedan",
    "i dag",
    "i morgon",
    "i går",
    "nästa $weekday()",
    "$weekday(), förra veckan",
    "$weekday(), för $weeks(-1.0) veckor sedan",
    "en vecka från $weekday()",
    "om $weeks(-1.0) veckor, på $weekday()",
    "$days(-1.0) dagar sedan",
    "om $days(-1.0) dager"

  ],
  "ta" : [
    ",  ",
    "இப்போது",
    "ஒன்று",
    "ஆண்டு",
    "ஆண்டுகள்",
    "ஆண்டு",
    "ஆண்டுகள்",
    "மாதம்",
    "மாதங்கள்",
    "மாதம்",
    "மாதங்கள்",
    "வாரம்",
    "வாரங்கள்",
    "வாரம்",
    "வாரங்கள்",
    "நாள்",
    "நாட்களில்",
    "நாள்",
    "நாட்களில்",
    "மணி",
    "மணி",
    "மணி",
    "மணி",
    "நிமிடம்",
    "நிமிடங்கள்",
    "நிமிடம்",
    "நிமிடம்",
    "வினாடி",
    "விநாடிகள்",
    "நொடி.",
    "நொடி.",
    "சில தருணங்களுக்கு முன்பு",
    "சில தருணங்களில்",
    "முன்பு",
    "இன்று",
    "நாளை",
    "நேற்று",
    "அடுத்த $weekday()",
    "கடந்த வாரம் $weekday()",
    "$weekday(), $weeks(-1.0) வாரங்களுக்கு முன்பு",
    "$weekday() முதல் ஒரு வாரம்",
    "$weeks(-1.0) வாரங்களில், $weekday()",
    "$days(-1.0) நாட்களுக்கு முன்பு",
    "$days(-1.0) நாட்களில்"
  ],
  "te" : [
    ", ",
    "ఇప్పుడు",
    "ఒకటి",
    "సంవత్సరం",
    "సంవత్సరాలు",
    "సంవత్సరం",
    "సంవత్సరాలు",
    "నెల",
    "నెలల",
    "నెల",
    "నెలల",
    "వారం",
    "వారాలు",
    "వారం",
    "వారాలు",
    "వారం",
    "వారాలు",
    "రోజులు",
    "వారాలు",
    "రోజులు",
    "గంట",
    "గంటలు",
    "గం.",
    "గం.",
    "నిమిషం",
    "నిమిషాలు",
    "నిమి.",
    "నిమి.",
    "సెకను",
    "సెకన్లు",
    "సెక.",
    "సెక.",
    "కొన్ని క్షణాల క్రితం",
    "కొన్ని క్షణాల్లో",
    "క్రితం",
    "ఈ రోజు",
    "రేపు",
    "నిన్న",
    "వచ్చే $weekday()",
    "$weekday() సోమవారం",
    "$weekday(), $weeks(-1.0) వారాల క్రితం",
    "$weekday() నుండి ఒక వారం",
    "$weeks(-1.0) వారాలలో, $weekday()",
    "$days(-1.0) రోజుల క్రితం",
    "$days(-1.0) రోజుల్లో"
  ],
  "th" : [
    ", ",
    "రోజుల్లో",
    "หนึ่ง",
    "ปี",
    "ปี",
    "ปี",
    "ปี",
    "เดือน",
    "เดือน",
    "เดือน",
    "เดือน",
    "สัปดาห์",
    "สัปดาห์",
    "สัปดาห์",
    "สัปดาห์",
    "วัน",
    "วัน",
    "วัน",
    "วัน",
    "ชั่วโมง",
    "ชั่วโมง",
    "ชม.",
    "ชม.",
    "นาที",
    "นาที",
    "นาที",
    "นาที",
    "วินาที",
    "วินาที",
    "วินาที",
    "วินาที",
    "เมื่อสักครู่นี้",
    "ในอีกสักครู่",
    "มาแล้ว",
    "วันนี้",
    "พรุ่งนี้",
    "เมื่อวาน",
    "$weekday()หน้า",
    "$weekday() อาทิตย์ที่แล้ว",
    "$weekday(), $weeks(-1.0) สัปดาห์ก่อน",
    "หนึ่งสัปดาห์ตั้งแต่ $weekday()",
    "ใน $weeks(-1.0) สัปดาห์ใน$weekday()",
    "$days(-1.0) วันที่ผ่านมา",
    "ใน $days(-1.0) วัน"

  ],
  "tr" : [
    " saat ",
    "şimdi",
    "bir",
    "yıl",
    "yıllar",
    "yıl",
    "yıl",
    "ay",
    "aylar",
    "ay.",
    "ay.",
    "hafta",
    "haftalar",
    "hafta",
    "haftalar",
    "gün",
    "günler",
    "gün",
    "günler",
    "saat",
    "saatler",
    "saat",
    "saatler",
    "dakika",
    "dakika",
    "dk.",
    "dk.",
    "saniye",
    "saniye",
    "sn.",
    "sn.",
    "birkaç dakika önce",
    "birkaç dakika içinde",
    "önce",
    "bugün",
    "yarın",
    "dün",
    "gelecek $weekday()",
    "$weekday(), geçen hafta",
    "$weekday(), $weeks(-1.0) hafta önce",
    "$weekday()dan bir hafta",
    "$weeks(-1.0) hafta sonra, $weekday()",
    "$days(-1.0) gün önce",
    "$days(-1.0) gün içerisinde"

  ],
  "uk" : [
    " о ",
    "зараз",
    "один",
    "рік",
    "років",
    "рік",
    "років",
    "місяць",
    "місяців",
    "місяць",
    "місяців",
    "тиждень",
    "тижнів",
    "тиждень",
    "тижнів",
    "день",
    "днів",
    "день",
    "днів",
    "год",
    "годин",
    "год",
    "годин",
    "хвилини",
    "хвилин",
    "хв.",
    "хв.",
    "секунда",
    "секунд",
    "сек.",
    "сек.",
    "кілька хвилин тому",
    "за кілька хвилин",
    "тому",
    "сьогодні",
    "завтра",
    "вчора",
    "наступного $weekday()",
    "$weekday(), минулого тижня",
    "$weekday(), $weeks(-1.0) тижні тому",
    "тиждень з $weekday()",
    "через $weeks(-1.0) тижні, у $weekday()",
    "$days(-1.0) дні тому",
    "через $days(-1.0) дні"
  ],
  "uz" : [
    " soat ",
    "hozir",
    "bitta",
    "yil",
    "yil",
    "yil",
    "yil",
    "oy",
    "oylar",
    "oy",
    "oylar",
    "hafta",
    "hafta",
    "hafta",
    "hafta",
    "kun",
    "kunlar",
    "kun",
    "kunlar",
    "soat",
    "soat",
    "soat",
    "soat",
    "daqiqa",
    "daqiqa",
    "daqiqa",
    "daqiqa",
    "soniya",
    "soniya",
    "soniya",
    "soniya",
    "bir necha lahza oldin",
    "bir necha lahzada",
    "oldin",
    "Bugun",
    "ertaga",
    "kecha",
    "keyingi $weekday()",
    "$weekday(), o'tgan hafta",
    "$weekday(), $weeks(-1.0) hafta oldin",
    "$weekday()dan bir hafta",
    "$weeks(-1.0) hafta ichida, $weekday() kuni",
    "$days(-1.0) kun oldin",
    "$days(-1.0) kun ichida"
  ]
}
/*
   at
   Sunday at 12:34
  now
  one
  year
  years
  yr.
  yr.
  month
  months
  mo.
  mo.
  week
  weeks
  wk.
  wk.
  day
  days
  dy.
  dy.
  hour
  hours
  hr.
  hr.
  minute
  minutes
  min.
  min.
  second
  seconds
  sec.
  sec.
  a few moments ago
  in a few moments
  ago
  today
  tomorrow
  yesterday

   --- next $weekday()
  next Sunday
   --- $weekday(), last week
  Sunday, last week
   --- $weekday(), $weeks(-1.0) weeks ago
  Sunday, 3 weeks ago
   --- a week from $weekday()
  a week from Sunday
   --- in $weeks(-1.0) weeks, on $weekday()
  in 3 weeks, on Sunday
   --- $days(-1.0) days ago
  3 days ago
   --- in $days(-1.0) days
  in 3 days


 */