export default {
    "am": [
        "2021 ፌብሩወሪ 14, እሑድ 12:34:56 ከሰዓት የተቀናጀ ሁለንተናዊ ሰዓት",
        "14 ፌብሩወሪ 2021 12:34:56 ከሰዓት UTC",
        "14/02/2021 12:34 ከሰዓት",
        "2021 ፌብሩወሪ 14, እሑድ 12:34:56 ከሰዓት - ጁላይ 6, እሑድ 12:34:56 ከሰዓት የተቀናጀ ሁለንተናዊ ሰዓት",
        "አሁን",
        "ከጥቂት ደቂቃዎች በፊት",
        "በጥቂት ጊዜያት ውስጥ",
        "ዛሬ",
        "ነገ",
        "ትናንት",
        "2020 ጁላይ 6",
        "2021 ጁን 6",
        "ማክሰኞ ፣ ባለፈው ሳምንት",
        "ትናንት",
        "ከ1 ሰዓት በፊት",
        "ከ1 ደቂቃ በፊት",
        "ከጥቂት ደቂቃዎች በፊት",
        "2022 ጁላይ 6",
        "2021 ኦገስት 6",
        "በሚቀጥለው ማክሰኞ",
        "ነገ",
        "በ1 ሰዓት ውስጥ",
        "በ1 ደቂቃ ውስጥ",
        "በጥቂት ጊዜያት ውስጥ",
        "2017 ጁላይ 6",
        "2021 ማርች 6",
        "2021 ጁን 15",
        "ዓርብ ፣ ባለፈው ሳምንት",
        "ከ 2 ቀናት በፊት",
        "ከ2 ሰዓታት በፊት",
        "ከ2 ደቂቃዎች በፊት",
        "ከ20 ሰከንዶች በፊት",
        "2025 ጁላይ 6",
        "2021 ኖቬምበር 6",
        "በ 3 ሳምንቶች, በ ማክሰኞ",
        "በሚቀጥለው ቅዳሜ",
        "በ 2 ቀናት ውስጥ",
        "በ2 ሰዓታት ውስጥ",
        "በ2 ደቂቃዎች ውስጥ",
        "በ20 ሰከንዶች ውስጥ"
    ],
    "ar": [
        "الأحد، ١٤ فبراير ٢٠٢١ ١٢:٣٤:٥٦ م التوقيت العالمي المنسق",
        "١٤ فبراير ٢٠٢١ ١٢:٣٤:٥٦ م UTC",
        "١٤‏/٢‏/٢٠٢١ ١٢:٣٤ م",
        "الأحد, فبراير 14, 2021 12:34:56 مساءً - الثلاثاء, يوليو 6, 12:34:56 مساءً توقيت عالمي متناسق",
        "الآن",
        "قبل لحظات قليلة",
        "في لحظات قليلة",
        "اليوم",
        "غدا",
        "في الامس",
        "الاثنين, يوليو 6, 2020",
        "الأحد, يونيو 6, 2021",
        "الالثلاثاء الأسبوع الماضي",
        "في الامس",
        "قبل ساعة واحدة",
        "قبل دقيقة واحدة",
        "قبل لحظات قليلة",
        "الأربعاء, يوليو 6, 2022",
        "الجمعة, أغسطس 6, 2021",
        "الالثلاثاء القادمة",
        "غدا",
        "خلال ساعة واحدة",
        "خلال دقيقة واحدة",
        "في لحظات قليلة",
        "الخميس, يوليو 6, 2017",
        "السبت, مارس 6, 2021",
        "الثلاثاء, يونيو 15, 2021",
        "الالجمعة الأسبوع الماضي",
        "منذ 2 أيام",
        "قبل ساعتين",
        "قبل دقيقتين",
        "قبل ٢٠ ثانية",
        "الأحد, يوليو 6, 2025",
        "السبت, نوفمبر 6, 2021",
        "في weeks[object Object] أسابيع يوم الالثلاثاء",
        "الالسبت القادمة",
        "في 2 أيام",
        "خلال ساعتين",
        "خلال دقيقتين",
        "خلال ٢٠ ثانية"
    ],
    "az": [
        "14 fevral 2021, bazar 12:34:56 Koordinasiya edilmiş ümumdünya vaxtı",
        "14 fevral 2021 12:34:56 UTC",
        "14.02.21 12:34",
        "fevral 14 2021 bazar, 56aat 12:34:56 - iyul 6 56aat 12:34:56 Razılaşdırılmış Universal Saat",
        "İndi",
        "bir neçə dəqiqə əvvəl",
        "bir neçə dəqiqədə",
        "bu gün",
        "sabah",
        "dünən",
        "iyul 6 2020 bazar ertəsi",
        "iyun 6 2021 bazar",
        "çərşənbə axşamı günü, keçən həftə",
        "dünən",
        "1 saat öncə",
        "1 dəqiqə öncə",
        "bir neçə dəqiqə əvvəl",
        "iyul 6 2022 çərşənbə",
        "avqust 6 2021 cümə",
        "növbəti çərşənbə axşamı günü",
        "sabah",
        "1 saat ərzində",
        "1 dəqiqə ərzində",
        "bir neçə dəqiqədə",
        "iyul 6 2017 cümə axşamı",
        "mart 6 2021 şənbə",
        "iyun 15 2021 çərşənbə axşamı",
        "cümə günü, keçən həftə",
        "2 gün əvvəl",
        "2 saat öncə",
        "2 dəqiqə öncə",
        "20 saniyə öncə",
        "iyul 6 2025 bazar",
        "noyabr 6 2021 şənbə",
        "3 həftədə, çərşənbə axşamı günü",
        "növbəti şənbə günü",
        "2 günə",
        "2 saat ərzində",
        "2 dəqiqə ərzində",
        "20 saniyə ərzində"
    ],
    "bg": [
        "неделя, 14 февруари 2021 г., 12:34:56 ч. Координирано универсално време",
        "14 февруари 2021 г., 12:34:56 ч. UTC",
        "14.02.21 г., 12:34 ч.",
        "неделя, 14 февруари 2021 в 12:34:56 - вторник, 6 юли 12:34:56 Координирано универсално време",
        "сега",
        "преди няколко мига",
        "след няколко мига",
        "днес",
        "утре",
        "вчера",
        "понеделник, 6 юли 2020",
        "неделя, 6 юни 2021",
        "вторник, миналата седмица",
        "вчера",
        "преди 1 час",
        "преди 1 минута",
        "преди няколко мига",
        "сряда, 6 юли 2022",
        "петък, 6 август 2021",
        "следващата вторник",
        "утре",
        "след 1 час",
        "след 1 минута",
        "след няколко мига",
        "четвъртък, 6 юли 2017",
        "събота, 6 март 2021",
        "вторник, 15 юни 2021",
        "петък, миналата седмица",
        "преди 2 дни",
        "преди 2 часа",
        "преди 2 минути",
        "преди 20 секунди",
        "неделя, 6 юли 2025",
        "събота, 6 ноември 2021",
        "след 3weekday",
        "следващата събота",
        "за 2 дни",
        "след 2 часа",
        "след 2 минути",
        "след 20 секунди"
    ],
    "bn": [
        "রবিবার, ১৪ ফেব্রুয়ারী, ২০২১ ১২:৩৪:৫৬ PM স্থানাংকিত আন্তর্জাতিক সময়",
        "১৪ ফেব্রুয়ারী, ২০২১ ১২:৩৪:৫৬ PM UTC",
        "১৪/২/২১ ১২:৩৪ PM",
        "রবিবার, 14 ফেব্রুয়ারী 2021 এ 12:34:56 - মঙ্গলবার, 6 জুলাই 12:34:56 সমন্বয়িত ইউনিভার্সাল টাইম",
        "এখন",
        "কয়েক মুহুর্ত আগে",
        "কয়েক মুহুর্তে",
        "আজ",
        "আগামীকাল",
        "গতকাল",
        "সোমবার, 6 জুলাই 2020",
        "রবিবার, 6 জুন 2021",
        "মঙ্গলবার, গত সপ্তাহে",
        "গতকাল",
        "১ ঘন্টা আগে",
        "১ মিনিট আগে",
        "কয়েক মুহুর্ত আগে",
        "বুধবার, 6 জুলাই 2022",
        "শুক্রবার, 6 আগস্ট 2021",
        "পরবর্তী মঙ্গলবার",
        "আগামীকাল",
        "১ ঘন্টায়",
        "১ মিনিটে",
        "কয়েক মুহুর্তে",
        "বৃহস্পতিবার, 6 জুলাই 2017",
        "শনিবার, 6 মার্চ 2021",
        "মঙ্গলবার, 15 জুন 2021",
        "শুক্রবার, গত সপ্তাহে",
        "2 দিন আগে",
        "২ ঘন্টা আগে",
        "২ মিনিট আগে",
        "২০ সেকেন্ড পূর্বে",
        "রবিবার, 6 জুলাই 2025",
        "শনিবার, 6 নভেম্বর 2021",
        "3 সপ্তাহে, মঙ্গলবার",
        "পরবর্তী শনিবার",
        "2 দিনের মধ্যে",
        "২ ঘন্টায়",
        "২ মিনিটে",
        "২০ সেকেন্ডে"
    ],
    "bs": [
        "nedjelja, 14. februar 2021. u 12:34:56 Koordinirano svjetsko vrijeme",
        "14. februar 2021. u 12:34:56 UTC",
        "14. 2. 2021. 12:34",
        "nedjelja, 14. februar 2021. 1613306096 12:34:56 - utorak, 6. juli 12:34:56 Univerzalno koordinirano vrijeme",
        "sad",
        "pre nekoliko trenutaka",
        "za nekoliko trenutaka",
        "danas",
        "sutra",
        "juce",
        "ponedjeljak, 6. juli 2020.",
        "nedjelja, 6. juni 2021.",
        "utorak, prošli tjedan",
        "juce",
        "prije 1 sat",
        "prije 1 minutu",
        "pre nekoliko trenutaka",
        "srijeda, 6. juli 2022.",
        "petak, 6. august 2021.",
        "sljedeći utorak",
        "sutra",
        "za 1 sat",
        "za 1 minutu",
        "za nekoliko trenutaka",
        "četvrtak, 6. juli 2017.",
        "subota, 6. mart 2021.",
        "utorak, 15. juni 2021.",
        "petak, prošli tjedan",
        "pre 2 dana",
        "prije 2 sata",
        "prije 2 minute",
        "prije 20 sekundi",
        "nedjelja, 6. juli 2025.",
        "subota, 6. novembar 2021.",
        "za 3 sedmice, u utorak",
        "sljedeći subota",
        "za 2 dana",
        "za 2 sata",
        "za 2 minute",
        "za 20 sekundi"
    ],
    "ca": [
        "diumenge, 14 de febrer de 2021 a les 12:34:56 Temps universal coordinat",
        "14 de febrer de 2021 a les 12:34:56 UTC",
        "14/2/21 12:34",
        "diumenge 14 de de febrer de 2021 a le56 12:34:56 - dimarts 6 de de juliol de 56 12:34:56 Temps Universal Coordinat",
        "ara",
        "fa uns moments",
        "en pocs moments",
        "avui",
        "demà",
        "ahir",
        "dilluns 6 de de juliol de 2020",
        "diumenge 6 de de juny de 2021",
        "dimarts, la setmana passada",
        "ahir",
        "fa 1 hora",
        "fa 1 minut",
        "fa uns moments",
        "dimecres 6 de de juliol de 2022",
        "divendres 6 de d’agost de 2021",
        "el pròxim dimarts",
        "demà",
        "d’aquí a 1 hora",
        "d’aquí a 1 minut",
        "en pocs moments",
        "dijous 6 de de juliol de 2017",
        "dissabte 6 de de març de 2021",
        "dimarts 15 de de juny de 2021",
        "divendres, la setmana passada",
        "fa 2 dies",
        "fa 2 hores",
        "fa 2 minuts",
        "fa 20 segons",
        "diumenge 6 de de juliol de 2025",
        "dissabte 6 de de novembre de 2021",
        "en 3 setmanes, el dimarts",
        "el pròxim dissabte",
        "en 2 dies",
        "d’aquí a 2 hores",
        "d’aquí a 2 minuts",
        "d’aquí a 20 segons"
    ],
    "cs": [
        "neděle 14. února 2021 12:34:56 Koordinovaný světový čas",
        "14. února 2021 12:34:56 UTC",
        "14.02.21 12:34",
        "neděle 14. února 2021 v 12:34:56 - úterý 6. července 12:34:56 Koordinovaný světový čas",
        "nyní",
        "před několika okamžiky",
        "za pár okamžiků",
        "dnes",
        "zítra",
        "včera",
        "pondělí 6. července 2020",
        "neděle 6. června 2021",
        "úterý, minulý týden",
        "včera",
        "před 1 hodinou",
        "před 1 minutou",
        "před několika okamžiky",
        "středa 6. července 2022",
        "pátek 6. srpna 2021",
        "příští úterý",
        "zítra",
        "za 1 hodinu",
        "za 1 minutu",
        "za pár okamžiků",
        "čtvrtek 6. července 2017",
        "sobota 6. března 2021",
        "úterý 15. června 2021",
        "pátek, minulý týden",
        "před 2 dny",
        "před 2 hodinami",
        "před 2 minutami",
        "před 20 sekundami",
        "neděle 6. července 2025",
        "sobota 6. listopadu 2021",
        "za 3 týdny, v úterý",
        "příští sobota",
        "za 2 dny",
        "za 2 hodiny",
        "za 2 minuty",
        "za 20 sekund"
    ],
    "da": [
        "søndag den 14. februar 2021 kl. 12.34.56 Koordineret universaltid",
        "14. februar 2021 kl. 12.34.56 UTC",
        "14.02.2021 12.34",
        "søndag 14. februar 2021 kl. 12:34:56 - tirsdag 6. juli 12:34:56 Koordineret universel tid",
        "nu",
        "for et øjeblik siden",
        "om få øjeblikke",
        "i dag",
        "i morgen",
        "i går",
        "mandag 6. juli 2020",
        "søndag 6. juni 2021",
        "tirsdag, sidste uge",
        "i går",
        "for 1 time siden",
        "for 1 minut siden",
        "for et øjeblik siden",
        "onsdag 6. juli 2022",
        "fredag 6. august 2021",
        "næste tirsdag",
        "i morgen",
        "om 1 time",
        "om 1 minut",
        "om få øjeblikke",
        "torsdag 6. juli 2017",
        "lørdag 6. marts 2021",
        "tirsdag 15. juni 2021",
        "fredag, sidste uge",
        "2 dage siden",
        "for 2 timer siden",
        "for 2 minutter siden",
        "for 20 sekunder siden",
        "søndag 6. juli 2025",
        "lørdag 6. november 2021",
        "om 3 uger, tirsdag",
        "næste lørdag",
        "om 2 dage",
        "om 2 timer",
        "om 2 minutter",
        "om 20 sekunder"
    ],
    "de": [
        "Sonntag, 14. Februar 2021 um 12:34:56 Koordinierte Weltzeit",
        "14. Februar 2021 um 12:34:56 UTC",
        "14.02.21, 12:34",
        "Sonntag 14. Februar 2021 161330609634 12:34:56 - Dienstag 6. Juli 34 12:34:56 koordinierte Weltzeit",
        "jetzt",
        "vor wenigen Augenblicken",
        "in ein paar Momenten",
        "heute",
        "morgen",
        "gestern",
        "Montag 6. Juli 2020",
        "Sonntag 6. Juni 2021",
        "Dienstag, letzte Woche",
        "gestern",
        "vor 1 Stunde",
        "vor 1 Minute",
        "vor wenigen Augenblicken",
        "Mittwoch 6. Juli 2022",
        "Freitag 6. August 2021",
        "nächsten Dienstag",
        "morgen",
        "in 1 Stunde",
        "in 1 Minute",
        "in ein paar Momenten",
        "Donnerstag 6. Juli 2017",
        "Samstag 6. Märkoordinierte Weltzeit 2021",
        "Dienstag 15. Juni 2021",
        "Freitag, letzte Woche",
        "vor 2 tagen",
        "vor 2 Stunden",
        "vor 2 Minuten",
        "vor 20 Sekunden",
        "Sonntag 6. Juli 2025",
        "Samstag 6. November 2021",
        "in 3 wochen, am Dienstag",
        "nächsten Samstag",
        "in 2 tagen",
        "in 2 Stunden",
        "in 2 Minuten",
        "in 20 Sekunden"
    ],
    "el": [
        "Κυριακή, 14 Φεβρουαρίου 2021 - 12:34:56 μ.μ. Συντονισμένη Παγκόσμια Ώρα",
        "14 Φεβρουαρίου 2021 - 12:34:56 μ.μ. UTC",
        "14/2/21, 12:34 μ.μ.",
        "Κυριακή 14 Φεβρουαρίου 2021 στις 12:34:56 - Τρίτη 6 Ιουλίου 12:34:56 Συντονισμένη καθολική ώρα",
        "τώρα",
        "πριν από λίγα λεπτά",
        "σε λίγες στιγμές",
        "σήμερα",
        "αύριο",
        "εχθές",
        "Δευτέρα 6 Ιουλίου 2020",
        "Κυριακή 6 Ιουνίου 2021",
        "Τρίτη, περασμένη εβδομάδα",
        "εχθές",
        "πριν από 1 ώρα",
        "πριν από 1 λεπτό",
        "πριν από λίγα λεπτά",
        "Τετάρτη 6 Ιουλίου 2022",
        "Παρασκευή 6 Αυγούστου 2021",
        "την επόμενη Τρίτη",
        "αύριο",
        "σε 1 ώρα",
        "σε 1 λεπτό",
        "σε λίγες στιγμές",
        "Πέμπτη 6 Ιουλίου 2017",
        "Σάββατο 6 Μαρτίου 2021",
        "Τρίτη 15 Ιουνίου 2021",
        "Παρασκευή, περασμένη εβδομάδα",
        "πριν από 2 ημέρες",
        "πριν από 2 ώρες",
        "πριν από 2 λεπτά",
        "πριν από 20 δευτερόλεπτα",
        "Κυριακή 6 Ιουλίου 2025",
        "Σάββατο 6 Νοεμβρίου 2021",
        "σε 3 εβδομάδες, την Τρίτη",
        "την επόμενη Σάββατο",
        "σε 2 ημέρες",
        "σε 2 ώρες",
        "σε 2 λεπτά",
        "σε 20 δευτερόλεπτα"
    ],
    "en": [
        "Sunday, February 14, 2021 at 12:34:56 PM Coordinated Universal Time",
        "February 14, 2021 at 12:34:56 PM UTC",
        "2/14/21, 12:34 PM",
        "Sunday, February 14, 2021 at 12:34:56 PM - Tuesday, July 6, 12:34:56 PM Coordinated Universal Time",
        "now",
        "a few moments ago",
        "in a few moments",
        "today",
        "tomorrow",
        "yesterday",
        "Monday, July 6, 2020",
        "Sunday, June 6, 2021",
        "Tuesday, last week",
        "yesterday",
        "1 hour ago",
        "1 minute ago",
        "a few moments ago",
        "Wednesday, July 6, 2022",
        "Friday, August 6, 2021",
        "next Tuesday",
        "tomorrow",
        "in 1 hour",
        "in 1 minute",
        "in a few moments",
        "Thursday, July 6, 2017",
        "Saturday, March 6, 2021",
        "Tuesday, June 15, 2021",
        "Friday, last week",
        "2 days ago",
        "2 hours ago",
        "2 minutes ago",
        "20 seconds ago",
        "Sunday, July 6, 2025",
        "Saturday, November 6, 2021",
        "in 3 weeks, on Tuesday",
        "next Saturday",
        "in 2 days",
        "in 2 hours",
        "in 2 minutes",
        "in 20 seconds"
    ],
    "es": [
        "domingo, 14 de febrero de 2021, 12:34:56 (tiempo universal coordinado)",
        "14 de febrero de 2021, 12:34:56 UTC",
        "14/2/21 12:34",
        "domingo, 14 de febrero de 2021, 12:34:56 - martes, 6 de julio de 12:34:56 (tiempo universal coordinado)",
        "ahora",
        "hace unos momentos",
        "en unos momentos",
        "hoy",
        "mañana",
        "ayer",
        "lunes, 6 de julio de 2020",
        "domingo, 6 de junio de 2021",
        "martes, la semana pasada",
        "ayer",
        "hace 1 hora",
        "hace 1 minuto",
        "hace unos momentos",
        "miércoles, 6 de julio de 2022",
        "viernes, 6 de agosto de 2021",
        "el próximo martes",
        "mañana",
        "dentro de 1 hora",
        "dentro de 1 minuto",
        "en unos momentos",
        "jueves, 6 de julio de 2017",
        "sábado, 6 de marzo de 2021",
        "martes, 15 de junio de 2021",
        "viernes, la semana pasada",
        "hace 2 días",
        "hace 2 horas",
        "hace 2 minutos",
        "hace 20 segundos",
        "domingo, 6 de julio de 2025",
        "sábado, 6 de noviembre de 2021",
        "en 3 semanas, el martes",
        "el próximo sábado",
        "en 2 días",
        "dentro de 2 horas",
        "dentro de 2 minutos",
        "dentro de 20 segundos"
    ],
    "et": [
        "pühapäev, 14. veebruar 2021 12:34:56 Koordineeritud maailmaaeg",
        "14. veebruar 2021 12:34:56 UTC",
        "14.02.21 12:34",
        "pühapäev, 14. veebruar 2021 kell 12:34:56 - teisipäev, 6. juuli 12:34:56 Koordineeritud ülemaailmne aeg",
        "nüüd",
        "mõni hetk tagasi",
        "mõne hetke pärast",
        "täna",
        "homme",
        "eile",
        "esmaspäev, 6. juuli 2020",
        "pühapäev, 6. juuni 2021",
        "teisipäev nädala pühapäev",
        "eile",
        "1 tunni eest",
        "1 minuti eest",
        "mõni hetk tagasi",
        "kolmapäev, 6. juuli 2022",
        "reede, 6. august 2021",
        "järgmisel teisipäev",
        "homme",
        "1 tunni pärast",
        "1 minuti pärast",
        "mõne hetke pärast",
        "neljapäev, 6. juuli 2017",
        "laupäev, 6. märts 2021",
        "teisipäev, 15. juuni 2021",
        "reede nädala pühapäev",
        "2 päeva tagasi",
        "2 tunni eest",
        "2 minuti eest",
        "20 sekundi eest",
        "pühapäev, 6. juuli 2025",
        "laupäev, 6. november 2021",
        "3 nädala pärast, teisipäev",
        "järgmisel laupäev",
        "2 päeva pärast",
        "2 tunni pärast",
        "2 minuti pärast",
        "20 sekundi pärast"
    ],
    "fa": [
        "۱۳۹۹ بهمن ۲۶, یکشنبه، ساعت ۱۲:۳۴:۵۶ (زمان هماهنگ جهانی)",
        "۲۶ بهمن ۱۳۹۹، ساعت ۱۲:۳۴:۵۶ (UTC)",
        "۱۳۹۹/۱۱/۲۶،‏ ۱۲:۳۴",
        "2021 بهمن 14 یکشنبه ساعت 12:34:56 - تیر 6 سه‌شنبه ساعت 12:34:56 زمان جهانی هماهنگ",
        "اکنون",
        "چند لحظه پیش",
        "در چند لحظه",
        "امروز",
        "فردا",
        "دیروز",
        "2020 تیر 6 دوشنبه",
        "2021 خرداد 6 یکشنبه",
        "سه‌شنبه، هفته گذشته",
        "دیروز",
        "۱ ساعت پیش",
        "۱ دقیقه پیش",
        "چند لحظه پیش",
        "2022 تیر 6 چهارشنبه",
        "2021 مرداد 6 جمعه",
        "سه‌شنبه بعدی",
        "فردا",
        "۱ ساعت بعد",
        "۱ دقیقه بعد",
        "در چند لحظه",
        "2017 تیر 6 پنجشنبه",
        "2021 اسفند 6 شنبه",
        "2021 خرداد 15 سه‌شنبه",
        "جمعه، هفته گذشته",
        "2 روز پیش",
        "۲ ساعت پیش",
        "۲ دقیقه پیش",
        "۲۰ ثانیه پیش",
        "2025 تیر 6 یکشنبه",
        "2021 آبان 6 شنبه",
        "در 3 هفته ، سه‌شنبه",
        "شنبه بعدی",
        "در 2 روز",
        "۲ ساعت بعد",
        "۲ دقیقه بعد",
        "۲۰ ثانیه بعد"
    ],
    "fi": [
        "sunnuntai 14. helmikuuta 2021 klo 12.34.56 UTC-yleisaika",
        "14. helmikuuta 2021 klo 12.34.56 UTC",
        "14.2.2021 12.34",
        "sunnuntai 14. helmikuuta 2021 klo 12:34:56 - tiistai 6. heinäkuuta 12:34:56 Koordinoidut maailmanajat",
        "nyt",
        "muutama hetki sitten",
        "hetkessä",
        "tänään",
        "huomenna",
        "eilen",
        "maanantai 6. heinäkuuta 2020",
        "sunnuntai 6. kesäkuuta 2021",
        "tiistai, viime viikko",
        "eilen",
        "1 tunti sitten",
        "1 minuutti sitten",
        "muutama hetki sitten",
        "keskiviikko 6. heinäkuuta 2022",
        "perjantai 6. elokuuta 2021",
        "ensi tiistai",
        "huomenna",
        "1 tunnin päästä",
        "1 minuutin päästä",
        "hetkessä",
        "torstai 6. heinäkuuta 2017",
        "lauantai 6. maaliskuuta 2021",
        "tiistai 15. kesäkuuta 2021",
        "perjantai, viime viikko",
        "2 päivää sitten",
        "2 tuntia sitten",
        "2 minuuttia sitten",
        "20 sekuntia sitten",
        "sunnuntai 6. heinäkuuta 2025",
        "lauantai 6. marraskuuta 2021",
        "3 viikon kuluttua tiistai",
        "ensi lauantai",
        "2 päivässä",
        "2 tunnin päästä",
        "2 minuutin päästä",
        "20 sekunnin päästä"
    ],
    "fil": [
        "Linggo, Pebrero 14, 2021 nang 12:34:56 PM Coordinated Universal Time",
        "Pebrero 14, 2021 nang 12:34:56 PM UTC",
        "2/14/21, 12:34 PM",
        "Linggo, Pebrero 14, 2021 ng 12:34:56 - Martes, Hulyo 6, 12:34:56 Coordinated Universal Time",
        "ngayon",
        "ilang sandali ang nakaraan",
        "sa ilang sandali",
        "ngayon",
        "bukas",
        "kahapon",
        "Lunes, Hulyo 6, 2020",
        "Linggo, Hunyo 6, 2021",
        "Martes, noong nakaraang linggo",
        "kahapon",
        "1 oras ang nakalipas",
        "1 minuto ang nakalipas",
        "ilang sandali ang nakaraan",
        "Miyerkules, Hulyo 6, 2022",
        "Biyernes, Agosto 6, 2021",
        "sa susunod na Martes",
        "bukas",
        "sa 1 oras",
        "sa 1 minuto",
        "sa ilang sandali",
        "Huwebes, Hulyo 6, 2017",
        "Sabado, Marso 6, 2021",
        "Martes, Hunyo 15, 2021",
        "Biyernes, noong nakaraang linggo",
        "2 araw na ang nakakalipas",
        "2 oras ang nakalipas",
        "2 minuto ang nakalipas",
        "20 segundo ang nakalipas",
        "Linggo, Hulyo 6, 2025",
        "Sabado, Nobyembre 6, 2021",
        "sa 3 linggo, sa Martes",
        "sa susunod na Sabado",
        "sa 2 araw",
        "sa 2 oras",
        "sa 2 minuto",
        "sa 20 segundo"
    ],
    "fr": [
        "dimanche 14 février 2021 à 12:34:56 Temps universel coordonné",
        "14 février 2021 à 12:34:56 UTC",
        "14/02/2021 12:34",
        "dimanche 14 février 2021 à 12:34:56 - mardi 6 juillet 12:34:56 Temps universel coordonné",
        "à présent",
        "il y a quelques instants",
        "dans quelques instants",
        "aujourd'hui",
        "demain",
        "hier",
        "lundi 6 juillet 2020",
        "dimanche 6 juin 2021",
        "mardi, la semaine dernière",
        "hier",
        "il y a 1 heure",
        "il y a 1 minute",
        "il y a quelques instants",
        "mercredi 6 juillet 2022",
        "vendredi 6 août 2021",
        "mardi prochain",
        "demain",
        "dans 1 heure",
        "dans 1 minute",
        "dans quelques instants",
        "jeudi 6 juillet 2017",
        "samedi 6 mars 2021",
        "mardi 15 juin 2021",
        "vendredi, la semaine dernière",
        "Il ya 2 jours",
        "il y a 2 heures",
        "il y a 2 minutes",
        "il y a 20 secondes",
        "dimanche 6 juillet 2025",
        "samedi 6 novembre 2021",
        "dans 3 semaines, le mardi",
        "samedi prochain",
        "dans 2 jours",
        "dans 2 heures",
        "dans 2 minutes",
        "dans 20 secondes"
    ],
    "he": [
        "יום ראשון, 14 בפברואר 2021 בשעה 12:34:56 זמן אוניברסלי מתואם",
        "14 בפברואר 2021 בשעה 12:34:56 UTC",
        "14.2.2021, 12:34",
        "2021 פברואר 14 ,יום ראשון בשעה 12:34:56 - יולי 6 ,יום שלישי בשעה 12:34:56 זמן אוניברסלי מתואם",
        "עַכשָׁיו",
        "לפני כמה רגעים",
        "בעוד כמה רגעים",
        "היום",
        "מָחָר",
        "אתמול",
        "2020 יולי 6 ,יום שני",
        "2021 יוני 6 ,יום ראשון",
        "יום יום שלישי, שבוע שעבר",
        "אתמול",
        "לפני שעה",
        "לפני דקה",
        "לפני כמה רגעים",
        "2022 יולי 6 ,יום רביעי",
        "2021 אוגוסט 6 ,יום שישי",
        "יום יום שלישי",
        "מָחָר",
        "בעוד שעה",
        "בעוד דקה",
        "בעוד כמה רגעים",
        "2017 יולי 6 ,יום חמישי",
        "2021 מרץ 6 ,יום שבת",
        "2021 יוני 15 ,יום שלישי",
        "יום יום שישי, שבוע שעבר",
        "לפני 2 ימים",
        "לפני שעתיים",
        "לפני שתי דקות",
        "לפני 20 שניות",
        "2025 יולי 6 ,יום ראשון",
        "2021 נובמבר 6 ,יום שבת",
        "בעוד 3 שבועות, ביום יום שלישי",
        "יום יום שבת",
        "בעוד 2 ימים",
        "בעוד שעתיים",
        "בעוד שתי דקות",
        "בעוד 20 שניות"
    ],
    "hi": [
        "रविवार, 14 फ़रवरी 2021 को 12:34:56 pm समन्वित वैश्विक समय",
        "14 फ़रवरी 2021 को 12:34:56 pm UTC",
        "14/2/21, 12:34 pm",
        "रविवार, 14 फ़रवरी, 2021, 12:34:56 - मंगलवार, 6 जुलाई, 12:34:56 समन्वित वैश्विक समय",
        "अब क",
        "कुछ पल पहले",
        "कुछ ही पलों में",
        "आज",
        "आने वाला कल",
        "बिता हुआ कल",
        "सोमवार, 6 जुलाई, 2020",
        "रविवार, 6 जून, 2021",
        "मंगलवार, पिछले सप्ताह",
        "बिता हुआ कल",
        "1 घंटे पहले",
        "1 मिनट पहले",
        "कुछ पल पहले",
        "बुधवार, 6 जुलाई, 2022",
        "शुक्रवार, 6 अगस्त, 2021",
        "अगले मंगलवार",
        "आने वाला कल",
        "1 घंटे में",
        "1 मिनट में",
        "कुछ ही पलों में",
        "गुरुवार, 6 जुलाई, 2017",
        "शनिवार, 6 मार्च, 2021",
        "मंगलवार, 15 जून, 2021",
        "शुक्रवार, पिछले सप्ताह",
        "2 दिन पहले",
        "2 घंटे पहले",
        "2 मिनट पहले",
        "20 सेकंड पहले",
        "रविवार, 6 जुलाई, 2025",
        "शनिवार, 6 नवंबर, 2021",
        "3 सप्ताह में, मंगलवार को",
        "अगले शनिवार",
        "2 दिनों में",
        "2 घंटे में",
        "2 मिनट में",
        "20 सेकंड में"
    ],
    "hr": [
        "nedjelja, 14. veljače 2021. u 12:34:56 (koordinirano svjetsko vrijeme)",
        "14. veljače 2021. u 12:34:56 UTC",
        "14. 02. 2021. 12:34",
        "nedjelja, 14. veljače 2021. 1613306096 12:34:56 - utorak, 6. srpnja 12:34:56 Koordinirano univerzalno vrijeme",
        "sada",
        "prije nekoliko trenutaka",
        "za nekoliko trenutaka",
        "danas",
        "sutra",
        "jučer",
        "ponedjeljak, 6. srpnja 2020.",
        "nedjelja, 6. lipnja 2021.",
        "utorak, prošli tjedan",
        "jučer",
        "prije 1 sat",
        "prije 1 minutu",
        "prije nekoliko trenutaka",
        "srijeda, 6. srpnja 2022.",
        "petak, 6. kolovoza 2021.",
        "sljedeći utorak",
        "sutra",
        "za 1 sat",
        "za 1 minutu",
        "za nekoliko trenutaka",
        "četvrtak, 6. srpnja 2017.",
        "subota, 6. ožujka 2021.",
        "utorak, 15. lipnja 2021.",
        "petak, prošli tjedan",
        "prije 2 dana",
        "prije 2 sata",
        "prije 2 minute",
        "prije 20 sekundi",
        "nedjelja, 6. srpnja 2025.",
        "subota, 6. studenoga 2021.",
        "za 3 tjedna, u utorak",
        "sljedeći subota",
        "za 2 dana",
        "za 2 sata",
        "za 2 minute",
        "za 20 sekundi"
    ],
    "hu": [
        "2021. február 14., vasárnap 12:34:56 egyezményes koordinált világidő",
        "2021. február 14. 12:34:56 UTC",
        "2021. 02. 14. 12:34",
        "2021. február 14.,vasárnap, 12:34:56 - július 6.,kedd, 12:34:56 Koordinált világidő",
        "Most",
        "néhány pillanattal ezelőtt",
        "néhány pillanat múlva",
        "Ma",
        "holnap",
        "tegnap",
        "2020. július 6.,hétfő",
        "2021. június 6.,vasárnap",
        "Múlt hét kedd",
        "tegnap",
        "1 órával ezelőtt",
        "1 perccel ezelőtt",
        "néhány pillanattal ezelőtt",
        "2022. július 6.,szerda",
        "2021. augusztus 6.,péntek",
        "jövő kedd",
        "holnap",
        "1 óra múlva",
        "1 perc múlva",
        "néhány pillanat múlva",
        "2017. július 6.,csütörtök",
        "2021. március 6.,szombat",
        "2021. június 15.,kedd",
        "Múlt hét péntek",
        "2 napja",
        "2 órával ezelőtt",
        "2 perccel ezelőtt",
        "20 másodperccel ezelőtt",
        "2025. július 6.,vasárnap",
        "2021. november 6.,szombat",
        "3 hét múlva, kedd",
        "jövő szombat",
        "2 napon belül",
        "2 óra múlva",
        "2 perc múlva",
        "20 másodperc múlva"
    ],
    "id": [
        "Minggu, 14 Februari 2021 12.34.56 Waktu Universal Terkoordinasi",
        "14 Februari 2021 12.34.56 UTC",
        "14/02/21 12.34",
        "Minggu, 14 Februari 2021 p1613306096k1613306096l 12:34:56 - Selasa, 6 Juli 12:34:56 Waktu Universal Terkoordinasi",
        "sekarang",
        "beberapa saat yang lalu",
        "dalam beberapa saat",
        "hari ini",
        "besok",
        "kemarin",
        "Senin, 6 Juli 2020",
        "Minggu, 6 Juni 2021",
        "Selasa, minggu lalu",
        "kemarin",
        "1 jam yang lalu",
        "1 menit yang lalu",
        "beberapa saat yang lalu",
        "Rabu, 6 Juli 2022",
        "Jumat, 6 Agustus 2021",
        "Selasa depan",
        "besok",
        "dalam 1 jam",
        "dalam 1 menit",
        "dalam beberapa saat",
        "Kamis, 6 Juli 2017",
        "Sabtu, 6 Maret 2021",
        "Selasa, 15 Juni 2021",
        "Jumat, minggu lalu",
        "2 hari yang lalu",
        "2 jam yang lalu",
        "2 menit yang lalu",
        "20 detik yang lalu",
        "Minggu, 6 Juli 2025",
        "Sabtu, 6 November 2021",
        "dalam 3 minggu, pada hari Selasa",
        "Sabtu depan",
        "dalam 2 hari",
        "dalam 2 jam",
        "dalam 2 menit",
        "dalam 20 detik"
    ],
    "it": [
        "domenica 14 febbraio 2021 12:34:56 Tempo coordinato universale",
        "14 febbraio 2021 12:34:56 UTC",
        "14/02/21, 12:34",
        "domenica 14 febbraio 2021 a 12:34:56 - martedì 6 luglio 12:34:56 Tempo Universale Coordinato",
        "adesso",
        "pochi istanti fa",
        "in pochi istanti",
        "oggi",
        "Domani",
        "ieri",
        "lunedì 6 luglio 2020",
        "domenica 6 giugno 2021",
        "martedì, la scorsa settimana",
        "ieri",
        "1 ora fa",
        "1 minuto fa",
        "pochi istanti fa",
        "mercoledì 6 luglio 2022",
        "venerdì 6 agosto 2021",
        "martedì prossimo",
        "Domani",
        "tra 1 ora",
        "tra 1 minuto",
        "in pochi istanti",
        "giovedì 6 luglio 2017",
        "sabato 6 marzo 2021",
        "martedì 15 giugno 2021",
        "venerdì, la scorsa settimana",
        "2 giorni fa",
        "2 ore fa",
        "2 minuti fa",
        "20 secondi fa",
        "domenica 6 luglio 2025",
        "sabato 6 novembre 2021",
        "tra 3 settimane, martedì",
        "sabato prossimo",
        "tra 2 giorni",
        "tra 2 ore",
        "tra 2 minuti",
        "tra 20 secondi"
    ],
    "ja": [
        "2021年2月14日日曜日 12時34分56秒 協定世界時",
        "2021年2月14日 12:34:56 UTC",
        "2021/02/14 12:34",
        "日曜日 14 2 2021 12:34:56 - 火曜日 6 7 12:34:56 協定世界時",
        "今",
        "少し前",
        "すぐに",
        "今日",
        "明日",
        "昨日",
        "月曜日 6 7 2020",
        "日曜日 6 6 2021",
        "先週の 火曜日",
        "昨日",
        "1 時間前",
        "1 分前",
        "少し前",
        "水曜日 6 7 2022",
        "金曜日 6 8 2021",
        "次の 火曜日",
        "明日",
        "1 時間後",
        "1 分後",
        "すぐに",
        "木曜日 6 7 2017",
        "土曜日 6 3 2021",
        "火曜日 15 6 2021",
        "先週の 金曜日",
        "2日前",
        "2 時間前",
        "2 分前",
        "20 秒前",
        "日曜日 6 7 2025",
        "土曜日 6 11 2021",
        "3 週間後、火曜日",
        "次の 土曜日",
        "2日で",
        "2 時間後",
        "2 分後",
        "20 秒後"
    ],
    "kn": [
        "ಭಾನುವಾರ, ಫೆಬ್ರವರಿ 14, 2021 12:34:56 ಅಪರಾಹ್ನ ಸಂಘಟಿತ ಸಾರ್ವತ್ರಿಕ ಸಮಯ",
        "ಫೆಬ್ರವರಿ 14, 2021 12:34:56 ಅಪರಾಹ್ನ UTC",
        "14/2/21 12:34 ಅಪರಾಹ್ನ",
        "ಫೆಬ್ರವರಿ 14, 2021 ಭಾನುವಾರ, 12:34:56 - ಜುಲೈ 6, 12:34:56 ಸಂಯೋಜಿತ ಸಾರ್ವತ್ರಿಕ ಸಮಯ",
        "ಈಗ",
        "ಕೆಲವು ಕ್ಷಣಗಳ ಹಿಂದೆ",
        "ಕೆಲವು ಕ್ಷಣಗಳಲ್ಲಿ",
        "ಇಂದು",
        "ನಾಳೆ",
        "ನಿನ್ನೆ",
        "ಜುಲೈ 6, 2020 ಸೋಮವಾರ",
        "ಜೂನ್ 6, 2021 ಭಾನುವಾರ",
        "ಕಳೆದ ವಾರ ಮಂಗಳವಾರ",
        "ನಿನ್ನೆ",
        "1 ಗಂಟೆ ಹಿಂದೆ",
        "1 ನಿಮಿಷದ ಹಿಂದೆ",
        "ಕೆಲವು ಕ್ಷಣಗಳ ಹಿಂದೆ",
        "ಜುಲೈ 6, 2022 ಬುಧವಾರ",
        "ಆಗಸ್ಟ್ 6, 2021 ಶುಕ್ರವಾರ",
        "ಮುಂದಿನ ಮಂಗಳವಾರ",
        "ನಾಳೆ",
        "1 ಗಂಟೆಯಲ್ಲಿ",
        "1 ನಿಮಿಷದಲ್ಲಿ",
        "ಕೆಲವು ಕ್ಷಣಗಳಲ್ಲಿ",
        "ಜುಲೈ 6, 2017 ಗುರುವಾರ",
        "ಮಾರ್ಚ್ 6, 2021 ಶನಿವಾರ",
        "ಜೂನ್ 15, 2021 ಮಂಗಳವಾರ",
        "ಕಳೆದ ವಾರ ಶುಕ್ರವಾರ",
        "2 ದಿನಗಳ ಹಿಂದೆ",
        "2 ಗಂಟೆಗಳ ಹಿಂದೆ",
        "2 ನಿಮಿಷಗಳ ಹಿಂದೆ",
        "20 ಸೆಕೆಂಡುಗಳ ಹಿಂದೆ",
        "ಜುಲೈ 6, 2025 ಭಾನುವಾರ",
        "ನವೆಂಬರ್ 6, 2021 ಶನಿವಾರ",
        "3 ವಾರಗಳಲ್ಲಿ, ಮಂಗಳವಾರ",
        "ಮುಂದಿನ ಶನಿವಾರ",
        "2 ದಿನಗಳಲ್ಲಿ",
        "2 ಗಂಟೆಗಳಲ್ಲಿ",
        "2 ನಿಮಿಷಗಳಲ್ಲಿ",
        "20 ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ"
    ],
    "lt": [
        "2021 m. vasario 14 d., sekmadienis 12:34:56 pasaulio suderintasis laikas",
        "2021 m. vasario 14 d. 12:34:56 UTC",
        "2021-02-14 12:34",
        "2021 n.vasario 14 d., sekmadienis, 12:34:56 - liepos 6 d., antradienis, 12:34:56 Koordinuotas pasaulinis laikas",
        "dabar",
        "prieš kelias akimirkas",
        "per kelias akimirkas",
        "šiandien",
        "rytoj",
        "vakar",
        "2020 n.liepos 6 d., pirmadienis",
        "2021 n.birželio 6 d., sekmadienis",
        "Praėjusios savaitės antradienis",
        "vakar",
        "prieš 1 valandą",
        "prieš 1 minutę",
        "prieš kelias akimirkas",
        "2022 n.liepos 6 d., trečiadienis",
        "2021 n.rugpjūčio 6 d., penktadienis",
        "kitą antradienis",
        "rytoj",
        "po 1 valandos",
        "po 1 minutės",
        "per kelias akimirkas",
        "2017 n.liepos 6 d., ketvirtadienis",
        "2021 n.kovo 6 d., šeštadienis",
        "2021 n.birželio 15 d., antradienis",
        "Praėjusios savaitės penktadienis",
        "prieš 2 dienas",
        "prieš 2 valandas",
        "prieš 2 minutes",
        "prieš 20 sekundžių",
        "2025 n.liepos 6 d., sekmadienis",
        "2021 n.lapkričio 6 d., šeštadienis",
        "po 3 savaičių, antradienis",
        "kitą šeštadienis",
        "per 2 dienas",
        "po 2 valandų",
        "po 2 minučių",
        "po 20 sekundžių"
    ],
    "lv": [
        "svētdiena, 2021. gada 14. februāris 12:34:56 Universālais koordinētais laiks",
        "2021. gada 14. februāris 12:34:56 UTC",
        "14.02.21 12:34",
        "svētdiena, 2021 gada 14. februāris plk56t 12:34:56 - otrdiena, 6. jūlijs plk56t 12:34:56 Saskaņotais pasaules laiks",
        "tagad",
        "pirms dažiem mirkļiem",
        "pēc dažiem mirkļiem",
        "šodien",
        "rīt",
        "vakar",
        "pirmdiena, 2020 gada 6. jūlijs",
        "svētdiena, 2021 gada 6. jūnijs",
        "otrdiena, pagājušā nedēļa",
        "vakar",
        "pirms 1 stundas",
        "pirms 1 minūtes",
        "pirms dažiem mirkļiem",
        "trešdiena, 2022 gada 6. jūlijs",
        "piektdiena, 2021 gada 6. augusts",
        "nākamajā otrdiena",
        "rīt",
        "pēc 1 stundas",
        "pēc 1 minūtes",
        "pēc dažiem mirkļiem",
        "ceturtdiena, 2017 gada 6. jūlijs",
        "sestdiena, 2021 gada 6. marts",
        "otrdiena, 2021 gada 15. jūnijs",
        "piektdiena, pagājušā nedēļa",
        "pirms 2 dienām",
        "pirms 2 stundām",
        "pirms 2 minūtēm",
        "pirms 20 sekundēm",
        "svētdiena, 2025 gada 6. jūlijs",
        "sestdiena, 2021 gada 6. novembris",
        "nedēļu no otrdiena",
        "nākamajā sestdiena",
        "2 dienām",
        "pēc 2 stundām",
        "pēc 2 minūtēm",
        "pēc 20 sekundēm"
    ],
    "ml": [
        "2021, ഫെബ്രുവരി 14, ഞായറാഴ്‌ച 12:34:56 PM കോർഡിനേറ്റഡ് യൂണിവേഴ്‌സൽ ടൈം",
        "2021, ഫെബ്രുവരി 14 12:34:56 PM UTC",
        "14/2/21 12:34 PM",
        "2021 ഫെബ്രുവരി 14 ഞായറാഴ്‌ച, 12:34:56 - ജൂലൈ 6 ചൊവ്വാഴ്ച, 12:34:56 ഏകോപിപ്പിച്ച യൂണിവേഴ്സൽ സമയം",
        "ഇപ്പോൾ",
        "കുറച്ച് നിമിഷങ്ങൾക്ക് മുമ്പ്",
        "കുറച്ച് നിമിഷങ്ങൾക്കുള്ളിൽ",
        "ഇന്ന്",
        "നാളെ",
        "ഇന്നലെ",
        "2020 ജൂലൈ 6 തിങ്കളാഴ്‌ച",
        "2021 ജൂൺ 6 ഞായറാഴ്‌ച",
        "കഴിഞ്ഞ ആഴ്ച ചൊവ്വാഴ്ച",
        "ഇന്നലെ",
        "1 മണിക്കൂർ മുമ്പ്",
        "1 മിനിറ്റ് മുമ്പ്",
        "കുറച്ച് നിമിഷങ്ങൾക്ക് മുമ്പ്",
        "2022 ജൂലൈ 6 ബുധനാഴ്‌ച",
        "2021 ഓഗസ്റ്റ് 6 വെള്ളിയാഴ്‌ച",
        "ചൊവ്വാഴ്ച അടുത്തത്",
        "നാളെ",
        "1 മണിക്കൂറിൽ",
        "1 മിനിറ്റിൽ",
        "കുറച്ച് നിമിഷങ്ങൾക്കുള്ളിൽ",
        "2017 ജൂലൈ 6 വ്യാഴാഴ്‌ച",
        "2021 മാർച്ച് 6 ശനിയാഴ്‌ച",
        "2021 ജൂൺ 15 ചൊവ്വാഴ്ച",
        "കഴിഞ്ഞ ആഴ്ച വെള്ളിയാഴ്‌ച",
        "2 ദിവസങ്ങളിൽ മുമ്പ്",
        "2 മണിക്കൂർ മുമ്പ്",
        "2 മിനിറ്റ് മുമ്പ്",
        "20 സെക്കൻഡ് മുമ്പ്",
        "2025 ജൂലൈ 6 ഞായറാഴ്‌ച",
        "2021 നവംബർ 6 ശനിയാഴ്‌ച",
        "ചൊവ്വാഴ്ച മുതൽ ഒരാഴ്ച",
        "ശനിയാഴ്‌ച അടുത്തത്",
        "2 ദിവസം മുൻപ്",
        "2 മണിക്കൂറിൽ",
        "2 മിനിറ്റിൽ",
        "20 സെക്കൻഡിൽ"
    ],
    "mr": [
        "रविवार, १४ फेब्रुवारी, २०२१ रोजी १२:३४:५६ म.उ. समन्वित वैश्विक वेळ",
        "१४ फेब्रुवारी, २०२१ रोजी १२:३४:५६ म.उ. UTC",
        "१४/२/२१, १२:३४ म.उ.",
        "रविवार, 14 फेब्रुवारी 2021, 12:34:56 - मंगळवार, 6 जुलै 12:34:56 समन्वयित युनिव्हर्सल टाइम",
        "आता",
        "काही क्षणांपूर्वी",
        "काही क्षणात",
        "आज",
        "उद्या",
        "काल",
        "सोमवार, 6 जुलै 2020",
        "रविवार, 6 जून 2021",
        "मंगळवार, गेल्या आठवड्यात",
        "काल",
        "१ तासापूर्वी",
        "१ मिनिटापूर्वी",
        "काही क्षणांपूर्वी",
        "बुधवार, 6 जुलै 2022",
        "शुक्रवार, 6 ऑगस्ट 2021",
        "पुढच्या मंगळवार",
        "उद्या",
        "१ तासामध्ये",
        "१ मिनिटामध्ये",
        "काही क्षणात",
        "गुरुवार, 6 जुलै 2017",
        "शनिवार, 6 मार्च 2021",
        "मंगळवार, 15 जून 2021",
        "शुक्रवार, गेल्या आठवड्यात",
        "2 दिवसांपूर्वी",
        "२ तासांपूर्वी",
        "२ मिनिटांपूर्वी",
        "२० सेकंदांपूर्वी",
        "रविवार, 6 जुलै 2025",
        "शनिवार, 6 नोव्हेंबर 2021",
        "मंगळवार पासून एक आठवडा",
        "पुढच्या शनिवार",
        "2 दिवसात",
        "२ तासांमध्ये",
        "२ मिनिटांमध्ये",
        "२० सेकंदांमध्ये"
    ],
    "ms": [
        "Ahad, 14 Februari 2021 12:34:56 PTG Waktu Universal Selaras",
        "14 Februari 2021 12:34:56 PTG UTC",
        "14/02/21, 12:34 PTG",
        "Ahad, 14 Februari 2021 1613306096000a34 12:34:56 - Selasa, 6 Julai 34 12:34:56 Waktu Semesta Berkoordinat",
        "sekarang",
        "beberapa saat yang lalu",
        "dalam beberapa saat",
        "hari ini",
        "esok",
        "semalam",
        "Isnin, 6 Julai 2020",
        "Ahad, 6 Jun 2021",
        "Selasa, minggu lalu",
        "semalam",
        "1 jam lalu",
        "1 minit lalu",
        "beberapa saat yang lalu",
        "Rabu, 6 Julai 2022",
        "Jumaat, 6 Ogos 2021",
        "Selasa depan",
        "esok",
        "dalam 1 jam",
        "dalam 1 minit",
        "dalam beberapa saat",
        "Khamis, 6 Julai 2017",
        "Sabtu, 6 Mac 2021",
        "Selasa, 15 Jun 2021",
        "Jumaat, minggu lalu",
        "2 hari lepas",
        "2 jam lalu",
        "2 minit lalu",
        "20 saat lalu",
        "Ahad, 6 Julai 2025",
        "Sabtu, 6 November 2021",
        "in 3 weeks, on Selasa",
        "Sabtu depan",
        "dalam 2 hari",
        "dalam 2 jam",
        "dalam 2 minit",
        "dalam 20 saat"
    ],
    "nb": [
        "søndag 14. februar 2021 12:34:56 koordinert universaltid",
        "14. februar 2021 kl. 12:34:56 UTC",
        "14.02.2021, 12:34",
        "søndag 14. februar 2021 kl 12:34:56 - tirsdag 6. juli 12:34:56 Koordinert universell tid",
        "nå",
        "for noen øyeblikk siden",
        "om noen få øyeblikk",
        "i dag",
        "i morgen",
        "i går",
        "mandag 6. juli 2020",
        "søndag 6. juni 2021",
        "tirsdag, forrige uke",
        "i går",
        "for 1 time siden",
        "for 1 minutt siden",
        "for noen øyeblikk siden",
        "onsdag 6. juli 2022",
        "fredag 6. august 2021",
        "neste tirsdag",
        "i morgen",
        "om 1 time",
        "om 1 minutt",
        "om noen få øyeblikk",
        "torsdag 6. juli 2017",
        "lørdag 6. mars 2021",
        "tirsdag 15. juni 2021",
        "fredag, forrige uke",
        "2 dager siden",
        "for 2 timer siden",
        "for 2 minutter siden",
        "for 20 sekunder siden",
        "søndag 6. juli 2025",
        "lørdag 6. november 2021",
        "om 3 uker, på tirsdag",
        "neste lørdag",
        "om 2 dager",
        "om 2 timer",
        "om 2 minutter",
        "om 20 sekunder"
    ],
    "nl": [
        "zondag 14 februari 2021 om 12:34:56 Gecoördineerde wereldtijd",
        "14 februari 2021 om 12:34:56 UTC",
        "14-02-2021 12:34",
        "zondag 14 februari 2021 o34 12:34:56 - dinsdag 6 juli 34 12:34:56 Gecoördineerde Universele Tijd",
        "nu",
        "enkele ogenblikken geleden",
        "binnen enkele ogenblikken",
        "vandaag",
        "morgen",
        "gisteren",
        "maandag 6 juli 2020",
        "zondag 6 juni 2021",
        "vorige week dinsdag",
        "gisteren",
        "1 uur geleden",
        "1 minuut geleden",
        "enkele ogenblikken geleden",
        "woensdag 6 juli 2022",
        "vrijdag 6 augustus 2021",
        "volgende dinsdag",
        "morgen",
        "over 1 uur",
        "over 1 minuut",
        "binnen enkele ogenblikken",
        "donderdag 6 juli 2017",
        "zaterdag 6 maart 2021",
        "dinsdag 15 juni 2021",
        "vorige week vrijdag",
        "2 dagen geleden",
        "2 uur geleden",
        "2 minuten geleden",
        "20 seconden geleden",
        "zondag 6 juli 2025",
        "zaterdag 6 november 2021",
        "over 3 weken, op dinsdag",
        "volgende zaterdag",
        "binnen 2 dagen",
        "over 2 uur",
        "over 2 minuten",
        "over 20 seconden"
    ],
    "pa": [
        "ਐਤਵਾਰ, 14 ਫ਼ਰਵਰੀ 2021 12:34:56 ਬਾ.ਦੁ. ਕੋਔਰਡੀਨੇਟੇਡ ਵਿਆਪਕ ਵੇਲਾ",
        "14 ਫ਼ਰਵਰੀ 2021 12:34:56 ਬਾ.ਦੁ. UTC",
        "14/2/21, 12:34 ਬਾ.ਦੁ.",
        "ਐਤਵਾਰ, 14 ਫ਼ਰਵਰੀ, 2021, 12:34:56 - ਮੰਗਲਵਾਰ, 6 ਜੁਲਾਈ, 12:34:56 ਕੋਆਰਡੀਨੇਟਡ ਯੂਨੀਵਰਸਲ ਟਾਈਮ",
        "ਹੁਣ",
        "ਕੁਝ ਪਲ ਪਹਿਲਾਂ",
        "ਕੁਝ ਪਲਾਂ ਵਿਚ",
        "ਅੱਜ",
        "ਕੱਲ",
        "ਕੱਲ",
        "ਸੋਮਵਾਰ, 6 ਜੁਲਾਈ, 2020",
        "ਐਤਵਾਰ, 6 ਜੂਨ, 2021",
        "ਮੰਗਲਵਾਰ, ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "ਕੱਲ",
        "1 ਘੰਟਾ ਪਹਿਲਾਂ",
        "1 ਮਿੰਟ ਪਹਿਲਾਂ",
        "ਕੁਝ ਪਲ ਪਹਿਲਾਂ",
        "ਬੁੱਧਵਾਰ, 6 ਜੁਲਾਈ, 2022",
        "ਸ਼ੁੱਕਰਵਾਰ, 6 ਅਗਸਤ, 2021",
        "ਅਗਲਾ ਮੰਗਲਵਾਰ",
        "ਕੱਲ",
        "1 ਘੰਟੇ ਵਿੱਚ",
        "1 ਮਿੰਟ ਵਿੱਚ",
        "ਕੁਝ ਪਲਾਂ ਵਿਚ",
        "ਵੀਰਵਾਰ, 6 ਜੁਲਾਈ, 2017",
        "ਸ਼ਨਿੱਚਰਵਾਰ, 6 ਮਾਰਚ, 2021",
        "ਮੰਗਲਵਾਰ, 15 ਜੂਨ, 2021",
        "ਸ਼ੁੱਕਰਵਾਰ, ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "2 ਦਿਨ ਪਹਿਲਾਂ",
        "2 ਘੰਟੇ ਪਹਿਲਾਂ",
        "2 ਮਿੰਟ ਪਹਿਲਾਂ",
        "20 ਸਕਿੰਟ ਪਹਿਲਾਂ",
        "ਐਤਵਾਰ, 6 ਜੁਲਾਈ, 2025",
        "ਸ਼ਨਿੱਚਰਵਾਰ, 6 ਨਵੰਬਰ, 2021",
        "3 ਹਫਤਿਆਂ ਵਿਚ, ਮੰਗਲਵਾਰ",
        "ਅਗਲਾ ਸ਼ਨਿੱਚਰਵਾਰ",
        "2 ਦਿਨਾਂ ਵਿਚ",
        "2 ਘੰਟਿਆਂ ਵਿੱਚ",
        "2 ਮਿੰਟਾਂ ਵਿੱਚ",
        "20 ਸਕਿੰਟਾਂ ਵਿੱਚ"
    ],
    "pl": [
        "niedziela, 14 lutego 2021 12:34:56 uniwersalny czas koordynowany",
        "14 lutego 2021 12:34:56 UTC",
        "14.02.2021, 12:34",
        "niedziela, 14 lutego 2021 o 12:34:56 - wtorek, 6 lipca 12:34:56 Skoordynowany czas uniwersalny",
        "teraz",
        "kilka chwil temu",
        "za kilka chwil",
        "dzisiaj",
        "jutro",
        "wczoraj",
        "poniedziałek, 6 lipca 2020",
        "niedziela, 6 czerwca 2021",
        "wtorek, ostatni tydzień",
        "wczoraj",
        "1 godzinę temu",
        "1 minutę temu",
        "kilka chwil temu",
        "środa, 6 lipca 2022",
        "piątek, 6 sierpnia 2021",
        "w następną wtorek",
        "jutro",
        "za 1 godzinę",
        "za 1 minutę",
        "za kilka chwil",
        "czwartek, 6 lipca 2017",
        "sobota, 6 marca 2021",
        "wtorek, 15 czerwca 2021",
        "piątek, ostatni tydzień",
        "2 dni temu",
        "2 godziny temu",
        "2 minuty temu",
        "20 sekund temu",
        "niedziela, 6 lipca 2025",
        "sobota, 6 listopada 2021",
        "za 3 tygodnie, w wtorek",
        "w następną sobota",
        "za 2 dni",
        "za 2 godziny",
        "za 2 minuty",
        "za 20 sekund"
    ],
    "pt": [
        "domingo, 14 de fevereiro de 2021 12:34:56 Horário Universal Coordenado",
        "14 de fevereiro de 2021 12:34:56 UTC",
        "14/02/2021 12:34",
        "domingo, 14 de fevereiro de 2021 à56 12:34:56 - terça-feira, 6 de julho de 56 12:34:56 Tempo Universal Coordenado",
        "agora",
        "alguns momentos atrás",
        "em alguns instantes",
        "hoje",
        "amanhã",
        "ontem",
        "segunda-feira, 6 de julho de 2020",
        "domingo, 6 de junho de 2021",
        "terça-feira, semana passada",
        "ontem",
        "há 1 hora",
        "há 1 minuto",
        "alguns momentos atrás",
        "quarta-feira, 6 de julho de 2022",
        "sexta-feira, 6 de agosto de 2021",
        "próxima terça-feira",
        "amanhã",
        "em 1 hora",
        "em 1 minuto",
        "em alguns instantes",
        "quinta-feira, 6 de julho de 2017",
        "sábado, 6 de março de 2021",
        "terça-feira, 15 de junho de 2021",
        "sexta-feira, semana passada",
        "2 dias atrás",
        "há 2 horas",
        "há 2 minutos",
        "há 20 segundos",
        "domingo, 6 de julho de 2025",
        "sábado, 6 de novembro de 2021",
        "em 3 semanas, na terça-feira",
        "próxima sábado",
        "em 2 dias",
        "em 2 horas",
        "em 2 minutos",
        "em 20 segundos"
    ],
    "ro": [
        "duminică, 14 februarie 2021, 12:34:56 Timpul universal coordonat",
        "14 februarie 2021, 12:34:56 UTC",
        "14.02.2021, 12:34",
        "duminică, 14 februarie 2021 la 12:34:56 - marți, 6 iulie 12:34:56 ora universală coordonată",
        "acum",
        "acum câteva clipe",
        "în câteva clipe",
        "azi",
        "Mâine",
        "ieri",
        "luni, 6 iulie 2020",
        "duminică, 6 iunie 2021",
        "marți, săptămâna trecută",
        "ieri",
        "acum 1 oră",
        "acum 1 minut",
        "acum câteva clipe",
        "miercuri, 6 iulie 2022",
        "vineri, 6 august 2021",
        "marți viitoare",
        "Mâine",
        "peste 1 oră",
        "peste 1 minut",
        "în câteva clipe",
        "joi, 6 iulie 2017",
        "sâmbătă, 6 martie 2021",
        "marți, 15 iunie 2021",
        "vineri, săptămâna trecută",
        "acum 2 zile",
        "acum 2 ore",
        "acum 2 minute",
        "acum 20 de secunde",
        "duminică, 6 iulie 2025",
        "sâmbătă, 6 noiembrie 2021",
        "în 3 săptămâni, marți",
        "sâmbătă viitoare",
        "în 2 zile",
        "peste 2 ore",
        "peste 2 minute",
        "peste 20 de secunde"
    ],
    "ru": [
        "воскресенье, 14 февраля 2021 г., 12:34:56 Всемирное координированное время",
        "14 февраля 2021 г., 12:34:56 UTC",
        "14.02.2021, 12:34",
        "воскресенье, 14 февраля 2021 r., в 12:34:56 - вторник, 6 июля 12:34:56 Всемирное координированное время",
        "сейчас",
        "несколько минут назад",
        "через несколько минут",
        "Cегодня",
        "завтра",
        "вчера",
        "понедельник, 6 июля 2020 r.",
        "воскресенье, 6 июня 2021 r.",
        "вторник, lна прошлой неделе",
        "вчера",
        "1 час назад",
        "1 минуту назад",
        "несколько минут назад",
        "среда, 6 июля 2022 r.",
        "пятница, 6 августа 2021 r.",
        "в следующую вторник",
        "завтра",
        "через 1 час",
        "через 1 минуту",
        "через несколько минут",
        "четверг, 6 июля 2017 r.",
        "суббота, 6 марта 2021 r.",
        "вторник, 15 июня 2021 r.",
        "пятница, lна прошлой неделе",
        "2 дня назад",
        "2 часа назад",
        "2 минуты назад",
        "20 секунд назад",
        "воскресенье, 6 июля 2025 r.",
        "суббота, 6 ноября 2021 r.",
        "через 3 недели, в вторник",
        "в следующую суббота",
        "через 2 дня",
        "через 2 часа",
        "через 2 минуты",
        "через 20 секунд"
    ],
    "sk": [
        "nedeľa 14. februára 2021, 12:34:56 koordinovaný svetový čas",
        "14. februára 2021, 12:34:56 UTC",
        "14. 2. 2021 12:34",
        "nedeľa 14. februára 2021 o 12:34:56 - utorok 6. júla 12:34:56 Koordinovaný svetový čas",
        "teraz",
        "pred pár okamihmi",
        "za pár okamihov",
        "dnes",
        "zajtra",
        "včera",
        "pondelok 6. júla 2020",
        "nedeľa 6. júna 2021",
        "utorok, minulý týždeň",
        "včera",
        "pred 1 hodinou",
        "pred 1 minútou",
        "pred pár okamihmi",
        "streda 6. júla 2022",
        "piatok 6. augusta 2021",
        "budúci utorok",
        "zajtra",
        "o 1 hodinu",
        "o 1 minútu",
        "za pár okamihov",
        "štvrtok 6. júla 2017",
        "sobota 6. marca 2021",
        "utorok 15. júna 2021",
        "piatok, minulý týždeň",
        "pred 2 dňami",
        "pred 2 hodinami",
        "pred 2 minútami",
        "pred 20 sekundami",
        "nedeľa 6. júla 2025",
        "sobota 6. novembra 2021",
        "o 3 týždne, v utorok",
        "budúci sobota",
        "za 2 dni",
        "o 2 hodiny",
        "o 2 minúty",
        "o 20 sekúnd"
    ],
    "sl": [
        "nedelja, 14. februar 2021 12:34:56 univerzalni koordinirani čas",
        "14. februar 2021 12:34:56 UTC",
        "14. 02. 21 12:34",
        "nedelja, 14. februar 2021 ob 12:34:56 - torek, 6. julij 12:34:56 Univerzalni koordinirani čas",
        "zdaj",
        "pred nekaj trenutki",
        "v nekaj trenutkih",
        "danes",
        "jutri",
        "včeraj",
        "ponedeljek, 6. julij 2020",
        "nedelja, 6. junij 2021",
        "torek, prejšnji teden",
        "včeraj",
        "pred 1 uro",
        "pred 1 minuto",
        "pred nekaj trenutki",
        "sreda, 6. julij 2022",
        "petek, 6. avgust 2021",
        "naslednji torek",
        "jutri",
        "čez 1 uro",
        "čez 1 minuto",
        "v nekaj trenutkih",
        "četrtek, 6. julij 2017",
        "sobota, 6. marec 2021",
        "torek, 15. junij 2021",
        "petek, prejšnji teden",
        "pred 2 dnevi",
        "pred 2 urama",
        "pred 2 minutama",
        "pred 20 sekundami",
        "nedelja, 6. julij 2025",
        "sobota, 6. november 2021",
        "čez 3 tedne, v torek",
        "naslednji sobota",
        "v 2 dneh",
        "čez 2 uri",
        "čez 2 minuti",
        "čez 20 sekund"
    ],
    "sr": [
        "недеља, 14. фебруар 2021. 12:34:56 Координисано универзално време",
        "14. фебруар 2021. 12:34:56 UTC",
        "14.2.21. 12:34",
        "недеља, 14. фебруар 2021. у 12:34:56 - уторак, 6. јул 12:34:56 Универзално координисано време",
        "Сада",
        "пре неколико тренутака",
        "за неколико тренутака",
        "данас",
        "сутра",
        "јуче",
        "понедељак, 6. јул 2020.",
        "недеља, 6. јун 2021.",
        "уторак, прошле недеље",
        "јуче",
        "пре 1 сата",
        "пре 1 минута",
        "пре неколико тренутака",
        "среда, 6. јул 2022.",
        "петак, 6. август 2021.",
        "следећи уторак",
        "сутра",
        "за 1 сат",
        "за 1 минут",
        "за неколико тренутака",
        "четвртак, 6. јул 2017.",
        "субота, 6. март 2021.",
        "уторак, 15. јун 2021.",
        "петак, прошле недеље",
        "пре 2 дана",
        "пре 2 сата",
        "пре 2 минута",
        "пре 20 секунди",
        "недеља, 6. јул 2025.",
        "субота, 6. новембар 2021.",
        "за 3 недеље, у уторак",
        "следећи субота",
        "за 2 дана",
        "за 2 сата",
        "за 2 минута",
        "за 20 секунди"
    ],
    "sv": [
        "söndag 14 februari 2021 kl. 12:34:56 Koordinerad universell tid",
        "14 februari 2021 12:34:56 UTC",
        "2021-02-14 12:34",
        "söndag 14 februari 2021 kl 12:34:56 - tisdag 6 juli 12:34:56 Koordinerad universell tid",
        "nu",
        "för några ögonblick sedan",
        "på några ögonblick",
        "i dag",
        "i morgon",
        "i går",
        "måndag 6 juli 2020",
        "söndag 6 juni 2021",
        "tisdag, förra veckan",
        "i går",
        "för 1 timme sedan",
        "för 1 minut sedan",
        "för några ögonblick sedan",
        "onsdag 6 juli 2022",
        "fredag 6 augusti 2021",
        "nästa tisdag",
        "i morgon",
        "om 1 timme",
        "om 1 minut",
        "på några ögonblick",
        "torsdag 6 juli 2017",
        "lördag 6 mars 2021",
        "tisdag 15 juni 2021",
        "fredag, förra veckan",
        "2 dagar sedan",
        "för 2 timmar sedan",
        "för 2 minuter sedan",
        "för 20 sekunder sedan",
        "söndag 6 juli 2025",
        "lördag 6 november 2021",
        "om 3 veckor, på tisdag",
        "nästa lördag",
        "om 2 dager",
        "om 2 timmar",
        "om 2 minuter",
        "om 20 sekunder"
    ],
    "sw": [
        "Jumapili, 14 Februari 2021 12:34:56 Mfumo wa kuratibu saa ulimwenguni",
        "14 Februari 2021 12:34:56 UTC",
        "14/02/2021 12:34",
        "Jumapili, Februari 14, 2021 56aa 12:34:56 - Jumanne, Julai 6, 56aa 12:34:56 Wakati wa Ulimwengu ulioratibiwa",
        "sasa",
        "dakika chache zilizopita",
        "katika muda mfupi",
        "leo",
        "kesho",
        "jana",
        "Jumatatu, Julai 6, 2020",
        "Jumapili, Juni 6, 2021",
        "Jumanne, wiki iliyopita",
        "jana",
        "saa 1 iliyopita",
        "dakika 1 iliyopita",
        "dakika chache zilizopita",
        "Jumatano, Julai 6, 2022",
        "Ijumaa, Agosti 6, 2021",
        "Jumanne ijayo",
        "kesho",
        "baada ya saa 1",
        "baada ya dakika 1",
        "katika muda mfupi",
        "Alhamisi, Julai 6, 2017",
        "Jumamosi, Machi 6, 2021",
        "Jumanne, Juni 15, 2021",
        "Ijumaa, wiki iliyopita",
        "siku 2 zilizopita",
        "saa 2 zilizopita",
        "dakika 2 zilizopita",
        "Sekunde 20 zilizopita",
        "Jumapili, Julai 6, 2025",
        "Jumamosi, Novemba 6, 2021",
        "katika wiki 3, Jumanne",
        "Jumamosi ijayo",
        "kwa siku 2",
        "baada ya saa 2",
        "baada ya dakika 2",
        "baada ya sekunde 20"
    ],
    "ta": [
        "ஞாயிறு, 14 பிப்ரவரி, 2021 ’அன்று’ பிற்பகல் 12:34:56 ஒருங்கிணைந்த சர்வதேச நேரம்",
        "14 பிப்ரவரி, 2021 ’அன்று’ பிற்பகல் 12:34:56 UTC",
        "14/2/21, பிற்பகல் 12:34",
        "பிப்ரவரி 14, 2021 ஞாயிறு, 12:34:56 - ஜூலை 6, 12:34:56 ஒருங்கிணைந்த யுனிவர்சல் நேரம்",
        "இப்போது",
        "சில தருணங்களுக்கு முன்பு",
        "சில தருணங்களில்",
        "இன்று",
        "நாளை",
        "நேற்று",
        "ஜூலை 6, 2020 திங்கள்",
        "ஜூன் 6, 2021 ஞாயிறு",
        "கடந்த வாரம் செவ்வாய்",
        "நேற்று",
        "1 மணிநேரம் முன்",
        "1 நிமிடத்திற்கு முன்",
        "சில தருணங்களுக்கு முன்பு",
        "ஜூலை 6, 2022 புதன்",
        "ஆகஸ்ட் 6, 2021 வெள்ளி",
        "அடுத்த செவ்வாய்",
        "நாளை",
        "1 மணிநேரத்தில்",
        "1 நிமிடத்தில்",
        "சில தருணங்களில்",
        "ஜூலை 6, 2017 வியாழன்",
        "மார்ச் 6, 2021 சனி",
        "ஜூன் 15, 2021 செவ்வாய்",
        "கடந்த வாரம் வெள்ளி",
        "2 நாட்களுக்கு முன்பு",
        "2 மணிநேரம் முன்",
        "2 நிமிடங்களுக்கு முன்",
        "20 விநாடிகளுக்கு முன்",
        "ஜூலை 6, 2025 ஞாயிறு",
        "நவம்பர் 6, 2021 சனி",
        "3 வாரங்களில், செவ்வாய்",
        "அடுத்த சனி",
        "2 நாட்களில்",
        "2 மணிநேரத்தில்",
        "2 நிமிடங்களில்",
        "20 விநாடிகளில்"
    ],
    "te": [
        "14, ఫిబ్రవరి 2021, ఆదివారం 12:34:56 PM సమన్వయ సార్వజనీన సమయంకి",
        "14 ఫిబ్రవరి, 2021 12:34:56 PM UTCకి",
        "14-02-21 12:34 PM",
        "ఫిబ్రవరి 14, 2021, ఆదివారం, 12:34:56 - జులై 6, 12:34:56 సమన్వయ యూనివర్సల్ సమయం",
        "ఇప్పుడు",
        "సెక.",
        "కొన్ని క్షణాల క్రితం",
        "క్రితం",
        "ఈ రోజు",
        "రేపు",
        "జులై 6, 2020, సోమవారం",
        "జూన్ 6, 2021, ఆదివారం",
        "వచ్చే మంగళవారం",
        "రేపు",
        "1 గంట క్రితం",
        "1 నిమిషం క్రితం",
        "సెక.",
        "జులై 6, 2022, బుధవారం",
        "ఆగస్టు 6, 2021, శుక్రవారం",
        "నిన్న",
        "ఈ రోజు",
        "1 గంటలో",
        "1 నిమిషంలో",
        "కొన్ని క్షణాల క్రితం",
        "జులై 6, 2017, గురువారం",
        "మార్చి 6, 2021, శనివారం",
        "జూన్ 15, 2021, మంగళవారం",
        "వచ్చే శుక్రవారం",
        "2 రోజుల క్రితం",
        "2 గంటల క్రితం",
        "2 నిమిషాల క్రితం",
        "20 సెకన్ల క్రితం",
        "జులై 6, 2025, ఆదివారం",
        "నవంబర్ 6, 2021, శనివారం",
        "మంగళవారం నుండి ఒక వారం",
        "నిన్న",
        "2 రోజుల్లో",
        "2 గంటల్లో",
        "2 నిమిషాల్లో",
        "20 సెకన్లలో"
    ],
    "th": [
        "วันอาทิตย์ที่ 14 กุมภาพันธ์ พ.ศ. 2564 12 นาฬิกา 34 นาที 56 วินาที เวลาสากลเชิงพิกัด",
        "14 กุมภาพันธ์ 2564 12 นาฬิกา 34 นาที 56 วินาที UTC",
        "14/2/64 12:34",
        "วันอาทิตย์ 14 กุมภาพันธ์ 2021 12:34:56 - วันอังคาร 6 กรกฎาคม 12:34:56 เวลาสากลเชิงพิกัด",
        "రోజుల్లో",
        "เมื่อสักครู่นี้",
        "ในอีกสักครู่",
        "วันนี้",
        "พรุ่งนี้",
        "เมื่อวาน",
        "วันจันทร์ 6 กรกฎาคม 2020",
        "วันอาทิตย์ 6 มิถุนายน 2021",
        "วันอังคาร อาทิตย์ที่แล้ว",
        "เมื่อวาน",
        "1 ชั่วโมงที่ผ่านมา",
        "1 นาทีที่ผ่านมา",
        "เมื่อสักครู่นี้",
        "วันพุธ 6 กรกฎาคม 2022",
        "วันศุกร์ 6 สิงหาคม 2021",
        "วันอังคารหน้า",
        "พรุ่งนี้",
        "ในอีก 1 ชั่วโมง",
        "ในอีก 1 นาที",
        "ในอีกสักครู่",
        "วันพฤหัสบดี 6 กรกฎาคม 2017",
        "วันเสาร์ 6 มีนาคม 2021",
        "วันอังคาร 15 มิถุนายน 2021",
        "วันศุกร์ อาทิตย์ที่แล้ว",
        "2 วันที่ผ่านมา",
        "2 ชั่วโมงที่ผ่านมา",
        "2 นาทีที่ผ่านมา",
        "20 วินาทีที่ผ่านมา",
        "วันอาทิตย์ 6 กรกฎาคม 2025",
        "วันเสาร์ 6 พฤศจิกายน 2021",
        "ใน 3 สัปดาห์ในวันอังคาร",
        "วันเสาร์หน้า",
        "ใน 2 วัน",
        "ในอีก 2 ชั่วโมง",
        "ในอีก 2 นาที",
        "ในอีก 20 วินาที"
    ],
    "tr": [
        "14 Şubat 2021 Pazar 12:34:56 Eş Güdümlü Evrensel Zaman",
        "14 Şubat 2021 12:34:56 UTC",
        "14.02.2021 12:34",
        "Pazar 14 Şubat 2021 at 12:34:56 - Salı 6 Temmuz 12:34:56 Coordinated Universal Time",
        "şimdi",
        "birkaç dakika önce",
        "birkaç dakika içinde",
        "bugün",
        "yarın",
        "dün",
        "PaUTCartesi 6 Temmuz 2020",
        "Pazar 6 Haziran 2021",
        "Salı, geçen hafta",
        "dün",
        "1 saat önce",
        "1 dakika önce",
        "birkaç dakika önce",
        "Çarşamba 6 TemmuUTC 2022",
        "Cuma 6 Ağustos 2021",
        "gelecek Salı",
        "yarın",
        "1 saat sonra",
        "1 dakika sonra",
        "birkaç dakika içinde",
        "Perşembe 6 TemmuUTC 2017",
        "Cumartesi 6 Mart 2021",
        "Salı 15 Haziran 2021",
        "Cuma, geçen hafta",
        "2 gün önce",
        "2 saat önce",
        "2 dakika önce",
        "20 saniye önce",
        "PaUTCar 6 Temmuz 2025",
        "Cumartesi 6 Kasım 2021",
        "3 hafta sonra, Salı",
        "gelecek Cumartesi",
        "2 gün içerisinde",
        "2 saat sonra",
        "2 dakika sonra",
        "20 saniye sonra"
    ],
    "uk": [
        "неділя, 14 лютого 2021 р. о 12:34:56 за всесвітнім координованим часом",
        "14 лютого 2021 р. о 12:34:56 UTC",
        "14.02.21, 12:34",
        "неділя, 14 лютого 2021 року, o 12:34:56 - вівторок, 6 липня 12:34:56 Універсальний скоординований час",
        "зараз",
        "кілька хвилин тому",
        "за кілька хвилин",
        "сьогодні",
        "завтра",
        "вчора",
        "понеділок, 6 липня 2020 року",
        "неділя, 6 червня 2021 року",
        "вівторок, минулого тижня",
        "вчора",
        "1 годину тому",
        "1 хвилину тому",
        "кілька хвилин тому",
        "середа, 6 липня 2022 року",
        "пʼятниця, 6 серпня 2021 року",
        "наступного вівторок",
        "завтра",
        "через 1 годину",
        "через 1 хвилину",
        "за кілька хвилин",
        "четвер, 6 липня 2017 року",
        "субота, 6 березня 2021 року",
        "вівторок, 15 червня 2021 року",
        "пʼятниця, минулого тижня",
        "2 дні тому",
        "2 години тому",
        "2 хвилини тому",
        "20 секунд тому",
        "неділя, 6 липня 2025 року",
        "субота, 6 листопада 2021 року",
        "через 3 тижні, у вівторок",
        "наступного субота",
        "через 2 дні",
        "через 2 години",
        "через 2 хвилини",
        "через 20 секунд"
    ],
    "uz": [
        "yakshanba, 14-fevral, 2021, 12:34:56 (Koordinatali universal vaqt)",
        "14-fevral, 2021, 12:34:56 (UTC)",
        "14/02/21, 12:34",
        "2021 yil 14-fevral, yakshanba k1613306096ni 56oat 12:34:56 - 6-iyul, seshanba k1625574896ni 56oat 12:34:56 Umumjahon vaqti muvofiqlashtirilgan",
        "hozir",
        "bir necha lahza oldin",
        "bir necha lahzada",
        "Bugun",
        "ertaga",
        "kecha",
        "2020 yil 6-iyul, dushanba k1594038296ni",
        "2021 yil 6-iyun, yakshanba k1622982296ni",
        "seshanba, o'tgan hafta",
        "kecha",
        "1 soat oldin",
        "1 daqiqa oldin",
        "bir necha lahza oldin",
        "2022 yil 6-iyul, chorshanba k1657110296ni",
        "2021 yil 6-avgust, juma k1628252696ni",
        "keyingi seshanba",
        "ertaga",
        "1 soatdan keyin",
        "1 daqiqadan keyin",
        "bir necha lahzada",
        "2017 yil 6-iyul, payshanba k1499343896ni",
        "2021 yil 6-mart, shanba k1615033496ni",
        "2021 yil 15-iyun, seshanba k1623759896ni",
        "juma, o'tgan hafta",
        "2 kun oldin",
        "2 soat oldin",
        "2 daqiqa oldin",
        "20 soniya oldin",
        "2025 yil 6-iyul, yakshanba k1751804696ni",
        "2021 yil 6-noyabr, shanba k1636201496ni",
        "3 hafta ichida, seshanba kuni",
        "keyingi shanba",
        "2 kun ichida",
        "2 soatdan keyin",
        "2 daqiqadan keyin",
        "20 soniyadan keyin"
    ],
    "vi": [
        "12:34:56 Giờ Phối hợp Quốc tế Chủ Nhật, 14 tháng 2, 2021",
        "12:34:56 UTC 14 tháng 2, 2021",
        "12:34, 14/02/2021",
        "Chủ Nhật, ngày 14 tháng 2 nă34 2021 lúc 12:34:56 - Thứ Ba, ngày 6 tháng 7 nă34 12:34:56 Giờ phối hợp quốc tế",
        "hiện nay",
        "một vài phút trước",
        "Trong giây lát",
        "hôm nay",
        "ngày mai",
        "hôm qua",
        "Thứ Hai, ngày 6 tháng 7 nă24 2020",
        "Chủ Nhật, ngày 6 tháng 6 nă24 2021",
        "Thứ Ba, tuần trước",
        "hôm qua",
        "1 giờ trước",
        "1 phút trước",
        "một vài phút trước",
        "Thứ Tư, ngày 6 tháng 7 nă24 2022",
        "Thứ Sáu, ngày 6 tháng 8 nă24 2021",
        "Thứ Ba tới",
        "ngày mai",
        "sau 1 giờ nữa",
        "sau 1 phút nữa",
        "Trong giây lát",
        "Thứ Năm, ngày 6 tháng 7 nă24 2017",
        "Thứ Bảy, ngày 6 tháng 3 nă24 2021",
        "Thứ Ba, ngày 15 tháng 6 nă24 2021",
        "Thứ Sáu, tuần trước",
        "2 ngày trước",
        "2 giờ trước",
        "2 phút trước",
        "20 giây trước",
        "Chủ Nhật, ngày 6 tháng 7 nă24 2025",
        "Thứ Bảy, ngày 6 tháng 11 nă24 2021",
        "trong 3 tuần, vào Thứ Ba",
        "Thứ Bảy tới",
        "trong 2 ngày nữa",
        "sau 2 giờ nữa",
        "sau 2 phút nữa",
        "sau 20 giây nữa"
    ],
    "zh": [
        "2021年2月14日星期日 协调世界时 下午12:34:56",
        "2021年2月14日 UTC 下午12:34:56",
        "2021/2/14 下午12:34",
        "星期日 14 2 2021 at 12:34:56 - 星期二 6 7 12:34:56 Coordinated Universal Time",
        "现在",
        "几分钟前",
        "过一会儿",
        "今天",
        "明天",
        "昨天",
        "星期一 6 7 2020",
        "星期日 6 6 2021",
        "星期二, 上周",
        "昨天",
        "1小时前",
        "1分钟前",
        "几分钟前",
        "星期三 6 7 2022",
        "星期五 6 8 2021",
        "next 星期二",
        "明天",
        "1小时后",
        "1分钟后",
        "过一会儿",
        "星期四 6 7 2017",
        "星期六 6 3 2021",
        "星期二 15 6 2021",
        "星期五, 上周",
        "2 天前",
        "2小时前",
        "2分钟前",
        "20秒钟前",
        "星期日 6 7 2025",
        "星期六 6 11 2021",
        "从 3 周，在 星期二",
        "next 星期六",
        "在 2 天",
        "2小时后",
        "2分钟后",
        "20秒钟后"
    ]
}