export default {
    "am": [
        "2021 ፌብሩዋሪ 14, እሑድ 12:34:56 ከሰዓት የተቀነባበረ ሁለገብ ሰዓት",
        "14 ፌብሩዋሪ 2021 12:34:56 ከሰዓት UTC",
        "14/02/2021 12:34 ከሰዓት",
        "2021 ፌብሩዋሪ 14, እሑድ 12:34:56 ከሰዓት - ጁላይ 6, እሑድ 12:34:56 ከሰዓት የተቀናጀ ሁለንተናዊ ሰዓት",
        "አሁን",
        "ከጥቂት ጊዜያት በፊት",
        "በጥቂት ጊዜያት ውስጥ",
        "ዛሬ",
        "ነገ",
        "ትናንት",
        "ትናንት",
        "ከ 2 ቀናት በፊት",
        "ማክሰኞ ፣ ባለፈው ሳምንት",
        "ትናንት",
        "ከ1 ሰዓት በፊት",
        "ከ1 ደቂቃ በፊት",
        "ከጥቂት ጊዜያት በፊት",
        "ነገ",
        "በሚቀጥለው ዓርብ",
        "በሚቀጥለው ማክሰኞ",
        "ነገ",
        "በ1 ሰዓት ውስጥ",
        "በ1 ደቂቃ ውስጥ",
        "በጥቂት ጊዜያት ውስጥ",
        "ሐሙስ ፣ ባለፈው ሳምንት",
        "ቅዳሜ ፣ ባለፈው ሳምንት",
        "ማክሰኞ, ከ 3 ሳምንታት በፊት",
        "ዓርብ ፣ ባለፈው ሳምንት",
        "ከ 2 ቀናት በፊት",
        "ከ2 ሰዓቶች በፊት",
        "ከ2 ደቂቃዎች በፊት",
        "ከ20 ሰከንዶች በፊት",
        "በሚቀጥለው እሑድ",
        "በሚቀጥለው ቅዳሜ",
        "በሚቀጥለው ማክሰኞ",
        "በሚቀጥለው ቅዳሜ",
        "በ 2 ቀናት ውስጥ",
        "በ2 ሰዓቶች ውስጥ",
        "በ2 ደቂቃዎች ውስጥ",
        "በ20 ሰከንዶች ውስጥ"
    ],
    "ar": [
        "الأحد، ١٤ فبراير ٢٠٢١ في ١٢:٣٤:٥٦ م التوقيت العالمي المنسق",
        "١٤ فبراير ٢٠٢١ في ١٢:٣٤:٥٦ م UTC",
        "١٤‏/٢‏/٢٠٢١، ١٢:٣٤ م",
        "الأحد, فبراير 14, 2021 12:34:56 مساءً - الثلاثاء, يوليو 6, 12:34:56 مساءً توقيت عالمي متناسق",
        "الآن",
        "قبل لحظات قليلة",
        "في لحظات قليلة",
        "اليوم",
        "غدا",
        "في الامس",
        "في الامس",
        "منذ 2 أيام",
        "الالثلاثاء الأسبوع الماضي",
        "في الامس",
        "قبل ساعة واحدة",
        "قبل دقيقة واحدة",
        "قبل لحظات قليلة",
        "غدا",
        "الالجمعة القادمة",
        "الالثلاثاء القادمة",
        "غدا",
        "خلال ساعة واحدة",
        "خلال دقيقة واحدة",
        "في لحظات قليلة",
        "الالخميس الأسبوع الماضي",
        "الالسبت الأسبوع الماضي",
        "الالثلاثاء ، قبل weeks أسابيع",
        "الالجمعة الأسبوع الماضي",
        "منذ 2 أيام",
        "قبل ساعتين",
        "قبل دقيقتين",
        "قبل ٢٠ ثانية",
        "الالأحد القادمة",
        "الالسبت القادمة",
        "الالثلاثاء القادمة",
        "الالسبت القادمة",
        "في 2 أيام",
        "خلال ساعتين",
        "خلال دقيقتين",
        "خلال ٢٠ ثانية"
    ],
    "az": [
        "14 fevral 2021, bazar/12:34:56 Koordinasiya edilmiş ümumdünya vaxtı",
        "14 fevral 2021 at 12:34:56 UTC",
        "14.02.21, 12:34",
        "fevral 14 2021 bazar, 56aat 12:34:56 - iyul 6 56aat 12:34:56 Razılaşdırılmış Universal Saat",
        "İndi",
        "bir neçə dəqiqə əvvəl",
        "bir neçə dəqiqədə",
        "bu gün",
        "sabah",
        "dünən",
        "dünən",
        "2 gün əvvəl",
        "çərşənbə axşamı günü, keçən həftə",
        "dünən",
        "1 saat öncə",
        "1 dəqiqə öncə",
        "bir neçə dəqiqə əvvəl",
        "sabah",
        "növbəti cümə günü",
        "növbəti çərşənbə axşamı günü",
        "sabah",
        "1 saat ərzində",
        "1 dəqiqə ərzində",
        "bir neçə dəqiqədə",
        "cümə axşamı günü, keçən həftə",
        "şənbə günü, keçən həftə",
        "çərşənbə axşamı, 3 həftə əvvəl",
        "cümə günü, keçən həftə",
        "2 gün əvvəl",
        "2 saat öncə",
        "2 dəqiqə öncə",
        "20 saniyə öncə",
        "növbəti bazar günü",
        "növbəti şənbə günü",
        "növbəti çərşənbə axşamı günü",
        "növbəti şənbə günü",
        "2 günə",
        "2 saat ərzində",
        "2 dəqiqə ərzində",
        "20 saniyə ərzində"
    ],
    "bg": [
        "неделя, 14 февруари 2021 г. в 12:34:56 ч. Координирано универсално време",
        "14 февруари 2021 г. в 12:34:56 ч. UTC",
        "14.02.21 г., 12:34",
        "неделя, 14 февруари 2021 в 12:34:56 - вторник, 6 юли 12:34:56 Координирано универсално време",
        "сега",
        "преди няколко мига",
        "след няколко мига",
        "днес",
        "утре",
        "вчера",
        "вчера",
        "преди 2 дни",
        "вторник, миналата седмица",
        "вчера",
        "преди 1 час",
        "преди 1 минута",
        "преди няколко мига",
        "утре",
        "следващата петък",
        "следващата вторник",
        "утре",
        "след 1 час",
        "след 1 минута",
        "след няколко мига",
        "четвъртък, миналата седмица",
        "събота, миналата седмица",
        "вторник, преди 3 седмици",
        "петък, миналата седмица",
        "преди 2 дни",
        "преди 2 часа",
        "преди 2 минути",
        "преди 20 секунди",
        "следващата неделя",
        "следващата събота",
        "следващата вторник",
        "следващата събота",
        "за 2 дни",
        "след 2 часа",
        "след 2 минути",
        "след 20 секунди"
    ],
    "bn": [
        "রবিবার, ১৪ ফেব্রুয়ারী, ২০২১ এ ১২:৩৪:৫৬ PM স্থানাংকিত আন্তর্জাতিক সময়",
        "১৪ ফেব্রুয়ারী, ২০২১ এ ১২:৩৪:৫৬ PM UTC",
        "১৪/২/২১, ১২:৩৪ PM",
        "রবিবার, 14 ফেব্রুয়ারী 2021 এ 12:34:56 - মঙ্গলবার, 6 জুলাই 12:34:56 সমন্বয়িত ইউনিভার্সাল টাইম",
        "এখন",
        "কয়েক মুহুর্ত আগে",
        "কয়েক মুহুর্তে",
        "আজ",
        "আগামীকাল",
        "গতকাল",
        "গতকাল",
        "2 দিন আগে",
        "মঙ্গলবার, গত সপ্তাহে",
        "গতকাল",
        "১ ঘন্টা আগে",
        "১ মিনিট আগে",
        "কয়েক মুহুর্ত আগে",
        "আগামীকাল",
        "পরবর্তী শুক্রবার",
        "পরবর্তী মঙ্গলবার",
        "আগামীকাল",
        "১ ঘন্টায়",
        "১ মিনিটে",
        "কয়েক মুহুর্তে",
        "বৃহস্পতিবার, গত সপ্তাহে",
        "শনিবার, গত সপ্তাহে",
        "মঙ্গলবার, 3 সপ্তাহ আগে",
        "শুক্রবার, গত সপ্তাহে",
        "2 দিন আগে",
        "২ ঘন্টা আগে",
        "২ মিনিট আগে",
        "২০ সেকেন্ড পূর্বে",
        "পরবর্তী রবিবার",
        "পরবর্তী শনিবার",
        "পরবর্তী মঙ্গলবার",
        "পরবর্তী শনিবার",
        "2 দিনের মধ্যে",
        "২ ঘন্টায়",
        "২ মিনিটে",
        "২০ সেকেন্ডে"
    ],
    "bs": [
        "nedjelja, 14. februar 2021. u 12:34:56 Koordinirano svjetsko vrijeme",
        "14. februar 2021. u 12:34:56 UTC",
        "14. 2. 2021. u 12:34",
        "nedjelja, 14. februar 2021. 1613306096 12:34:56 - utorak, 6. juli 12:34:56 Univerzalno koordinirano vrijeme",
        "sad",
        "pre nekoliko trenutaka",
        "za nekoliko trenutaka",
        "danas",
        "sutra",
        "juce",
        "juce",
        "pre 2 dana",
        "utorak, prošli tjedan",
        "juce",
        "prije 1 sat",
        "prije 1 minutu",
        "pre nekoliko trenutaka",
        "sutra",
        "sljedeći petak",
        "sljedeći utorak",
        "sutra",
        "za 1 sat",
        "za 1 minutu",
        "za nekoliko trenutaka",
        "četvrtak, prošli tjedan",
        "subota, prošli tjedan",
        "utorak, prije 3 sedmice",
        "petak, prošli tjedan",
        "pre 2 dana",
        "prije 2 sata",
        "prije 2 minute",
        "prije 20 sekundi",
        "sljedeći nedjelja",
        "sljedeći subota",
        "sljedeći utorak",
        "sljedeći subota",
        "za 2 dana",
        "za 2 sata",
        "za 2 minute",
        "za 20 sekundi"
    ],
    "ca": [
        "diumenge, 14 de febrer del 2021, a les 12:34:56 (Temps universal coordinat)",
        "14 de febrer del 2021, a les 12:34:56 UTC",
        "14/2/21 12:34",
        "diumenge 14 de de febrer de 2021 a le56 12:34:56 - dimarts 6 de de juliol de 56 12:34:56 Temps Universal Coordinat",
        "ara",
        "fa uns moments",
        "en pocs moments",
        "avui",
        "demà",
        "ahir",
        "ahir",
        "fa 2 dies",
        "dimarts, la setmana passada",
        "ahir",
        "fa 1 hora",
        "fa 1 minut",
        "fa uns moments",
        "demà",
        "el pròxim divendres",
        "el pròxim dimarts",
        "demà",
        "d’aquí a 1 hora",
        "d’aquí a 1 minut",
        "en pocs moments",
        "dijous, la setmana passada",
        "dissabte, la setmana passada",
        "dimarts, fa 3 setmanes",
        "divendres, la setmana passada",
        "fa 2 dies",
        "fa 2 hores",
        "fa 2 minuts",
        "fa 20 segons",
        "el pròxim diumenge",
        "el pròxim dissabte",
        "el pròxim dimarts",
        "el pròxim dissabte",
        "en 2 dies",
        "d’aquí a 2 hores",
        "d’aquí a 2 minuts",
        "d’aquí a 20 segons"
    ],
    "cs": [
        "neděle 14. února 2021 v 12:34:56, koordinovaný světový čas",
        "14. února 2021 v 12:34:56 UTC",
        "14.02.21 12:34",
        "neděle 14. února 2021 v 12:34:56 - úterý 6. července 12:34:56 Koordinovaný světový čas",
        "nyní",
        "před několika okamžiky",
        "za pár okamžiků",
        "dnes",
        "zítra",
        "včera",
        "včera",
        "před 2 dny",
        "úterý, minulý týden",
        "včera",
        "před 1 hodinou",
        "před 1 minutou",
        "před několika okamžiky",
        "zítra",
        "příští pátek",
        "příští úterý",
        "zítra",
        "za 1 hodinu",
        "za 1 minutu",
        "za pár okamžiků",
        "čtvrtek, minulý týden",
        "sobota, minulý týden",
        "úterý, před 3 týdny",
        "pátek, minulý týden",
        "před 2 dny",
        "před 2 hodinami",
        "před 2 minutami",
        "před 20 sekundami",
        "příští neděle",
        "příští sobota",
        "příští úterý",
        "příští sobota",
        "za 2 dny",
        "za 2 hodiny",
        "za 2 minuty",
        "za 20 sekund"
    ],
    "da": [
        "søndag den 14. februar 2021 kl. 12.34.56 Koordineret universaltid",
        "14. februar 2021 kl. 12.34.56 UTC",
        "14.02.2021, 12.34",
        "søndag 14. februar 2021 kl. 12:34:56 - tirsdag 6. juli 12:34:56 Koordineret universel tid",
        "nu",
        "for et øjeblik siden",
        "om få øjeblikke",
        "i dag",
        "i morgen",
        "i går",
        "i går",
        "2 dage siden",
        "tirsdag, sidste uge",
        "i går",
        "for 1 time siden",
        "for 1 minut siden",
        "for et øjeblik siden",
        "i morgen",
        "næste fredag",
        "næste tirsdag",
        "i morgen",
        "om 1 time",
        "om 1 minut",
        "om få øjeblikke",
        "torsdag, sidste uge",
        "lørdag, sidste uge",
        "tirsdag, for 3 uger siden",
        "fredag, sidste uge",
        "2 dage siden",
        "for 2 timer siden",
        "for 2 minutter siden",
        "for 20 sekunder siden",
        "næste søndag",
        "næste lørdag",
        "næste tirsdag",
        "næste lørdag",
        "om 2 dage",
        "om 2 timer",
        "om 2 minutter",
        "om 20 sekunder"
    ],
    "de": [
        "Sonntag, 14. Februar 2021 um 12:34:56 Koordinierte Weltzeit",
        "14. Februar 2021 um 12:34:56 UTC",
        "14.02.21, 12:34",
        "Sonntag 14. Februar 2021 161330609634 12:34:56 - Dienstag 6. Juli 34 12:34:56 koordinierte Weltzeit",
        "jetzt",
        "vor wenigen Augenblicken",
        "in ein paar Momenten",
        "heute",
        "morgen",
        "gestern",
        "gestern",
        "vor 2 tagen",
        "Dienstag, letzte Woche",
        "gestern",
        "vor 1 Stunde",
        "vor 1 Minute",
        "vor wenigen Augenblicken",
        "morgen",
        "nächsten Freitag",
        "nächsten Dienstag",
        "morgen",
        "in 1 Stunde",
        "in 1 Minute",
        "in ein paar Momenten",
        "Donnerstag, letzte Woche",
        "Samstag, letzte Woche",
        "Dienstag, vor 3 wochen",
        "Freitag, letzte Woche",
        "vor 2 tagen",
        "vor 2 Stunden",
        "vor 2 Minuten",
        "vor 20 Sekunden",
        "nächsten Sonntag",
        "nächsten Samstag",
        "nächsten Dienstag",
        "nächsten Samstag",
        "in 2 tagen",
        "in 2 Stunden",
        "in 2 Minuten",
        "in 20 Sekunden"
    ],
    "el": [
        "Κυριακή 14 Φεβρουαρίου 2021 στις 12:34:56 μ.μ. Συντονισμένη Παγκόσμια Ώρα",
        "14 Φεβρουαρίου 2021 στις 12:34:56 μ.μ. UTC",
        "14/2/21, 12:34 μ.μ.",
        "Κυριακή 14 Φεβρουαρίου 2021 στις 12:34:56 - Τρίτη 6 Ιουλίου 12:34:56 Συντονισμένη καθολική ώρα",
        "τώρα",
        "πριν από λίγα λεπτά",
        "σε λίγες στιγμές",
        "σήμερα",
        "αύριο",
        "εχθές",
        "εχθές",
        "πριν από 2 ημέρες",
        "Τρίτη, περασμένη εβδομάδα",
        "εχθές",
        "πριν από 1 ώρα",
        "πριν από 1 λεπτό",
        "πριν από λίγα λεπτά",
        "αύριο",
        "την επόμενη Παρασκευή",
        "την επόμενη Τρίτη",
        "αύριο",
        "σε 1 ώρα",
        "σε 1 λεπτό",
        "σε λίγες στιγμές",
        "Πέμπτη, περασμένη εβδομάδα",
        "Σάββατο, περασμένη εβδομάδα",
        "Τρίτη, 3 εβδομάδες πριν",
        "Παρασκευή, περασμένη εβδομάδα",
        "πριν από 2 ημέρες",
        "πριν από 2 ώρες",
        "πριν από 2 λεπτά",
        "πριν από 20 δευτερόλεπτα",
        "την επόμενη Κυριακή",
        "την επόμενη Σάββατο",
        "την επόμενη Τρίτη",
        "την επόμενη Σάββατο",
        "σε 2 ημέρες",
        "σε 2 ώρες",
        "σε 2 λεπτά",
        "σε 20 δευτερόλεπτα"
    ],
    "en": [
        "Sunday, February 14, 2021 at 12:34:56 PM Coordinated Universal Time",
        "February 14, 2021 at 12:34:56 PM UTC",
        "2/14/21, 12:34 PM",
        "Sunday, February 14, 2021 at 12:34:56 PM - Tuesday, July 6, 12:34:56 PM Coordinated Universal Time",
        "now",
        "a few moments ago",
        "in a few moments",
        "today",
        "tomorrow",
        "yesterday",
        "yesterday",
        "2 days ago",
        "Tuesday, last week",
        "yesterday",
        "1 hour ago",
        "1 minute ago",
        "a few moments ago",
        "tomorrow",
        "next Friday",
        "next Tuesday",
        "tomorrow",
        "in 1 hour",
        "in 1 minute",
        "in a few moments",
        "Thursday, last week",
        "Saturday, last week",
        "Tuesday, 3 weeks ago",
        "Friday, last week",
        "2 days ago",
        "2 hours ago",
        "2 minutes ago",
        "20 seconds ago",
        "next Sunday",
        "next Saturday",
        "next Tuesday",
        "next Saturday",
        "in 2 days",
        "in 2 hours",
        "in 2 minutes",
        "in 20 seconds"
    ],
    "es": [
        "domingo, 14 de febrero de 2021, 12:34:56 (tiempo universal coordinado)",
        "14 de febrero de 2021, 12:34:56 UTC",
        "14/2/21, 12:34",
        "domingo, 14 de febrero de 2021, 12:34:56 - martes, 6 de julio de 12:34:56 (tiempo universal coordinado)",
        "ahora",
        "hace unos momentos",
        "en unos momentos",
        "hoy",
        "mañana",
        "ayer",
        "ayer",
        "hace 2 días",
        "martes, la semana pasada",
        "ayer",
        "hace 1 hora",
        "hace 1 minuto",
        "hace unos momentos",
        "mañana",
        " próximo viernes",
        " próximo martes",
        "mañana",
        "dentro de 1 hora",
        "dentro de 1 minuto",
        "en unos momentos",
        "jueves, la semana pasada",
        "sábado, la semana pasada",
        "martes, hace 3 semanas",
        "viernes, la semana pasada",
        "hace 2 días",
        "hace 2 horas",
        "hace 2 minutos",
        "hace 20 segundos",
        " próximo domingo",
        " próximo sábado",
        " próximo martes",
        " próximo sábado",
        "en 2 días",
        "dentro de 2 horas",
        "dentro de 2 minutos",
        "dentro de 20 segundos"
    ],
    "et": [
        "pühapäev, 14. veebruar 2021, kell 12:34:56 Koordineeritud maailmaaeg",
        "14. veebruar 2021, kell 12:34:56 UTC",
        "14.02.21, 12:34",
        "pühapäev, 14. veebruar 2021 kell 12:34:56 - teisipäev, 6. juuli 12:34:56 Koordineeritud ülemaailmne aeg",
        "nüüd",
        "mõni hetk tagasi",
        "mõne hetke pärast",
        "täna",
        "homme",
        "eile",
        "eile",
        "2 päeva tagasi",
        "teisipäev nädala pühapäev",
        "eile",
        "1 tunni eest",
        "1 minuti eest",
        "mõni hetk tagasi",
        "homme",
        "järgmisel reede",
        "järgmisel teisipäev",
        "homme",
        "1 tunni pärast",
        "1 minuti pärast",
        "mõne hetke pärast",
        "neljapäev nädala pühapäev",
        "laupäev nädala pühapäev",
        "teisipäev, 3 nädalat tagasi",
        "reede nädala pühapäev",
        "2 päeva tagasi",
        "2 tunni eest",
        "2 minuti eest",
        "20 sekundi eest",
        "järgmisel pühapäev",
        "järgmisel laupäev",
        "järgmisel teisipäev",
        "järgmisel laupäev",
        "2 päeva pärast",
        "2 tunni pärast",
        "2 minuti pärast",
        "20 sekundi pärast"
    ],
    "fa": [
        "۱۳۹۹ بهمن ۲۶, یکشنبه ساعت ۱۲:۳۴:۵۶ (زمان هماهنگ جهانی)",
        "۲۶ بهمن ۱۳۹۹ ساعت ۱۲:۳۴:۵۶ (UTC)",
        "۱۳۹۹/۱۱/۲۶, ۱۲:۳۴",
        "2021 بهمن 14 یکشنبه ساعت 12:34:56 - تیر 6 سه‌شنبه ساعت 12:34:56 زمان جهانی هماهنگ",
        "اکنون",
        "چند لحظه پیش",
        "در چند لحظه",
        "امروز",
        "فردا",
        "دیروز",
        "دیروز",
        "2 روز پیش",
        "سه‌شنبه، هفته گذشته",
        "دیروز",
        "۱ ساعت پیش",
        "۱ دقیقه پیش",
        "چند لحظه پیش",
        "فردا",
        "جمعه بعدی",
        "سه‌شنبه بعدی",
        "فردا",
        "۱ ساعت بعد",
        "۱ دقیقه بعد",
        "در چند لحظه",
        "پنجشنبه، هفته گذشته",
        "شنبه، هفته گذشته",
        "سه‌شنبه، 3 هفته پیش",
        "جمعه، هفته گذشته",
        "2 روز پیش",
        "۲ ساعت پیش",
        "۲ دقیقه پیش",
        "۲۰ ثانیه پیش",
        "یکشنبه بعدی",
        "شنبه بعدی",
        "سه‌شنبه بعدی",
        "شنبه بعدی",
        "در 2 روز",
        "۲ ساعت بعد",
        "۲ دقیقه بعد",
        "۲۰ ثانیه بعد"
    ],
    "fi": [
        "sunnuntai 14. helmikuuta 2021 klo 12.34.56 UTC-yleisaika",
        "14. helmikuuta 2021 klo 12.34.56 UTC",
        "14.2.2021 klo 12.34",
        "sunnuntai 14. helmikuuta 2021 klo 12:34:56 - tiistai 6. heinäkuuta 12:34:56 Koordinoidut maailmanajat",
        "nyt",
        "muutama hetki sitten",
        "hetkessä",
        "tänään",
        "huomenna",
        "eilen",
        "eilen",
        "2 päivää sitten",
        "tiistai, viime viikko",
        "eilen",
        "1 tunti sitten",
        "1 minuutti sitten",
        "muutama hetki sitten",
        "huomenna",
        "ensi perjantai",
        "ensi tiistai",
        "huomenna",
        "1 tunnin päästä",
        "1 minuutin päästä",
        "hetkessä",
        "torstai, viime viikko",
        "lauantai, viime viikko",
        "tiistai, 3 viikkoa sitten",
        "perjantai, viime viikko",
        "2 päivää sitten",
        "2 tuntia sitten",
        "2 minuuttia sitten",
        "20 sekuntia sitten",
        "ensi sunnuntai",
        "ensi lauantai",
        "ensi tiistai",
        "ensi lauantai",
        "2 päivässä",
        "2 tunnin päästä",
        "2 minuutin päästä",
        "20 sekunnin päästä"
    ],
    "fil": [
        "Linggo, Pebrero 14, 2021 nang 12:34:56 PM Coordinated Universal Time",
        "Pebrero 14, 2021 nang 12:34:56 PM UTC",
        "2/14/21, 12:34 PM",
        "Linggo, Pebrero 14, 2021 ng 12:34:56 - Martes, Hulyo 6, 12:34:56 Coordinated Universal Time",
        "ngayon",
        "ilang sandali ang nakaraan",
        "sa ilang sandali",
        "ngayon",
        "bukas",
        "kahapon",
        "kahapon",
        "2 araw na ang nakakalipas",
        "Martes, noong nakaraang linggo",
        "kahapon",
        "1 oras ang nakalipas",
        "1 minuto ang nakalipas",
        "ilang sandali ang nakaraan",
        "bukas",
        "sa susunod na Biyernes",
        "sa susunod na Martes",
        "bukas",
        "sa 1 oras",
        "sa 1 minuto",
        "sa ilang sandali",
        "Huwebes, noong nakaraang linggo",
        "Sabado, noong nakaraang linggo",
        "Martes, 3 linggo ang nakakaraan",
        "Biyernes, noong nakaraang linggo",
        "2 araw na ang nakakalipas",
        "2 oras ang nakalipas",
        "2 minuto ang nakalipas",
        "20 segundo ang nakalipas",
        "sa susunod na Linggo",
        "sa susunod na Sabado",
        "sa susunod na Martes",
        "sa susunod na Sabado",
        "sa 2 araw",
        "sa 2 oras",
        "sa 2 minuto",
        "sa 20 segundo"
    ],
    "fr": [
        "dimanche 14 février 2021 à 12:34:56 temps universel coordonné",
        "14 février 2021 à 12:34:56 UTC",
        "14/02/2021 12:34",
        "dimanche 14 février 2021 à 12:34:56 - mardi 6 juillet 12:34:56 Temps universel coordonné",
        "à présent",
        "il y a quelques instants",
        "dans quelques instants",
        "aujourd'hui",
        "demain",
        "hier",
        "hier",
        "Il ya 2 jours",
        "mardi, la semaine dernière",
        "hier",
        "il y a 1 heure",
        "il y a 1 minute",
        "il y a quelques instants",
        "demain",
        "vendredi prochain",
        "mardi prochain",
        "demain",
        "dans 1 heure",
        "dans 1 minute",
        "dans quelques instants",
        "jeudi, la semaine dernière",
        "samedi, la semaine dernière",
        "mardi,il y a 3 semaines",
        "vendredi, la semaine dernière",
        "Il ya 2 jours",
        "il y a 2 heures",
        "il y a 2 minutes",
        "il y a 20 secondes",
        "dimanche prochain",
        "samedi prochain",
        "mardi prochain",
        "samedi prochain",
        "dans 2 jours",
        "dans 2 heures",
        "dans 2 minutes",
        "dans 20 secondes"
    ],
    "he": [
        "יום ראשון, 14 בפברואר 2021 בשעה 12:34:56 זמן אוניברסלי מתואם",
        "14 בפברואר 2021 בשעה 12:34:56 UTC",
        "14.2.2021, 12:34",
        "2021 פברואר 14 ,יום ראשון בשעה 12:34:56 - יולי 6 ,יום שלישי בשעה 12:34:56 זמן אוניברסלי מתואם",
        "עַכשָׁיו",
        "לפני כמה רגעים",
        "בעוד כמה רגעים",
        "היום",
        "מָחָר",
        "אתמול",
        "אתמול",
        "לפני 2 ימים",
        "יום יום שלישי, שבוע שעבר",
        "אתמול",
        "לפני שעה",
        "לפני דקה",
        "לפני כמה רגעים",
        "מָחָר",
        "יום יום שישי",
        "יום יום שלישי",
        "מָחָר",
        "בעוד שעה",
        "בעוד דקה",
        "בעוד כמה רגעים",
        "יום יום חמישי, שבוע שעבר",
        "יום יום שבת, שבוע שעבר",
        "ב יום שלישי, 3 לפני שבועות",
        "יום יום שישי, שבוע שעבר",
        "לפני 2 ימים",
        "לפני שעתיים",
        "לפני שתי דקות",
        "לפני 20 שניות",
        "יום יום ראשון",
        "יום יום שבת",
        "יום יום שלישי",
        "יום יום שבת",
        "בעוד 2 ימים",
        "בעוד שעתיים",
        "בעוד שתי דקות",
        "בעוד 20 שניות"
    ],
    "hi": [
        "रविवार, 14 फ़रवरी 2021 को 12:34:56 pm समन्वित वैश्विक समय बजे",
        "14 फ़रवरी 2021 को 12:34:56 pm UTC बजे",
        "14/2/21, 12:34 pm",
        "रविवार, 14 फ़रवरी, 2021, 12:34:56 - मंगलवार, 6 जुलाई, 12:34:56 समन्वित वैश्विक समय",
        "अब क",
        "कुछ पल पहले",
        "कुछ ही पलों में",
        "आज",
        "आने वाला कल",
        "बिता हुआ कल",
        "बिता हुआ कल",
        "2 दिन पहले",
        "मंगलवार, पिछले सप्ताह",
        "बिता हुआ कल",
        "1 घंटे पहले",
        "1 मिनट पहले",
        "कुछ पल पहले",
        "आने वाला कल",
        "अगले शुक्रवार",
        "अगले मंगलवार",
        "आने वाला कल",
        "1 घंटे में",
        "1 मिनट में",
        "कुछ ही पलों में",
        "गुरुवार, पिछले सप्ताह",
        "शनिवार, पिछले सप्ताह",
        "मंगलवार, 3 सप्ताह पहले",
        "शुक्रवार, पिछले सप्ताह",
        "2 दिन पहले",
        "2 घंटे पहले",
        "2 मिनट पहले",
        "20 सेकंड पहले",
        "अगले रविवार",
        "अगले शनिवार",
        "अगले मंगलवार",
        "अगले शनिवार",
        "2 दिनों में",
        "2 घंटे में",
        "2 मिनट में",
        "20 सेकंड में"
    ],
    "hr": [
        "nedjelja, 14. veljače 2021. u 12:34:56 (koordinirano svjetsko vrijeme)",
        "14. veljače 2021. u 12:34:56 UTC",
        "14. 02. 2021. 12:34",
        "nedjelja, 14. veljače 2021. 1613306096 12:34:56 - utorak, 6. srpnja 12:34:56 Koordinirano univerzalno vrijeme",
        "sada",
        "prije nekoliko trenutaka",
        "za nekoliko trenutaka",
        "danas",
        "sutra",
        "jučer",
        "jučer",
        "prije 2 dana",
        "utorak, prošli tjedan",
        "jučer",
        "prije 1 sat",
        "prije 1 minutu",
        "prije nekoliko trenutaka",
        "sutra",
        "sljedeći petak",
        "sljedeći utorak",
        "sutra",
        "za 1 sat",
        "za 1 minutu",
        "za nekoliko trenutaka",
        "četvrtak, prošli tjedan",
        "subota, prošli tjedan",
        "utorak, prije 3 tjedna",
        "petak, prošli tjedan",
        "prije 2 dana",
        "prije 2 sata",
        "prije 2 minute",
        "prije 20 sekundi",
        "sljedeći nedjelja",
        "sljedeći subota",
        "sljedeći utorak",
        "sljedeći subota",
        "za 2 dana",
        "za 2 sata",
        "za 2 minute",
        "za 20 sekundi"
    ],
    "hu": [
        "2021. február 14., vasárnap 12:34:56 koordinált világidő",
        "2021. február 14. 12:34:56 UTC",
        "2021. 02. 14. 12:34",
        "2021. február 14.,vasárnap, 12:34:56 - július 6.,kedd, 12:34:56 Koordinált világidő",
        "Most",
        "néhány pillanattal ezelőtt",
        "néhány pillanat múlva",
        "Ma",
        "holnap",
        "tegnap",
        "tegnap",
        "2 napja",
        "Múlt hét kedd",
        "tegnap",
        "1 órával ezelőtt",
        "1 perccel ezelőtt",
        "néhány pillanattal ezelőtt",
        "holnap",
        "jövő péntek",
        "jövő kedd",
        "holnap",
        "1 óra múlva",
        "1 perc múlva",
        "néhány pillanat múlva",
        "Múlt hét csütörtök",
        "Múlt hét szombat",
        "hete hete, kedd",
        "Múlt hét péntek",
        "2 napja",
        "2 órával ezelőtt",
        "2 perccel ezelőtt",
        "20 másodperccel ezelőtt",
        "jövő vasárnap",
        "jövő szombat",
        "jövő kedd",
        "jövő szombat",
        "2 napon belül",
        "2 óra múlva",
        "2 perc múlva",
        "20 másodperc múlva"
    ],
    "id": [
        "Minggu, 14 Februari 2021 pukul 12.34.56 Waktu Universal Terkoordinasi",
        "14 Februari 2021 pukul 12.34.56 UTC",
        "14/02/21, 12.34",
        "Minggu, 14 Februari 2021 p1613306096k1613306096l 12:34:56 - Selasa, 6 Juli 12:34:56 Waktu Universal Terkoordinasi",
        "sekarang",
        "beberapa saat yang lalu",
        "dalam beberapa saat",
        "hari ini",
        "besok",
        "kemarin",
        "kemarin",
        "2 hari yang lalu",
        "Selasa, minggu lalu",
        "kemarin",
        "1 jam yang lalu",
        "1 menit yang lalu",
        "beberapa saat yang lalu",
        "besok",
        "Jumat depan",
        "Selasa depan",
        "besok",
        "dalam 1 jam",
        "dalam 1 menit",
        "dalam beberapa saat",
        "Kamis, minggu lalu",
        "Sabtu, minggu lalu",
        "Selasa, 3 minggu yang lalu",
        "Jumat, minggu lalu",
        "2 hari yang lalu",
        "2 jam yang lalu",
        "2 menit yang lalu",
        "20 detik yang lalu",
        "Minggu depan",
        "Sabtu depan",
        "Selasa depan",
        "Sabtu depan",
        "dalam 2 hari",
        "dalam 2 jam",
        "dalam 2 menit",
        "dalam 20 detik"
    ],
    "it": [
        "domenica 14 febbraio 2021 alle ore 12:34:56 Tempo coordinato universale",
        "14 febbraio 2021 alle ore 12:34:56 UTC",
        "14/02/21, 12:34",
        "domenica 14 febbraio 2021 a 12:34:56 - martedì 6 luglio 12:34:56 Tempo Universale Coordinato",
        "adesso",
        "pochi istanti fa",
        "in pochi istanti",
        "oggi",
        "Domani",
        "ieri",
        "ieri",
        "2 giorni fa",
        "martedì, la scorsa settimana",
        "ieri",
        "1 ora fa",
        "1 minuto fa",
        "pochi istanti fa",
        "Domani",
        "venerdì prossimo",
        "martedì prossimo",
        "Domani",
        "tra 1 ora",
        "tra 1 minuto",
        "in pochi istanti",
        "giovedì, la scorsa settimana",
        "sabato, la scorsa settimana",
        "martedì, 3 settimane fa",
        "venerdì, la scorsa settimana",
        "2 giorni fa",
        "2 ore fa",
        "2 minuti fa",
        "20 secondi fa",
        "domenica prossimo",
        "sabato prossimo",
        "martedì prossimo",
        "sabato prossimo",
        "tra 2 giorni",
        "tra 2 ore",
        "tra 2 minuti",
        "tra 20 secondi"
    ],
    "ja": [
        "2021年2月14日日曜日 12時34分56秒 協定世界時",
        "2021年2月14日 12:34:56 UTC",
        "2021/02/14 12:34",
        "日曜日 14 2 2021 12:34:56 - 火曜日 6 7 12:34:56 協定世界時",
        "今",
        "少し前",
        "すぐに",
        "今日",
        "明日",
        "昨日",
        "昨日",
        "2日前",
        "先週の 火曜日",
        "昨日",
        "1 時間前",
        "1 分前",
        "少し前",
        "明日",
        "次の 金曜日",
        "次の 火曜日",
        "明日",
        "1 時間後",
        "1 分後",
        "すぐに",
        "先週の 木曜日",
        "先週の 土曜日",
        "3 週間前の 火曜日",
        "先週の 金曜日",
        "2日前",
        "2 時間前",
        "2 分前",
        "20 秒前",
        "次の 日曜日",
        "次の 土曜日",
        "次の 火曜日",
        "次の 土曜日",
        "2日で",
        "2 時間後",
        "2 分後",
        "20 秒後"
    ],
    "kn": [
        "ಭಾನುವಾರ, ಫೆಬ್ರವರಿ 14, 2021 ರಂದು 12:34:56 ಅಪರಾಹ್ನ ಸಂಘಟಿತ ಸಾರ್ವತ್ರಿಕ ಸಮಯ ಸಮಯಕ್ಕೆ",
        "ಫೆಬ್ರವರಿ 14, 2021 ರಂದು 12:34:56 ಅಪರಾಹ್ನ UTC ಸಮಯಕ್ಕೆ",
        "14/2/21, 12:34 ಅಪರಾಹ್ನ",
        "ಫೆಬ್ರವರಿ 14, 2021 ಭಾನುವಾರ, 12:34:56 - ಜುಲೈ 6, 12:34:56 ಸಂಯೋಜಿತ ಸಾರ್ವತ್ರಿಕ ಸಮಯ",
        "ಈಗ",
        "ಕೆಲವು ಕ್ಷಣಗಳ ಹಿಂದೆ",
        "ಕೆಲವು ಕ್ಷಣಗಳಲ್ಲಿ",
        "ಇಂದು",
        "ನಾಳೆ",
        "ನಿನ್ನೆ",
        "ನಿನ್ನೆ",
        "2 ದಿನಗಳ ಹಿಂದೆ",
        "ಕಳೆದ ವಾರ ಮಂಗಳವಾರ",
        "ನಿನ್ನೆ",
        "1 ಗಂಟೆ ಹಿಂದೆ",
        "1 ನಿಮಿಷದ ಹಿಂದೆ",
        "ಕೆಲವು ಕ್ಷಣಗಳ ಹಿಂದೆ",
        "ನಾಳೆ",
        "ಮುಂದಿನ ಶುಕ್ರವಾರ",
        "ಮುಂದಿನ ಮಂಗಳವಾರ",
        "ನಾಳೆ",
        "1 ಗಂಟೆಯಲ್ಲಿ",
        "1 ನಿಮಿಷದಲ್ಲಿ",
        "ಕೆಲವು ಕ್ಷಣಗಳಲ್ಲಿ",
        "ಕಳೆದ ವಾರ ಗುರುವಾರ",
        "ಕಳೆದ ವಾರ ಶನಿವಾರ",
        "3 ವಾರಗಳ ಹಿಂದೆ ಮಂಗಳವಾರ",
        "ಕಳೆದ ವಾರ ಶುಕ್ರವಾರ",
        "2 ದಿನಗಳ ಹಿಂದೆ",
        "2 ಗಂಟೆಗಳ ಹಿಂದೆ",
        "2 ನಿಮಿಷಗಳ ಹಿಂದೆ",
        "20 ಸೆಕೆಂಡುಗಳ ಹಿಂದೆ",
        "ಮುಂದಿನ ಭಾನುವಾರ",
        "ಮುಂದಿನ ಶನಿವಾರ",
        "ಮುಂದಿನ ಮಂಗಳವಾರ",
        "ಮುಂದಿನ ಶನಿವಾರ",
        "2 ದಿನಗಳಲ್ಲಿ",
        "2 ಗಂಟೆಗಳಲ್ಲಿ",
        "2 ನಿಮಿಷಗಳಲ್ಲಿ",
        "20 ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ"
    ],
    "lt": [
        "2021 m. vasario 14 d., sekmadienis 12:34:56 pasaulio suderintasis laikas",
        "2021 m. vasario 14 d. 12:34:56 UTC",
        "2021-02-14 12:34",
        "2021 n.vasario 14 d., sekmadienis, 12:34:56 - liepos 6 d., antradienis, 12:34:56 Koordinuotas pasaulinis laikas",
        "dabar",
        "prieš kelias akimirkas",
        "per kelias akimirkas",
        "šiandien",
        "rytoj",
        "vakar",
        "vakar",
        "prieš 2 dienas",
        "Praėjusios savaitės antradienis",
        "vakar",
        "prieš 1 valandą",
        "prieš 1 minutę",
        "prieš kelias akimirkas",
        "rytoj",
        "kitą penktadienis",
        "kitą antradienis",
        "rytoj",
        "po 1 valandos",
        "po 1 minutės",
        "per kelias akimirkas",
        "Praėjusios savaitės ketvirtadienis",
        "Praėjusios savaitės šeštadienis",
        "Prieš 3 savaites, antradienis",
        "Praėjusios savaitės penktadienis",
        "prieš 2 dienas",
        "prieš 2 valandas",
        "prieš 2 minutes",
        "prieš 20 sekundžių",
        "kitą sekmadienis",
        "kitą šeštadienis",
        "kitą antradienis",
        "kitą šeštadienis",
        "per 2 dienas",
        "po 2 valandų",
        "po 2 minučių",
        "po 20 sekundžių"
    ],
    "lv": [
        "svētdiena, 2021. gada 14. februāris 12:34:56 Universālais koordinētais laiks",
        "2021. gada 14. februāris 12:34:56 UTC",
        "14.02.21 12:34",
        "svētdiena, 2021 gada 14. februāris plk56t 12:34:56 - otrdiena, 6. jūlijs plk56t 12:34:56 Saskaņotais pasaules laiks",
        "tagad",
        "pirms dažiem mirkļiem",
        "pēc dažiem mirkļiem",
        "šodien",
        "rīt",
        "vakar",
        "vakar",
        "pirms 2 dienām",
        "otrdiena, pagājušā nedēļa",
        "vakar",
        "pirms 1 stundas",
        "pirms 1 minūtes",
        "pirms dažiem mirkļiem",
        "rīt",
        "nākamajā piektdiena",
        "nākamajā otrdiena",
        "rīt",
        "pēc 1 stundas",
        "pēc 1 minūtes",
        "pēc dažiem mirkļiem",
        "ceturtdiena, pagājušā nedēļa",
        "sestdiena, pagājušā nedēļa",
        "Pirms 3weekday",
        "piektdiena, pagājušā nedēļa",
        "pirms 2 dienām",
        "pirms 2 stundām",
        "pirms 2 minūtēm",
        "pirms 20 sekundēm",
        "nākamajā svētdiena",
        "nākamajā sestdiena",
        "nākamajā otrdiena",
        "nākamajā sestdiena",
        "2 dienām",
        "pēc 2 stundām",
        "pēc 2 minūtēm",
        "pēc 20 sekundēm"
    ],
    "ml": [
        "2021, ഫെബ്രുവരി 14, ഞായറാഴ്‌ച 12:34:56 PM കോർഡിനേറ്റഡ് യൂണിവേഴ്‌സൽ സമയം",
        "2021, ഫെബ്രുവരി 14 12:34:56 PM UTC",
        "14/2/21 12:34 PM",
        "2021 ഫെബ്രുവരി 14 ഞായറാഴ്‌ച, 12:34:56 - ജൂലൈ 6 ചൊവ്വാഴ്ച, 12:34:56 ഏകോപിപ്പിച്ച യൂണിവേഴ്സൽ സമയം",
        "ഇപ്പോൾ",
        "കുറച്ച് നിമിഷങ്ങൾക്ക് മുമ്പ്",
        "കുറച്ച് നിമിഷങ്ങൾക്കുള്ളിൽ",
        "ഇന്ന്",
        "നാളെ",
        "ഇന്നലെ",
        "ഇന്നലെ",
        "2 ദിവസങ്ങളിൽ മുമ്പ്",
        "കഴിഞ്ഞ ആഴ്ച ചൊവ്വാഴ്ച",
        "ഇന്നലെ",
        "1 മണിക്കൂർ മുമ്പ്",
        "1 മിനിറ്റ് മുമ്പ്",
        "കുറച്ച് നിമിഷങ്ങൾക്ക് മുമ്പ്",
        "നാളെ",
        "വെള്ളിയാഴ്‌ച അടുത്തത്",
        "ചൊവ്വാഴ്ച അടുത്തത്",
        "നാളെ",
        "1 മണിക്കൂറിൽ",
        "1 മിനിറ്റിൽ",
        "കുറച്ച് നിമിഷങ്ങൾക്കുള്ളിൽ",
        "കഴിഞ്ഞ ആഴ്ച വ്യാഴാഴ്‌ച",
        "കഴിഞ്ഞ ആഴ്ച ശനിയാഴ്‌ച",
        "3 ആഴ്ച മുമ്പ് ചൊവ്വാഴ്ച",
        "കഴിഞ്ഞ ആഴ്ച വെള്ളിയാഴ്‌ച",
        "2 ദിവസങ്ങളിൽ മുമ്പ്",
        "2 മണിക്കൂർ മുമ്പ്",
        "2 മിനിറ്റ് മുമ്പ്",
        "20 സെക്കൻഡ് മുമ്പ്",
        "ഞായറാഴ്‌ച അടുത്തത്",
        "ശനിയാഴ്‌ച അടുത്തത്",
        "ചൊവ്വാഴ്ച അടുത്തത്",
        "ശനിയാഴ്‌ച അടുത്തത്",
        "2 ദിവസം മുൻപ്",
        "2 മണിക്കൂറിൽ",
        "2 മിനിറ്റിൽ",
        "20 സെക്കൻഡിൽ"
    ],
    "mr": [
        "रविवार, १४ फेब्रुवारी, २०२१ रोजी १२:३४:५६ PM समन्वित वैश्विक वेळ",
        "१४ फेब्रुवारी, २०२१ रोजी १२:३४:५६ PM UTC",
        "१४/२/२१, १२:३४ PM",
        "रविवार, 14 फेब्रुवारी 2021, 12:34:56 - मंगळवार, 6 जुलै 12:34:56 समन्वयित युनिव्हर्सल टाइम",
        "आता",
        "काही क्षणांपूर्वी",
        "काही क्षणात",
        "आज",
        "उद्या",
        "काल",
        "काल",
        "2 दिवसांपूर्वी",
        "मंगळवार, गेल्या आठवड्यात",
        "काल",
        "१ तासापूर्वी",
        "१ मिनिटापूर्वी",
        "काही क्षणांपूर्वी",
        "उद्या",
        "पुढच्या शुक्रवार",
        "पुढच्या मंगळवार",
        "उद्या",
        "१ तासामध्ये",
        "१ मिनिटामध्ये",
        "काही क्षणात",
        "गुरुवार, गेल्या आठवड्यात",
        "शनिवार, गेल्या आठवड्यात",
        "मंगळवार, 3 आठवड्यांपूर्वी",
        "शुक्रवार, गेल्या आठवड्यात",
        "2 दिवसांपूर्वी",
        "२ तासांपूर्वी",
        "२ मिनिटांपूर्वी",
        "२० सेकंदांपूर्वी",
        "पुढच्या रविवार",
        "पुढच्या शनिवार",
        "पुढच्या मंगळवार",
        "पुढच्या शनिवार",
        "2 दिवसात",
        "२ तासांमध्ये",
        "२ मिनिटांमध्ये",
        "२० सेकंदांमध्ये"
    ],
    "ms": [
        "Ahad, 14 Februari 2021 pada 12:34:56 PTG Waktu Universal Selaras",
        "14 Februari 2021 pada 12:34:56 PTG UTC",
        "14/02/21, 12:34 PTG",
        "Ahad, 14 Februari 2021 1613306096000a34 12:34:56 - Selasa, 6 Julai 34 12:34:56 Waktu Semesta Berkoordinat",
        "sekarang",
        "beberapa saat yang lalu",
        "dalam beberapa saat",
        "hari ini",
        "esok",
        "semalam",
        "semalam",
        "2 hari lepas",
        "Selasa, minggu lalu",
        "semalam",
        "1 jam lalu",
        "1 minit lalu",
        "beberapa saat yang lalu",
        "esok",
        "Jumaat depan",
        "Selasa depan",
        "esok",
        "dalam 1 jam",
        "dalam 1 minit",
        "dalam beberapa saat",
        "Khamis, minggu lalu",
        "Sabtu, minggu lalu",
        "Selasa, 3 minggu yang lalu",
        "Jumaat, minggu lalu",
        "2 hari lepas",
        "2 jam lalu",
        "2 minit lalu",
        "20 saat lalu",
        "Ahad depan",
        "Sabtu depan",
        "Selasa depan",
        "Sabtu depan",
        "dalam 2 hari",
        "dalam 2 jam",
        "dalam 2 minit",
        "dalam 20 saat"
    ],
    "nb": [
        "søndag 14. februar 2021 kl. 12:34:56 koordinert universaltid",
        "14. februar 2021 kl. 12:34:56 UTC",
        "14.02.2021, 12:34",
        "søndag 14. februar 2021 kl 12:34:56 - tirsdag 6. juli 12:34:56 Koordinert universell tid",
        "nå",
        "for noen øyeblikk siden",
        "om noen få øyeblikk",
        "i dag",
        "i morgen",
        "i går",
        "i går",
        "2 dager siden",
        "tirsdag, forrige uke",
        "i går",
        "for 1 time siden",
        "for 1 minutt siden",
        "for noen øyeblikk siden",
        "i morgen",
        "neste fredag",
        "neste tirsdag",
        "i morgen",
        "om 1 time",
        "om 1 minutt",
        "om noen få øyeblikk",
        "torsdag, forrige uke",
        "lørdag, forrige uke",
        "tirsdag, for 3 uker siden",
        "fredag, forrige uke",
        "2 dager siden",
        "for 2 timer siden",
        "for 2 minutter siden",
        "for 20 sekunder siden",
        "neste søndag",
        "neste lørdag",
        "neste tirsdag",
        "neste lørdag",
        "om 2 dager",
        "om 2 timer",
        "om 2 minutter",
        "om 20 sekunder"
    ],
    "nl": [
        "zondag 14 februari 2021 om 12:34:56 gecoördineerde wereldtijd",
        "14 februari 2021 om 12:34:56 UTC",
        "14-02-2021, 12:34",
        "zondag 14 februari 2021 o34 12:34:56 - dinsdag 6 juli 34 12:34:56 Gecoördineerde Universele Tijd",
        "nu",
        "enkele ogenblikken geleden",
        "binnen enkele ogenblikken",
        "vandaag",
        "morgen",
        "gisteren",
        "gisteren",
        "2 dagen geleden",
        "vorige week dinsdag",
        "gisteren",
        "1 uur geleden",
        "1 minuut geleden",
        "enkele ogenblikken geleden",
        "morgen",
        "volgende vrijdag",
        "volgende dinsdag",
        "morgen",
        "over 1 uur",
        "over 1 minuut",
        "binnen enkele ogenblikken",
        "vorige week donderdag",
        "vorige week zaterdag",
        "dinsdag, 3 weken geleden",
        "vorige week vrijdag",
        "2 dagen geleden",
        "2 uur geleden",
        "2 minuten geleden",
        "20 seconden geleden",
        "volgende zondag",
        "volgende zaterdag",
        "volgende dinsdag",
        "volgende zaterdag",
        "binnen 2 dagen",
        "over 2 uur",
        "over 2 minuten",
        "over 20 seconden"
    ],
    "pa": [
        "ਐਤਵਾਰ, 14 ਫ਼ਰਵਰੀ 2021 12:34:56 ਬਾ.ਦੁ. ਕੋਔਰਡੀਨੇਟੇਡ ਵਿਆਪਕ ਵੇਲਾ",
        "14 ਫ਼ਰਵਰੀ 2021 12:34:56 ਬਾ.ਦੁ. UTC",
        "14/2/21, 12:34 ਬਾ.ਦੁ.",
        "ਐਤਵਾਰ, 14 ਫ਼ਰਵਰੀ, 2021, 12:34:56 - ਮੰਗਲਵਾਰ, 6 ਜੁਲਾਈ, 12:34:56 ਕੋਆਰਡੀਨੇਟਡ ਯੂਨੀਵਰਸਲ ਟਾਈਮ",
        "ਹੁਣ",
        "ਕੁਝ ਪਲ ਪਹਿਲਾਂ",
        "ਕੁਝ ਪਲਾਂ ਵਿਚ",
        "ਅੱਜ",
        "ਕੱਲ",
        "ਕੱਲ",
        "ਕੱਲ",
        "2 ਦਿਨ ਪਹਿਲਾਂ",
        "ਮੰਗਲਵਾਰ, ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "ਕੱਲ",
        "1 ਘੰਟਾ ਪਹਿਲਾਂ",
        "1 ਮਿੰਟ ਪਹਿਲਾਂ",
        "ਕੁਝ ਪਲ ਪਹਿਲਾਂ",
        "ਕੱਲ",
        "ਅਗਲਾ ਸ਼ੁੱਕਰਵਾਰ",
        "ਅਗਲਾ ਮੰਗਲਵਾਰ",
        "ਕੱਲ",
        "1 ਘੰਟੇ ਵਿੱਚ",
        "1 ਮਿੰਟ ਵਿੱਚ",
        "ਕੁਝ ਪਲਾਂ ਵਿਚ",
        "ਵੀਰਵਾਰ, ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "ਸ਼ਨਿੱਚਰਵਾਰ, ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "ਮੰਗਲਵਾਰ, 3 ਹਫ਼ਤੇ ਪਹਿਲਾਂ",
        "ਸ਼ੁੱਕਰਵਾਰ, ਪਿਛਲੇ ਹਫ਼ਤੇ",
        "2 ਦਿਨ ਪਹਿਲਾਂ",
        "2 ਘੰਟੇ ਪਹਿਲਾਂ",
        "2 ਮਿੰਟ ਪਹਿਲਾਂ",
        "20 ਸਕਿੰਟ ਪਹਿਲਾਂ",
        "ਅਗਲਾ ਐਤਵਾਰ",
        "ਅਗਲਾ ਸ਼ਨਿੱਚਰਵਾਰ",
        "ਅਗਲਾ ਮੰਗਲਵਾਰ",
        "ਅਗਲਾ ਸ਼ਨਿੱਚਰਵਾਰ",
        "2 ਦਿਨਾਂ ਵਿਚ",
        "2 ਘੰਟਿਆਂ ਵਿੱਚ",
        "2 ਮਿੰਟਾਂ ਵਿੱਚ",
        "20 ਸਕਿੰਟਾਂ ਵਿੱਚ"
    ],
    "pl": [
        "niedziela, 14 lutego 2021 12:34:56 uniwersalny czas koordynowany",
        "14 lutego 2021 12:34:56 UTC",
        "14.02.2021, 12:34",
        "niedziela, 14 lutego 2021 o 12:34:56 - wtorek, 6 lipca 12:34:56 Skoordynowany czas uniwersalny",
        "teraz",
        "kilka chwil temu",
        "za kilka chwil",
        "dzisiaj",
        "jutro",
        "wczoraj",
        "wczoraj",
        "2 dni temu",
        "wtorek, ostatni tydzień",
        "wczoraj",
        "1 godzinę temu",
        "1 minutę temu",
        "kilka chwil temu",
        "jutro",
        "w następną piątek",
        "w następną wtorek",
        "jutro",
        "za 1 godzinę",
        "za 1 minutę",
        "za kilka chwil",
        "czwartek, ostatni tydzień",
        "sobota, ostatni tydzień",
        "wtorek, 3 tygodnie temu",
        "piątek, ostatni tydzień",
        "2 dni temu",
        "2 godziny temu",
        "2 minuty temu",
        "20 sekund temu",
        "w następną niedziela",
        "w następną sobota",
        "w następną wtorek",
        "w następną sobota",
        "w 2 dni",
        "za 2 godziny",
        "za 2 minuty",
        "za 20 sekund"
    ],
    "pt": [
        "domingo, 14 de fevereiro de 2021 às 12:34:56 Horário Universal Coordenado",
        "14 de fevereiro de 2021 às 12:34:56 UTC",
        "14/02/2021, 12:34",
        "domingo, 14 de fevereiro de 2021 à56 12:34:56 - terça-feira, 6 de julho de 56 12:34:56 Tempo Universal Coordenado",
        "agora",
        "alguns momentos atrás",
        "em alguns instantes",
        "hoje",
        "amanhã",
        "ontem",
        "ontem",
        "2 dias atrás",
        "terça-feira, semana passada",
        "ontem",
        "há 1 hora",
        "há 1 minuto",
        "alguns momentos atrás",
        "amanhã",
        "próxima sexta-feira",
        "próxima terça-feira",
        "amanhã",
        "em 1 hora",
        "em 1 minuto",
        "em alguns instantes",
        "quinta-feira, semana passada",
        "sábado, semana passada",
        "terça-feira, 3 semanas atrás",
        "sexta-feira, semana passada",
        "2 dias atrás",
        "há 2 horas",
        "há 2 minutos",
        "há 20 segundos",
        "próxima domingo",
        "próxima sábado",
        "próxima terça-feira",
        "próxima sábado",
        "em 2 dias",
        "em 2 horas",
        "em 2 minutos",
        "em 20 segundos"
    ],
    "ro": [
        "duminică, 14 februarie 2021 la 12:34:56 Timpul universal coordonat",
        "14 februarie 2021 la 12:34:56 UTC",
        "14.02.2021, 12:34",
        "duminică, 14 februarie 2021 la 12:34:56 - marți, 6 iulie 12:34:56 ora universală coordonată",
        "acum",
        "acum câteva clipe",
        "în câteva clipe",
        "azi",
        "Mâine",
        "ieri",
        "ieri",
        "acum 2 zile",
        "marți, săptămâna trecută",
        "ieri",
        "acum 1 oră",
        "acum 1 minut",
        "acum câteva clipe",
        "Mâine",
        "vineri viitoare",
        "marți viitoare",
        "Mâine",
        "peste 1 oră",
        "peste 1 minut",
        "în câteva clipe",
        "joi, săptămâna trecută",
        "sâmbătă, săptămâna trecută",
        "marți, acum 3 săptămâni",
        "vineri, săptămâna trecută",
        "acum 2 zile",
        "acum 2 ore",
        "acum 2 minute",
        "acum 20 de secunde",
        "duminică viitoare",
        "sâmbătă viitoare",
        "marți viitoare",
        "sâmbătă viitoare",
        "în 2 zile",
        "peste 2 ore",
        "peste 2 minute",
        "peste 20 de secunde"
    ],
    "ru": [
        "воскресенье, 14 февраля 2021 г. в 12:34:56 Всемирное координированное время",
        "14 февраля 2021 г. в 12:34:56 UTC",
        "14.02.2021, 12:34",
        "воскресенье, 14 февраля 2021 r., в 12:34:56 - вторник, 6 июля 12:34:56 Всемирное координированное время",
        "сейчас",
        "несколько минут назад",
        "через несколько минут",
        "Cегодня",
        "завтра",
        "вчера",
        "вчера",
        "2 дня назад",
        "вторник, lна прошлой неделе",
        "вчера",
        "1 час назад",
        "1 минуту назад",
        "несколько минут назад",
        "завтра",
        "в следующую пятница",
        "в следующую вторник",
        "завтра",
        "через 1 час",
        "через 1 минуту",
        "через несколько минут",
        "четверг, lна прошлой неделе",
        "суббота, lна прошлой неделе",
        "вторник, 3 недели назад",
        "пятница, lна прошлой неделе",
        "2 дня назад",
        "2 часа назад",
        "2 минуты назад",
        "20 секунд назад",
        "в следующую воскресенье",
        "в следующую суббота",
        "в следующую вторник",
        "в следующую суббота",
        "через 2 дня",
        "через 2 часа",
        "через 2 минуты",
        "через 20 секунд"
    ],
    "sk": [
        "nedeľa 14. februára 2021 o 12:34:56 koordinovaný svetový čas",
        "14. februára 2021 o 12:34:56 UTC",
        "14. 2. 2021 12:34",
        "nedeľa 14. februára 2021 o 12:34:56 - utorok 6. júla 12:34:56 Koordinovaný svetový čas",
        "teraz",
        "pred pár okamihmi",
        "za pár okamihov",
        "dnes",
        "zajtra",
        "včera",
        "včera",
        "pred 2 dňami",
        "utorok, minulý týždeň",
        "včera",
        "pred 1 hodinou",
        "pred 1 minútou",
        "pred pár okamihmi",
        "zajtra",
        "budúci piatok",
        "budúci utorok",
        "zajtra",
        "o 1 hodinu",
        "o 1 minútu",
        "za pár okamihov",
        "štvrtok, minulý týždeň",
        "sobota, minulý týždeň",
        "utorok, pred 3 týždňami",
        "piatok, minulý týždeň",
        "pred 2 dňami",
        "pred 2 hodinami",
        "pred 2 minútami",
        "pred 20 sekundami",
        "budúci nedeľa",
        "budúci sobota",
        "budúci utorok",
        "budúci sobota",
        "za 2 dni",
        "o 2 hodiny",
        "o 2 minúty",
        "o 20 sekúnd"
    ],
    "sl": [
        "nedelja, 14. februar 2021 ob 12:34:56 univerzalni koordinirani čas",
        "14. februar 2021 ob 12:34:56 UTC",
        "14. 2. 21, 12:34",
        "nedelja, 14. februar 2021 ob 12:34:56 - torek, 6. julij 12:34:56 Univerzalni koordinirani čas",
        "zdaj",
        "pred nekaj trenutki",
        "v nekaj trenutkih",
        "danes",
        "jutri",
        "včeraj",
        "včeraj",
        "pred 2 dnevi",
        "torek, prejšnji teden",
        "včeraj",
        "pred 1 uro",
        "pred 1 minuto",
        "pred nekaj trenutki",
        "jutri",
        "naslednji petek",
        "naslednji torek",
        "jutri",
        "čez 1 uro",
        "čez 1 minuto",
        "v nekaj trenutkih",
        "četrtek, prejšnji teden",
        "sobota, prejšnji teden",
        "torek, pred 3 tedni",
        "petek, prejšnji teden",
        "pred 2 dnevi",
        "pred 2 urama",
        "pred 2 minutama",
        "pred 20 sekundami",
        "naslednji nedelja",
        "naslednji sobota",
        "naslednji torek",
        "naslednji sobota",
        "v 2 dneh",
        "čez 2 uri",
        "čez 2 minuti",
        "čez 20 sekund"
    ],
    "sr": [
        "недеља, 14. фебруар 2021. 12:34:56 Координисано универзално време",
        "14. фебруар 2021. 12:34:56 UTC",
        "14.2.21. 12:34",
        "недеља, 14. фебруар 2021. у 12:34:56 - уторак, 6. јул 12:34:56 Универзално координисано време",
        "Сада",
        "пре неколико тренутака",
        "за неколико тренутака",
        "данас",
        "сутра",
        "јуче",
        "јуче",
        "пре 2 дана",
        "уторак, прошле недеље",
        "јуче",
        "пре 1 сата",
        "пре 1 минута",
        "пре неколико тренутака",
        "сутра",
        "следећи петак",
        "следећи уторак",
        "сутра",
        "за 1 сат",
        "за 1 минут",
        "за неколико тренутака",
        "четвртак, прошле недеље",
        "субота, прошле недеље",
        "уторак, пре 3 недеље",
        "петак, прошле недеље",
        "пре 2 дана",
        "пре 2 сата",
        "пре 2 минута",
        "пре 20 секунди",
        "следећи недеља",
        "следећи субота",
        "следећи уторак",
        "следећи субота",
        "за 2 дана",
        "за 2 сата",
        "за 2 минута",
        "за 20 секунди"
    ],
    "sv": [
        "söndag 14 februari 2021 kl. 12:34:56 koordinerad universell tid",
        "14 februari 2021 kl. 12:34:56 UTC",
        "2021-02-14 12:34",
        "söndag 14 februari 2021 kl 12:34:56 - tisdag 6 juli 12:34:56 Koordinerad universell tid",
        "nu",
        "för några ögonblick sedan",
        "på några ögonblick",
        "i dag",
        "i morgon",
        "i går",
        "i går",
        "2 dagar sedan",
        "tisdag, förra veckan",
        "i går",
        "för 1 timme sedan",
        "för 1 minut sedan",
        "för några ögonblick sedan",
        "i morgon",
        "nästa fredag",
        "nästa tisdag",
        "i morgon",
        "om 1 timme",
        "om 1 minut",
        "på några ögonblick",
        "torsdag, förra veckan",
        "lördag, förra veckan",
        "tisdag, för 3 veckor sedan",
        "fredag, förra veckan",
        "2 dagar sedan",
        "för 2 timmar sedan",
        "för 2 minuter sedan",
        "för 20 sekunder sedan",
        "nästa söndag",
        "nästa lördag",
        "nästa tisdag",
        "nästa lördag",
        "om 2 dager",
        "om 2 timmar",
        "om 2 minuter",
        "om 20 sekunder"
    ],
    "sw": [
        "Jumapili, 14 Februari 2021, 12:34:56 Mfumo wa kuratibu saa ulimwenguni",
        "14 Februari 2021, 12:34:56 UTC",
        "14/02/2021, 12:34",
        "Jumapili, Februari 14, 2021 56aa 12:34:56 - Jumanne, Julai 6, 56aa 12:34:56 Wakati wa Ulimwengu ulioratibiwa",
        "sasa",
        "dakika chache zilizopita",
        "katika muda mfupi",
        "leo",
        "kesho",
        "jana",
        "jana",
        "siku 2 zilizopita",
        "Jumanne, wiki iliyopita",
        "jana",
        "saa 1 iliyopita",
        "dakika 1 iliyopita",
        "dakika chache zilizopita",
        "kesho",
        "Ijumaa ijayo",
        "Jumanne ijayo",
        "kesho",
        "baada ya saa 1",
        "baada ya dakika 1",
        "katika muda mfupi",
        "Alhamisi, wiki iliyopita",
        "Jumamosi, wiki iliyopita",
        "Jumanne, wiki 3 zilizopita",
        "Ijumaa, wiki iliyopita",
        "siku 2 zilizopita",
        "saa 2 zilizopita",
        "dakika 2 zilizopita",
        "Sekunde 20 zilizopita",
        "Jumapili ijayo",
        "Jumamosi ijayo",
        "Jumanne ijayo",
        "Jumamosi ijayo",
        "kwa siku 2",
        "baada ya saa 2",
        "baada ya dakika 2",
        "baada ya sekunde 20"
    ],
    "ta": [
        "ஞாயிறு, 14 பிப்ரவரி, 2021 அன்று 12:34:56 PM ஒருங்கிணைந்த சர்வதேச நேரம்",
        "14 பிப்ரவரி, 2021 அன்று 12:34:56 PM UTC",
        "14/2/21, 12:34 PM",
        "பிப்ரவரி 14, 2021 ஞாயிறு, 12:34:56 - ஜூலை 6, 12:34:56 ஒருங்கிணைந்த யுனிவர்சல் நேரம்",
        "இப்போது",
        "சில தருணங்களுக்கு முன்பு",
        "சில தருணங்களில்",
        "இன்று",
        "நாளை",
        "நேற்று",
        "நேற்று",
        "2 நாட்களுக்கு முன்பு",
        "கடந்த வாரம் செவ்வாய்",
        "நேற்று",
        "1 மணிநேரம் முன்",
        "1 நிமிடத்திற்கு முன்",
        "சில தருணங்களுக்கு முன்பு",
        "நாளை",
        "அடுத்த வெள்ளி",
        "அடுத்த செவ்வாய்",
        "நாளை",
        "1 மணிநேரத்தில்",
        "1 நிமிடத்தில்",
        "சில தருணங்களில்",
        "கடந்த வாரம் வியாழன்",
        "கடந்த வாரம் சனி",
        "செவ்வாய், 3 வாரங்களுக்கு முன்பு",
        "கடந்த வாரம் வெள்ளி",
        "2 நாட்களுக்கு முன்பு",
        "2 மணிநேரம் முன்",
        "2 நிமிடங்களுக்கு முன்",
        "20 விநாடிகளுக்கு முன்",
        "அடுத்த ஞாயிறு",
        "அடுத்த சனி",
        "அடுத்த செவ்வாய்",
        "அடுத்த சனி",
        "2 நாட்களில்",
        "2 மணிநேரத்தில்",
        "2 நிமிடங்களில்",
        "20 விநாடிகளில்"
    ],
    "te": [
        "14, ఫిబ్రవరి 2021, ఆదివారం 12:34:56 PM సమన్వయ సార్వజనీన సమయంకి",
        "14 ఫిబ్రవరి, 2021 12:34:56 PM UTCకి",
        "14-02-21 12:34 PM",
        "ఫిబ్రవరి 14, 2021, ఆదివారం, 12:34:56 - జులై 6, 12:34:56 సమన్వయ యూనివర్సల్ సమయం",
        "ఇప్పుడు",
        "సెక.",
        "కొన్ని క్షణాల క్రితం",
        "క్రితం",
        "ఈ రోజు",
        "రేపు",
        "రేపు",
        "2 రోజుల క్రితం",
        "వచ్చే మంగళవారం",
        "రేపు",
        "1 గంట క్రితం",
        "1 నిమిషం క్రితం",
        "సెక.",
        "ఈ రోజు",
        "నిన్న",
        "నిన్న",
        "ఈ రోజు",
        "1 గంటలో",
        "1 నిమిషంలో",
        "కొన్ని క్షణాల క్రితం",
        "వచ్చే గురువారం",
        "వచ్చే శనివారం",
        "మంగళవారం సోమవారం",
        "వచ్చే శుక్రవారం",
        "2 రోజుల క్రితం",
        "2 గంటల క్రితం",
        "2 నిమిషాల క్రితం",
        "20 సెకన్ల క్రితం",
        "నిన్న",
        "నిన్న",
        "నిన్న",
        "నిన్న",
        "2 రోజుల్లో",
        "2 గంటల్లో",
        "2 నిమిషాల్లో",
        "20 సెకన్లలో"
    ],
    "th": [
        "วันอาทิตย์ที่ 14 กุมภาพันธ์ พ.ศ. 2564 เวลา 12 นาฬิกา 34 นาที 56 วินาที เวลาสากลเชิงพิกัด",
        "14 กุมภาพันธ์ 2564 เวลา 12 นาฬิกา 34 นาที 56 วินาที UTC",
        "14/2/64 12:34",
        "วันอาทิตย์ 14 กุมภาพันธ์ 2021 12:34:56 - วันอังคาร 6 กรกฎาคม 12:34:56 เวลาสากลเชิงพิกัด",
        "రోజుల్లో",
        "เมื่อสักครู่นี้",
        "ในอีกสักครู่",
        "วันนี้",
        "พรุ่งนี้",
        "เมื่อวาน",
        "เมื่อวาน",
        "2 วันที่ผ่านมา",
        "วันอังคาร อาทิตย์ที่แล้ว",
        "เมื่อวาน",
        "1 ชั่วโมงที่ผ่านมา",
        "1 นาทีที่ผ่านมา",
        "เมื่อสักครู่นี้",
        "พรุ่งนี้",
        "วันศุกร์หน้า",
        "วันอังคารหน้า",
        "พรุ่งนี้",
        "ในอีก 1 ชั่วโมง",
        "ในอีก 1 นาที",
        "ในอีกสักครู่",
        "วันพฤหัสบดี อาทิตย์ที่แล้ว",
        "วันเสาร์ อาทิตย์ที่แล้ว",
        "วันอังคาร, 3 สัปดาห์ก่อน",
        "วันศุกร์ อาทิตย์ที่แล้ว",
        "2 วันที่ผ่านมา",
        "2 ชั่วโมงที่ผ่านมา",
        "2 นาทีที่ผ่านมา",
        "20 วินาทีที่ผ่านมา",
        "วันอาทิตย์หน้า",
        "วันเสาร์หน้า",
        "วันอังคารหน้า",
        "วันเสาร์หน้า",
        "ใน 2 วัน",
        "ในอีก 2 ชั่วโมง",
        "ในอีก 2 นาที",
        "ในอีก 20 วินาที"
    ],
    "tr": [
        "14 Şubat 2021 Pazar 12:34:56 Eş Güdümlü Evrensel Zaman",
        "14 Şubat 2021 12:34:56 UTC",
        "14.02.2021 12:34",
        "Pazar 14 Şubat 2021 at 12:34:56 - Salı 6 Temmuz 12:34:56 Coordinated Universal Time",
        "şimdi",
        "birkaç dakika önce",
        "birkaç dakika içinde",
        "bugün",
        "yarın",
        "dün",
        "dün",
        "2 gün önce",
        "Salı, geçen hafta",
        "dün",
        "1 saat önce",
        "1 dakika önce",
        "birkaç dakika önce",
        "yarın",
        "gelecek Cuma",
        "gelecek Salı",
        "yarın",
        "1 saat sonra",
        "1 dakika sonra",
        "birkaç dakika içinde",
        "Perşembe, geçen hafta",
        "Cumartesi, geçen hafta",
        "Salı, 3 hafta önce",
        "Cuma, geçen hafta",
        "2 gün önce",
        "2 saat önce",
        "2 dakika önce",
        "20 saniye önce",
        "gelecek Pazar",
        "gelecek Cumartesi",
        "gelecek Salı",
        "gelecek Cumartesi",
        "2 gün içerisinde",
        "2 saat sonra",
        "2 dakika sonra",
        "20 saniye sonra"
    ],
    "uk": [
        "неділя, 14 лютого 2021 р. о 12:34:56 за всесвітнім координованим часом",
        "14 лютого 2021 р. о 12:34:56 UTC",
        "14.02.21, 12:34",
        "неділя, 14 лютого 2021 року, o 12:34:56 - вівторок, 6 липня 12:34:56 Універсальний скоординований час",
        "зараз",
        "кілька хвилин тому",
        "за кілька хвилин",
        "сьогодні",
        "завтра",
        "вчора",
        "вчора",
        "2 дні тому",
        "вівторок, минулого тижня",
        "вчора",
        "1 годину тому",
        "1 хвилину тому",
        "кілька хвилин тому",
        "завтра",
        "наступного пʼятниця",
        "наступного вівторок",
        "завтра",
        "через 1 годину",
        "через 1 хвилину",
        "за кілька хвилин",
        "четвер, минулого тижня",
        "субота, минулого тижня",
        "вівторок, 3 тижні тому",
        "пʼятниця, минулого тижня",
        "2 дні тому",
        "2 години тому",
        "2 хвилини тому",
        "20 секунд тому",
        "наступного неділя",
        "наступного субота",
        "наступного вівторок",
        "наступного субота",
        "через 2 дні",
        "через 2 години",
        "через 2 хвилини",
        "через 20 секунд"
    ],
    "uz": [
        "yakshanba, 14-fevral, 2021, 12:34:56 (Koordinatali universal vaqt)",
        "14-fevral, 2021, 12:34:56 (UTC)",
        "14/02/21, 12:34",
        "2021 yil 14-fevral, yakshanba k1613306096ni 56oat 12:34:56 - 6-iyul, seshanba k1625574896ni 56oat 12:34:56 Umumjahon vaqti muvofiqlashtirilgan",
        "hozir",
        "bir necha lahza oldin",
        "bir necha lahzada",
        "Bugun",
        "ertaga",
        "kecha",
        "kecha",
        "2 kun oldin",
        "seshanba, o'tgan hafta",
        "kecha",
        "1 soat oldin",
        "1 daqiqa oldin",
        "bir necha lahza oldin",
        "ertaga",
        "keyingi juma",
        "keyingi seshanba",
        "ertaga",
        "1 soatdan keyin",
        "1 daqiqadan keyin",
        "bir necha lahzada",
        "payshanba, o'tgan hafta",
        "shanba, o'tgan hafta",
        "seshanba, 3 hafta oldin",
        "juma, o'tgan hafta",
        "2 kun oldin",
        "2 soat oldin",
        "2 daqiqa oldin",
        "20 soniya oldin",
        "keyingi yakshanba",
        "keyingi shanba",
        "keyingi seshanba",
        "keyingi shanba",
        "2 kun ichida",
        "2 soatdan keyin",
        "2 daqiqadan keyin",
        "20 soniyadan keyin"
    ],
    "vi": [
        "lúc 12:34:56 Giờ Phối hợp Quốc tế Chủ Nhật, 14 tháng 2, 2021",
        "lúc 12:34:56 UTC 14 tháng 2, 2021",
        "12:34 14/2/21",
        "Chủ Nhật, ngày 14 tháng 2 nă34 2021 lúc 12:34:56 - Thứ Ba, ngày 6 tháng 7 nă34 12:34:56 Giờ phối hợp quốc tế",
        "hiện nay",
        "một vài phút trước",
        "Trong giây lát",
        "hôm nay",
        "Ngày mai",
        "hôm qua",
        "hôm qua",
        "2 ngày trước",
        "Thứ Ba, tuần trước",
        "hôm qua",
        "1 giờ trước",
        "1 phút trước",
        "một vài phút trước",
        "Ngày mai",
        "Thứ Sáu tới",
        "Thứ Ba tới",
        "Ngày mai",
        "sau 1 giờ nữa",
        "sau 1 phút nữa",
        "Trong giây lát",
        "Thứ Năm, tuần trước",
        "Thứ Bảy, tuần trước",
        "Thứ Ba, 3 tuần trước",
        "Thứ Sáu, tuần trước",
        "2 ngày trước",
        "2 giờ trước",
        "2 phút trước",
        "20 giây trước",
        "Chủ Nhật tới",
        "Thứ Bảy tới",
        "Thứ Ba tới",
        "Thứ Bảy tới",
        "trong 2 ngày nữa",
        "sau 2 giờ nữa",
        "sau 2 phút nữa",
        "sau 20 giây nữa"
    ],
    "zh": [
        "2021年2月14日星期日 协调世界时 12:34:56",
        "2021年2月14日 UTC 12:34:56",
        "2021/2/14 12:34",
        "星期日 14 2 2021 at 12:34:56 - 星期二 6 7 12:34:56 Coordinated Universal Time",
        "现在",
        "几分钟前",
        "过一会儿",
        "今天",
        "明天",
        "昨天",
        "昨天",
        "2 天前",
        "星期二, 上周",
        "昨天",
        "1小时前",
        "1分钟前",
        "几分钟前",
        "明天",
        "next 星期五",
        "next 星期二",
        "明天",
        "1小时后",
        "1分钟后",
        "过一会儿",
        "星期四, 上周",
        "星期六, 上周",
        "星期二, 3 周前",
        "星期五, 上周",
        "2 天前",
        "2小时前",
        "2分钟前",
        "20秒钟前",
        "next 星期日",
        "next 星期六",
        "next 星期二",
        "next 星期六",
        "在 2 天",
        "2小时后",
        "2分钟后",
        "20秒钟后"
    ]
}